### ISSUE TITLE
Slider is not working anymore with Vaadin 8.1

### ISSUE THREAD

**Issue by rimqpp** [vaadin/framework#10006]
Schwerwiegend:   java.lang.NoSuchMethodError: org.vaadin.sliderpanel.SliderPanel.setImmediate(Z)V
	at org.vaadin.sliderpanel.SliderPanel.<init>(SliderPanel.java:115)
	at org.vaadin.sliderpanel.SliderPanelBuilder.build(SliderPanelBuilder.java:220)

**Comment by pwilkin** [comment]
https://vaadin.com/directory#!addon/sliderpanel

Use version 2.0.0. 

Plus, this is not a framework issue, Slider is an addon.

**Comment by anasmi** [comment]
As mentioned by @pwilkin, it's an add-on related issue, therefore to get more attention, it would be better to open  issue in its tracker, if the problem still persists.

I will close this issue due to this, but if you disagree with this decision, please comment here and we will re-open it!

Thanks for you contributions and have a nice day! : )
