### ISSUE TITLE
Sometimes, DataProvider.refreshAll() stops to work on Grid...

### ISSUE THREAD

**Issue by TatuLund** [vaadin/framework#10038]
Sometimes 2 refresh requests can break the Grid component. Here, an example that can help you to reproduce the problem.

Thanks to tried to click on Refresh Button several times. After some seconds, the Grid keeps empty until the end. It's very sporadic. You can also put the focus on the refresh button and main "enter" key pressed during some seconds to reproduce the issue.

private volatile Boolean filter = false;

private Stream fetchValue(Boolean filter) {
    if (filter) {
        return Arrays.asList("One", String.valueOf(System.currentTimeMillis())).stream().map(s -> new AtomicReference<>(s));
    } else {
        return Stream.empty();
    }
}

public void init() {
    VerticalLayout mainLayout = new VerticalLayout();
    setCompositionRoot(mainLayout);

    AbstractBackEndDataProvider<AtomicReference<String>, Object> dataProvider = new AbstractBackEndDataProvider<AtomicReference<String>, Object>() {

        @Override
        protected Stream<AtomicReference<String>> fetchFromBackEnd(Query<AtomicReference<String>, Object> query) {
            try {
                Thread.sleep(250);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            return fetchValue(filter);
        }

        @Override
        protected int sizeInBackEnd(Query<AtomicReference<String>, Object> query) {
           return (int) fetchValue(filter).count();
        }
    };

    Grid<AtomicReference<String>> grid = new Grid<>();
    grid.setDataProvider(dataProvider);
    grid.addColumn(AtomicReference::get);
    mainLayout.addComponent(grid);

    Button button = new Button("Refresh");
    button.addClickListener(event1 -> {
            filter = new Boolean(!filter);
            dataProvider.refreshAll();
    });
    mainLayout.addComponent(button);
}

**Comment by wbadam** [comment]
Reproducible example is:
- Given a `Grid` with more than zero rows of data
- Create a filter that filters out _all_ of the rows, returning zero rows of data to display
- Toggle the filter on a button click

If the button is clicked in a very quick succession (e.g. when the focus is on the button and the ENTER key is pressed and held), the data communicator may end up in a _pending hard reset_ state.

On normal operation the following happens:
_1.-2.: apply filter on button click_
_3.-6.: remove filter on button click_

1. `ButtonServerRpc.click()` called from client, **add filter**
2. `DataCommunicatorClientRpc.reset(0)` called from server - client removes all rows
3. `ButtonServerRpc.click()` called from client, **remove filter**
4. `DataCommunicatorClientRpc.reset(2)` called from server - client adds 2 rows
5. `SimpleDataRequestRpc.requestRows(0, 2, 0, 0)` called from client requesting data to fill the rows
6. `DataCommunicatorClientRpc.updateData(dataArray)` called from server and client updates rows with given data

Note that adding the filter requires one server roundtrip (1.-2.) while removing it requires two (3.-6.).

When the requests are fired in a very quick succession, the order of requests may differ from the normal operation. A simple order with which the issue appears is _1, 2, 3, 4, 1, 2, 5, 6_.

The following happens.
- Client requests to remove filter (3)
- Server resets row count to 2 (4)
- **Instead of requesting data**, the client requests to add filter (1)
- Server resets row count to 0 (2)
- **Client requests data after all for the unfiltered rows** (5)
- **Server has the filter on and returns data for 0 rows** (6)

After this there is no way out since `DataCommunicator.reset == true` and the connector is never marked dirty in `hardReset()`.

Note that I logged all these on the server side since the issue is not reproducible with ?debug mode or Developer Tools open on the client.

**Comment by wbadam** [comment]
I cannot check without the dev tools but I suspect that _1-2_ and _5-6_ roundtrips are actually in the same request, only the order of RPC calls are flipped.
