### ISSUE TITLE
Tree collapsing itself

### ISSUE THREAD

**Issue by Joe32** [vaadin/framework#10053]
For bugs, please provide at minimum the following information:
- Vaadin version: 8.1.4
- Description of the bug
Tree collapses itself when there are many nodes on same level (50 in my example) and one of them is clicked to expand.
Occurs on linux chromium and firefox.
![peek 2017-09-21 10-14](https://user-images.githubusercontent.com/3439600/30685695-0bab2428-9eb6-11e7-9999-8ef49e57510b.gif)

- If possible, minimal reproducible example:
[project-name.zip](https://github.com/vaadin/framework/files/1320438/project-name.zip)

**Comment by TatuLund** [comment]
@Joe32  I tend to believe the problem is not in the Tree but in the app. I did not have time to check it now, but I have worked with Tree quite a lot and haven't seen this behavior, e.g. you can check the FileSelect component in this add-on: https://vaadin.com/directory/component/filesystem-dataprovider-add-on
