### ISSUE TITLE
Selected item in ComboBox with icons not shown correctly

### ISSUE THREAD

**Issue by moberwasserlechner** [vaadin/framework#10074]
**Vaadin version**
8.1.4

**Description of the bug**
If I use the ComboBox component with item icons the *selected item* is not shown correctly. The icon is moved over the text like you see it in the screenshot. The items in the list a displayed correctly.

![vaadin_combobox_icon](https://user-images.githubusercontent.com/1049938/30802890-2f38016a-a1e8-11e7-8ae4-1c18243e812e.png)

I'm not sure if this only happens if used in a FormLayout.

**Comment by tsuoanttila** [comment]
Hi @moberwasserlechner, 

can you dig around a bit with an Inspector tool of a browser to see what kind of style does the icon have? We have a test in the framework to see that the icons of selected item align correctly. If using a specific layout breaks it, we need to fix our layout theming so that no longer happens. 

Also a minimal UI code to reproduce this issue with the Valo theme would speed up debugging and fixing this issue.

**Comment by moberwasserlechner** [comment]
Hi @tsuoanttila,

I use the ComboxBox in a *FormLayout* and show it in a *Window*.

![image](https://user-images.githubusercontent.com/1049938/30863276-e7f91a34-a2d0-11e7-9001-621268aeed29.png)

I can't promise when I'm able to put together a minimal UI, but I will try to get back to you.

**Comment by TatuLund** [comment]
Does not reproduce with Sampler https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/combo-box
