### ISSUE TITLE
TreeGrid - only 16 first items are as tree - next ones are at top level

### ISSUE THREAD

**Issue by tomimalkki** [vaadin/framework#10125]
With TreeGrid - only 16 first items are as tree. Then next ones are on top level.

![vaadin_screenshot](https://user-images.githubusercontent.com/32452480/31073681-a0b9b026-a775-11e7-98c9-5535d7f4776d.png)

![vaadin_code](https://user-images.githubusercontent.com/32452480/31073756-e1ffe5d2-a775-11e7-8401-0cd18b831140.png)

**Comment by tomimalkki** [comment]
Vaadin 8.1.5

**Comment by hesara** [comment]
This is because the indentation is implemented in CSS, and by default only 15 levels (+ top level) are generated. See https://github.com/vaadin/framework/blob/master/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L58 .

As a workaround, you can add a similar loop that goes deeper in your theme. You only need to generate the extra levels, not the levels 0-15.

**Comment by tomimalkki** [comment]
How to make the workaround? Why is it limited to 15 levels?

**Comment by hesara** [comment]
16 is an arbitrary limit, but as it is implemented now, some limit is needed to avoid bloating the generated CSS for Tree and TreeGrid. The limit should really be controlled by a variable rather than being hard-coded.

I haven't tested this, but I suppose something like this would work (after the point where valo is included in your theme to get `#{$v-treegrid-class-depth}` replaced with `depth` and `$v-treegrid-indent` replaced with `1.5em` or whatever custom value is used for it):
```
  .v-treegrid-node {
    @for $i from 0 through 15 {
      &.#{$v-treegrid-class-depth}-#{$i} {
        padding-left: $v-treegrid-indent * $i;
      }
    }
  }
```

**Comment by tomimalkki** [comment]
The workaround works.
