### ISSUE TITLE
TreeGrid.getBeanType() always returns null

### ISSUE THREAD

**Issue by rntrp** [vaadin/framework#10195]
**Vaadin Framework version 8.1.5**

**Description of the bug**
TreeGrid.getBeanType() returns `null` even for TreeGrids instantiated via the corresponding constructor:
```java
TreeGrid treeGrid = new TreeGrid(MyBean.class);
Class<?> beanType = treeGrid.getBeanType(); // is null
```

Reason: TreeGrid constructor does not store the bean type:
```java
public TreeGrid(Class<T> beanType) {
  this(BeanPropertySet.get(beanType),
      new HierarchicalDataCommunicator<>());
}
```
Possible solution:
1. Make superclass field `Grid.beanType` protected or package-private
2. Change the above call to `BeanPropertySet.get(this.beanType = beanType)`

**Comment by peergynt** [comment]
Another solution would be to change the constructor like this:

```java
    public TreeGrid(Class<T> beanType) {
        this(BeanPropertySet.get(beanType),
                new HierarchicalDataCommunicator<>());
        setBeanType(beanType)
    }
```

One caveat with this approach is that setPropertySet() would be called twice within the constructor with the same bean type.

Anyway, I has to extend TreeGrid because of beanType not being assigned properly (I'm using the constructor above even though it's not ideal).
