### ISSUE TITLE
Vaadin 7.7.10 with Liferay 6.2, ComboBox:  the popup is now correctly show below the combo box

### ISSUE THREAD

**Issue by joacovela16** [vaadin/framework#10230]
Hi.
We have a problem with combo box when vaadin running as portlet in liferay 6.2 and the page has scroll:  combo's popup aren't displayed below to combo's input. 

This issue can be reproduced using Google Chrome 61 or 62; in previous versions the vaadin app runs right. 

We found this issue for Vaadin 7.6 ( https://dev.vaadin.com/review/#/c/13545/ )

Example are attached.
Thanks

![capture-1](https://user-images.githubusercontent.com/8474046/31834602-dcf9e1ae-b5a4-11e7-9c34-8255224e6bff.png)
![cature-2](https://user-images.githubusercontent.com/8474046/31834606-dfcb2c76-b5a4-11e7-8523-53b05b1845d2.png)

**Comment by TatuLund** [comment]
Can you try out Vaadin version 7.7.12. Recently fix in GWT was made to tackle similar issue.

**Comment by anasmi** [comment]
Hi!

We are going through the process of closing issues, which were fixed in the newer versions of the framework, or have never been verified. 
As it mentioned by @TatuLund the issue should be addressed in the 7.7.12 release.

Also, there was created an extension to address similar problem behaviour. [ComboBoxPopupTracker Add-on](https://vaadin.com/directory/component/comboboxpopuptracker-add-on)

If you disagree with the decision of closing this particular issue, please create here and we will re-open it or create a new one, with explanation and/or example how to reproduce.

Thanks for your help and contributions!
Have a nice day! : )
