### ISSUE TITLE
Binder.setReadOnly(false) makes fields with no setter writeable

### ISSUE THREAD

**Issue by aley2003** [vaadin/framework#10252]
Vaadin 8.1.5
A call of Binder.setReadOnly(false) sets all bound fields to read/write. 
This incudes fields wich setter == null. 
Fields bound with no setter should always be read only.

**Comment by mcollovati** [comment]
Should field be read only even when binding to a property with non accessible setter or without a setter?

**Comment by Legioth** [comment]
My gut feeling is that this should work so that `setReadOnly(false)` would throw `IllegalStateException` in cases when the binding can only be in a readonly mode.

**Comment by aley2003** [comment]
If I bind a Component with setter = null, the field is readOnly per default.
If I call binder.setReadOnly(false) afterwards, the field gets read/write suprisingly. 
The create time rule used (fields with no setter are readOnly) will be ignored. That is the problem from my point of view.

An IllegalStateExceptions would make Binder.setReadOnly() useless in all cases with null Setters.

I would suggest to support the bind time rule (no setter ->readOnly) inBinder.setReadOnly().

**Comment by Legioth** [comment]
The entire `setReadOnly()` method is indeed completely redundant for cases where only one mode can work.

It can be annoying if a method throws unchecked exceptions, but it can on the other hand be very confusing if calling `setReadOnly(false)` would be silently ignored.

**Comment by aley2003** [comment]
We have Dialogs were some of the fields should be read only all the time and for some fields read only has to be switched on and off depending of the state of the Dialog. For this case a setReadOnly(false) enabling only the writable fields (with setter) would be very usefull.
I would not call it "silently ignored" if setReadOnly(false) does not enable fields without setter. bind() without setter does the same. It is a question of the contract for Binder.setReadOnly().

**Comment by mcollovati** [comment]
IMO in a mixed mode (RO an RW fields) it makes sense that Binder.setReadonly(...) silently ignores bindings that are **explicitly** set as RO.

For example having a form that contains also a field whose readonly status is base on runtime conditions (eg user role), I would like having its readonly state managed by Binder only if it is no implicitly RO.
It would be nice if one can do that by simply binding the field with a null setter (or with an explicit bind method `Binding<BEAN, TARGET> bindReadonly(ValueProvider<BEAN, TARGET> getter)`), instead of having to manually manage `HasValue.setReadonly` for each field to avoid a potential `IllegalStateException`.

Something like
```
binder.bind(Bean::maybeReadonlyGetter, adminOnly(Bean::maybeReadonlySetter))
```
where `adminOnly` returns null when the field should be readonly

**Comment by Legioth** [comment]
The case I'm concerned about is when adding `someBinding.setReadOnly(false)` has no effect at all and the developer has now way of understanding why because they don't realize that there is no setting for the binding. A setter being a no-op is acceptable if you expect it to work in that way, but it's a major source of confusion for any developer who isn't familiar with all the underlying assumptions.

Would it make sense to also introduce a method for checking whether RW mode is possible. In that way, an additional check would still be needed when toggling back and forth, but it wouldn't be necessary to catch exceptions for supporting the case. I.e. changing `binding.setReadOnly(desiredSetting)` to `binding.setReadOnly(desiredSetting && !binding.hasSetter());`. This gets slightly ugly because of the additional required negation, but otherwise it could be a compromise between

**Comment by mcollovati** [comment]
AFAIK `setReadonly` is a method of `Binder`, not `Binding`, and it then delegates the call to every bounded field.

Are you suggesting to expose a `setReadonly` method on `Binding` (in addition to `hasSetter`) so developers can/must manually handle RO/RW state by hand in mixed mode?

Sorry for the silly question, but maybe I'm missing something.

**Comment by Legioth** [comment]
You're right. I was confusing `Binder` with `Binding` in this case. Sorry about that!

`Binder.setReadOnly` could and should indeed ignore bindings that don't have a setter.

**Comment by mcollovati** [comment]
Thanks @Legioth. 
So, coming back to my original question, is it correct that, when binding by property name, the field should be readonly if the bean has no accessible setter?
And, to be consistent, shouldn't `bind(String propertyName)` register a null setter instead of a NoOp one?

**Comment by Legioth** [comment]
Seems logical that `bind(String propertyName)` for a property with only a getter but no setter should behave the same way as a binding that explicitly has a `null` setter. Another question is whether that change can be made without impacting backwards compatibility.

**Comment by mcollovati** [comment]
What about having an explicit method to mark as readonly every field bound with a null setter? Something like `binder.ensureReadOnlyBindings()`; this could be invoked by the developer after all bindings are completed and will not be done automatically by the framework.

This way bindings with null setter will behave as before (field is not marked as readonly) but with a single method call we can adjust readonly settings for all bounded fields.

**Comment by Legioth** [comment]
I think there are multiple aspects here.

First, there is what's described in this ticket that `binder.setReadOnly(false)` shouldn't have any effect for bindings that can only be readonly because the setter is `null`.

Second, it might make sense to extend the same logic to also cover bindings that have a no-op setter set through `bind(String propertyName)` in addition to bindings that have a `null` setter. There might be some extreme edge cases that break down by this, but I don't see any big risks here.

A potential follow-up, which should probably be implemented separately, would be that `field.setReadOnly(true)` would be automatically called when creating a binding with a `null` or no-op setter. In most cases, existing application code is probably already doing `setReadOnly(true)` for such fields now. There is however also a small risk that the field component is changed to not emit any new values in some other way, and automatically calling `setReadOnly(true)` might cause some unintended side effects.

Finally, if we have implemented the logic so that bindings with a `null` or no-op setter are always kept as readonly and `field.setReadOnly(true)` is called when a binding is created, then we could potentially simplify the logic by dropping the no-op case and instead making `bind(String propertyName)` use a `null` setter instead of a no-op implementation.

**Comment by tsuoanttila** [comment]
In the code review of the PR we briefly discussed having `Binding::setReadOnly` that would give the user more fine-grained control and allows the `Binding` to decide for itself what does `setReadOnly` mean and how to handle it. Should we implement this approach then `Binder::setReadOnly` would be just a shortcut to call the same for all `Bindings`. Any thoughts on this idea/approach?

**Comment by mcollovati** [comment]
I was thinking about how  `Binding.setReadOnly` and Binding.isReadOnly` should relate to the same methods on `HasValue` field: should they be in sync or may the two values be independent from each other?

**Comment by aley2003** [comment]
There is an other problem with null Setters (see https://github.com/vaadin/framework/issues/10405).
I think this is slightly related to this. The NullPointerExceptions will not allow to use null Setters at all.

**Comment by mcollovati** [comment]
@aley2003 I think this is already fixed on master but not backported to 8.1.x

**Comment by aley2003** [comment]
Thanks for the info

**Comment by Legioth** [comment]
What would `Binding::setReadOnly` do for a binding without a functioning setter (i.e. either `null` or the no-op implementation used for bean properties without setters)?

A no-op would break the general invariant that `getFoo` is expected to return the last value passed to `setFoo`. A runtime exception would be equally unexpected.

**Comment by mcollovati** [comment]
What about having some sort of `BindingReadOnlyHandler` at `Binding` level?
This could be a definded as

```java
interface BindingReadOnlyHandler {
  void readOnlyChange(BindingReadOnlyChange change);
}
class BindingReadOnlyChange(Binding<...> binding, boolean readOnly)

```
and would be configured through `BindingBuilder.withBindingReadOnlyHandler` method.
`Binding` interface will expose a method `readOnlyChange(boolean readOnly)` that will delegate
to the `BindingReadOnlyHandler` instance.

```
interface Binding {
  void readOnlyChange(boolean readOnly);
}
class BindingImpl {
  void readOnlyChange(boolean readOnly) {
    this.bindingReadOnlyHandler.readOnlyChange(new BindingReadOnlyChange(this, readOnly))
  }
}
```

The default implementation (used when no handler is given) will replicate the actual logic in `Binder.serReadOnly`

```java
 readOnlyChange(BindingReadOnlyChange change)  {
    if (change.binding.setter != null) {
       binding.getField().setReadOnly(change.readOnly)
    }
```
`Binder.setReadOnly` will then invoke `Binding.readOnlyChange(bool readonly)` for each binding.

With this solution

a) By default `Binder.setReadOnly` will not affect RO bindings; for RW bindings it will invoke `HasValue.setReadOnly`
b) A developer that wants a more fine-grained control on readonly state could provided a
 custom `BindingReadOnlyHandler` at binding time


BTW, a `Binding.isReadOnly` could be added to decouple logic of BindingReadOnlyHandler; 
`BindingImpl.isReadOnly` may be implemented as `setter == null`. In this case the default handler will be

```java
 readOnlyChange(BindingReadOnlyChange change)  {
    if (!chnge.binding.isReadOnly()) {
       binding.getField().setReadOnly(readOnly)
    }
```

I apologize for any mistakes in my English.

**Comment by Legioth** [comment]
> What about having some sort of `BindingReadOnlyHandler` at `Binding` level?

Looks like quite much complexity for something that should really be quite simple. I'd propose merging the current PR without introducing anything along the lines of `Binding.setReadonly`,  and then considering that method separately.

**Comment by mcollovati** [comment]
Is it worth to open another issue for field readonly initialization inside `BindingBuilder.bind` in case of null setters?

**Comment by tsuoanttila** [comment]
The PR from @mcollovati fixes the immediate issue. There are still some changes we might want to make to give a bit more fine-grained control over the read-only mode in `Binder` and `Binding` as well as provide some helpers about flagging effectively read-only fields in a `Binding` automatically in the `BindingBuilder`
