### ISSUE TITLE
Setting a new renderer on a Grid.Column resets the presentation provider, it should not.

### ISSUE THREAD

**Issue by RobertZenz** [vaadin/framework#10277]
Setting a renderer on a Grid.Column by calling `column.setRenderer(renderer)` will override any previously set presentation provider. This is neither documented nor intuitive because the API makes me believe that this is a valid usecase:

```java
Column column = grid.addColumn(
    valueProvider,
    presentationProvider);

// Some ifs later
column.setRenderer(renderer);
```

This will reset the previously set presentation provider, it should not.

**Comment by RobertZenz** [comment]
Additionally, there is no getter for the presentation provider on the column.

**Comment by tsuoanttila** [comment]
The Column holds no type information about the presentation provider. There's no way to make sure the renderer and the presentation provider are matching at compile time. This decision has been made so far to provide compile time information for the user about non-matching types.

@Legioth do you think we should break the type safety and provide an option to pass in unknown types for renderer + presentation provider?

**Comment by Legioth** [comment]
Both the current and the suggested approach have a significant potential for causing generally surprising results as well as runtime class cast exceptions.

One potential approach that would prevent any surprises but requires some boilerplate code in advanced use cases would be to make `setRenderer(renderer)` always throw if a presentation value provider has ever been explicitly set for that column. To accompany this, there would also have to be a getter for checking whether a column is in that "mode".

**Comment by Legioth** [comment]
@RobertZenz Any thoughts on my suggestion with throwing in cases when there is a custom presentation provider that would be discarded by `setRenderer(renderer)`. This case would then also need some way of checking in advance in what state the column is. There was also a ticket about making it easier to find the currently set presentation provider.

**Comment by RobertZenz** [comment]
@Legioth Why discard it at all? When the renderer and the presentation provider are incompatible it will fail early and fast. Yes, it would be neater to have a certain way to determine that beforehand, but as far as I understand this, there isn't beyond extending the renderer/presentation provides with an additional function to return the source/target type. Additionally, the likelihood that the presentation provider and the renderer are changed at runtime are close to zero, like, really close, I don't see a value in doing that. So I'd argue that the only times these two are set is during the initial creation, which means there are two possible solutions to this:

 1. Remove all methods which allow to set the presentation provider independent of the renderer or vice versa.
 2. Make `setRenderer(...)` not reset the provider.

But I'm viewing this from the point of view of ERP applications, where there is little to no value in "dynamically changing columns", at least in such a way. If I'd have a column which must change its representation based on the content, I'd need a custom renderer anyway. If I'd have a column which should change based on "outside properties", I'd use a completely different column to begin with and only toggle visibility.

**Comment by Legioth** [comment]
The problem is that there isn't enough runtime information for failing early and fast because all the generic type information is removed by the compiler.

Any incompatibility between the presentation provider and the renderer won't be detectable until the runtime encounters a `ClassCastException` when passing a value from the provider into the renderer. This part of the code is run asynchronously without any application code in the calling stack, thus making it quite hard to pinpoint the source of the error.

**Comment by RobertZenz** [comment]
>  Any incompatibility between the presentation provider and the renderer won't be detectable until the runtime encounters a ClassCastException when passing a value from the provider into the renderer.

That is what I mean, though.

> This part of the code is run asynchronously without any application code in the calling stack, thus making it quite hard to pinpoint the source of the error.

Ah, I see, I was not aware of that. Isn't there a mechanism to be able to push errors to the main thread? Or to tell the table "yo, your backend just went haywire"?

**Comment by Legioth** [comment]
> Ah, I see, I was not aware of that. Isn't there a mechanism to be able to push errors to the main thread? 

What matters is that `setRenderer` itself cannot throw the exception, which means that the code that did the invalid `setRenderer` call won't be in the stacktrace. Even without the asynchronous processing that the framework does, `setRenderer` would still be unable to discover the error until at least one item is available, i.e. only after `setItems` or `setDataProvider` has been called.

**Comment by RobertZenz** [comment]
Yes, so? If I see this right there is still plenty of information about what column is broken, which can be included in the exception when it is thrown, for example the ID, the caption, the classes of the providers and renderers. Sure, not perfect, far from it, but receiving the message "Exception when processing column MyColumn" with the original exception attached seems fairly sensible to me.

If you don't want to extend the provider interface (and I'd say you don't want that), processing an exception as it occurs during runtime and then preparing it with useful information seems like the next best step. Or you remove the methods that make it possible to set them independently. But as I said before, I lack the capability to see a scenario in which the columns would be changed dynamically (or from multiple points, for that matter), so there might be use-cases I'm completely missing.

**Comment by Legioth** [comment]
Let's recap the options and their pros and cons.

* Current implementation with `setRenderer(Renderer<V>)` that resets the presentation provider and `setRenderer(ValueProvider<V, P>, Renderer<P>)` that allows including a presentation provider between the value provider and the renderer.
  * Pro: No way of getting type safety issues unless using raw types or unsafe casts
  * Con: Surprising that the presentation provider is discarded.
  * Con: No generic way of finding an existing value to pass to the two-arg overload.
    * This can be mitigated by adding a `ValueProvider<V, ?>  getPresentationProvider()` method, but you'd still have to use raw types of unsafe casts for passing that instance into the two-args `setRenderer` method.
* Same as currently implemented, but make `setRenderer(Renderer<V>)` preserve the presentation provider.
  * Pro: Easy to set a renderer after creating the column if and only if `P` and `V` are the same type.
  * Con: You'd have to use raw types for passing a `Renderer<P>` into `setRenderer(Renderer<V>)`.
  * Con: Surprising asynchronous exception when the new renderer is used with the old presentation provider if the types are mismatching.
  * Con: Changing the currently implemented default would silently break existing implementations that rely on the presentation provider being reset.
* Same as currently implemented, but make `setRenderer(Renderer<V>)` throw if a presentation provider has been set
  * Pro: No way of getting type safety issues unless using raw types or unsafe casts
  * Pro: Instead of a hard-to-debug issue with discarded presentation providers, there would be an explicit message to the developer about why they're doing something "wrong". Depending on the case, there are two different ways of removing the exception:
    * Use the three-argument overload of `addColumn` to set all three pieces at once
    * Use the two-argument overload of `setRenderer`, optionally in combination with `getPresentationProvider` and an usafe cast.
  * Con: Runtime exception is always a surprise
  * Con: No generic way of finding an existing value to pass to the two-arg overload (same as for the original approach).
  * Con: Changing the default would not be fully backwards compatible, but existing code that expect that a custom presentation provider is reset would break in a loud and obvious way.

**Comment by RobertZenz** [comment]
I'm still for the second option, I'm also for a getter to get the presentation provider.

**Comment by Legioth** [comment]
The issue for the presentation provider getter is https://github.com/vaadin/framework/issues/10323

**Comment by Legioth** [comment]
@RobertZenz Of course you prefer the second option. It aligns with your particular usage pattern and you're not the one who would receive complaints from users with other usage patterns after they've shot themselves in the foot. :wink:

I still think a proper solution should still be designed so that the only way of getting runtime type exceptions is by using raw types or explicit casts.

Yet another way of achieving this would be to introduce a `replaceRenderer(Renderer<Object> renderer)` method that doesn't remove the presentation provider, but which instead requires you to supply a renderer instance that can accept whatever output that an unknown presentation provider produces. You can still use that method with e.g. a `Renderer<String>`, but the application code would explicitly have to acknowledge responsibility for the potential runtime type issues that might happen by either using an unsafe cast or using raw types.
