### ISSUE TITLE
Access to Grid.Column's presentationProvider

### ISSUE THREAD

**Issue by apgsga-stb** [vaadin/framework#10323]
For a Grid-to-Excel-Export we would like to use the same presentation providers as in the grid. But currently it's a private field only, so we can't access. Currently we do it that way:
```
final Field getter = Grid.Column.class.getDeclaredField("presentationProvider");
getter.setAccessible(true);
final ValueProvider presentationProvider = (ValueProvider) getter.get(column);
Object displayValue = presentationProvider == null ? value : presentationProvider.apply(value);
```
That does the job, but of course we don't want that in production code. We need at least protected access to the presentationProvider field.

Vaadin 8.1.0

**Comment by Tebra** [comment]
Hi, I have the same use case as @apgsga-stb and need to access the presentation provider of the columns to properly export the wanted data.

This is also an issue in Vaadin 8.4.4

Thanks for checking that out! Love the Framework btw.

**Comment by DALDEI** [comment]
+1 - ran into this myself, presenter and renderer should be able to be independently set and retrieved.
My first attempt to reuse the renderer (just set presenter) threw an exception because I used getRenderer() as the renderer -- the grid code doesnt behave well if the replacement renderer is the same as the existing one.

**Comment by mvysny** [comment]
Also Karibu-Testing would benefit from having this implemented, in order to format the rows of the Grid and assert on the contents: https://github.com/mvysny/karibu-testing/blob/3b22372d6ba25ddf3e4c4bce26cf42069b9bf11d/karibu-testing-v8/src/main/kotlin/com/github/mvysny/kaributesting/v8/Grid.kt#L193
