### ISSUE TITLE
If I do a select all on RichTextArea in Vaadin 8.1.6 the getValue() still has content

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/framework#10338]
For whatever reason sometimes RichTextArea returns the following when it's empty (and no there was no empty break line in the RichTextArea):

`<div style="text-align: justify;"><br></div>`

It would be ideal if it could always return an empty string "" because there is no way to currently do a check to see if the field is empty assuming I'm using Binder.

**Comment by tarekoraby** [comment]
The issue is reproducible in Firefox 74 and Internet Explorer 11 using the following example:

```
public class MyUI extends UI {

	@Override
	protected void init(VaadinRequest vaadinRequest) {
		final VerticalLayout layout = new VerticalLayout();
		final RichTextArea area = new RichTextArea();
		final Label l = new Label(area.getValue(), ContentMode.PREFORMATTED);
		l.setCaption("Value recieved from RichTextArea:");
		final Button b = new Button("get area value", event -> l.setValue(area.getValue()));
		layout.addComponent(area);
		layout.addComponent(b);
		layout.addComponent(l);
		setContent(layout);
	}

	@WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
	@VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
	public static class MyUIServlet extends VaadinServlet {
	}
}
```

Then to reproduce, in:

**Firefox 74:**  

In the RTA, press "Enter" key, then "Backspace" key, then click on the "get area value" button.
Expected: the label should show nothing (i.e. an empty string)
Actual: the label will show the following string : ```<div><br></div>```

**IE11:**  

In the RTA, add some letter(s) (ex. "asdf"), then press "Backspace" key until all text is removed, then click on the "get area value" button.
Expected: the label should show nothing (i.e. an empty string)
Actual: the label will show the following string : ```<p><br></p>```
