### ISSUE TITLE
Vaadin 8 - disabled and read-only textfield

### ISSUE THREAD

**Issue by daviddarrencox** [vaadin/framework#10385]
I am using Vaadin 8.1.2.

A support document ( https://vaadin.com/docs/v8/framework/articles/ReadOnlyVsDisabledFields.html ) states that there is also a visual difference between a disabled and a read-only textfield. At the time speaking this is not the case and _textfield.setReadOnly(true)_ does not seem to do anything different than _textfield.setEnabled(false)_. Visually they both show a disabled and greyed out textfield.

Please resolve the issue for the _Textfield_ to work as described in the linked document.
Thank your very much.

**Comment by anasmi** [comment]
Hi,
thanks for noticing this misleading. This article belongs to Community Articles and because of it also listed under the Vaadin8 documentation, even if it refers to earlier version Vaadin6, so the topics discussed there neither work in Vaadin7/Vaadin8.
If you want to get your textfields  looking the same as in the article, you can add:
```
.v-textfield-readonly{
border:none !important;
background:transparent !important ;
}
```

**Comment by jouni** [comment]
> Visually they both show a disabled and greyed out textfield.

There’s a small difference in the styles (if we are looking at the Valo theme):
- Disabled reduces the opacity of the whole component, so it still has the background color for the input field
- Read-only removes the background color but doesn’t touch the opacity of the component
