### ISSUE TITLE
Binder: Bean level validator inconsistencies and problems

### ISSUE THREAD

**Issue by aley2003** [vaadin/framework#10406]
While trying to use bean level validation with Binder.withValidation() I found the following problems:

1. JavaDoc of Binder.writeBean() and Binder.writeBeanIfValid states, that bean level validation is called only, if field level validation passes with no errors. The implementation in doWriteIfValid() calls bean level validation always. What is right?
2. After calling Binder.withValidation() I get the IllegalStateException("if bean level validators have been configured and no bean is currently set") from Binder.isValid().  Why? How can I use bean level validation in buffered mode?
3. A Validator can return only return 1 ValidationResult with 1 errorMessage. Bean level validations tend to need expensive preparations (database access). It would be helpfull, if 1 Validator could return more than 1 error/ValidationResult.

**Comment by aley2003** [comment]
Does bean level validation in Vaadin mean JSR-303? 
If yes, how can I validate my bean without JSR-303?

**Comment by aley2003** [comment]
I guess the problems are gone with 8.2 (with the exception of 3.)

**Comment by nikkijuk** [comment]
referring to 2 & 8.2.rc1: I get "bean level validators have been configured but no bean is currently set" while using buffered mode (readBean/writeBean) and binder.withValidator(..)

**Comment by nikkijuk** [comment]
It seems that buffered readBean/WriteBean pair works as exprected using bean level withValidator, but there's error in binder.validate() method. So; if one uses binder.validate, has not set bean with set bean (unbuffered) and there's bean level validators exception is thrown.

Important part of stack trace looks like this

Caused by: java.lang.IllegalStateException: Cannot validate binder: bean level validators have been configured but no bean is currently set
	at com.vaadin.data.Binder.validate(Binder.java:1864) ~[vaadin-server-8.2.0.rc1.jar:8.2.0.rc1]

**Comment by nikkijuk** [comment]
Described my findings in separate issue https://github.com/vaadin/framework/issues/10486
