### ISSUE TITLE
Bad Code: UsingRPCToSendEventsToTheClient.asciidoc 

### ISSUE THREAD

**Issue by swallace21** [vaadin/framework#10439]
There is all kinds of code commented out saying it is for "clarity."

This is counterintuitive, because the code is not working. Eclipse is spitting out errors. Just keep it simple and include the full working code. Thanks!

**Comment by anasmi** [comment]
Hi,

there are couple of things to mention. First of all, you need to import proper dependencies to work with client side, as explained here [Client side installation guide](https://vaadin.com/docs/v8/framework/clientside/clientside-installing.html). Therefore, you need:

-  		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-client</artifactId>
		</dependency>

- 		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-client-compiler</artifactId>
		</dependency>

- 		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-shared</artifactId>
		</dependency>

(If you use maven).

There was, through, the mistake in the example, and I have created the pull request, which should replace the wrong import.(Thanks for reporting the issue : ) )

When you will include those dependencies, the project should compile. Also, this particular article in a way is continuation of the [Sending events from the client to the server Using RPC](https://github.com/vaadin/framework/blob/a4464cf209f4fb80f44eb9878a942135762554d2/documentation/articles/SendingEventsFromTheClientToTheServerUsingRPC.asciidoc) and _MyComponentServerRpc _ class could be found from there.

I think including imports will make article less readable, but you are correct in the fact it didn't compile before.

I will close this issue, since it should compile after the changes, but ,please, comment here if you disagree with this decision(and someone of us will re-open  the ticket) or create a new one! 

Thanks for your contributions! 
And have a nice day :)
