### ISSUE TITLE
Removing binding should also hide the required indicator (8.2.0)

### ISSUE THREAD

**Issue by krasnyt** [vaadin/framework#10499]
Calling `asRequired("message")` on `Binding` sets the required indicator visibility to `true`. However, removing the binding from `Binder` keeps the indicator visible. Was this a intention or? It would make sense to hide it again.

Thank you for feedback.

**Comment by knoobie** [comment]
Sounds intentional - because `asRequired `is just as shortcut for:

```
HasValue#setRequiredIndicatorVisible(boolean)
Binder#withValidator(SerializablePredicate, String)
```

The underlying Binder/Binding has no idea that the required indicator was set through him and I think the Binder shouldn't know this. 

You can create a little utility for yourself, that does something like this to remove the required indicator as well:

```
public static void unbindRequired(Binder binder, HasValue<?> field){
    binder.removeBinding(field);
    field.setRequiredIndicatorVisible(false);
}
```

**Comment by krasnyt** [comment]
Ok so it was intentional, closing.
