### ISSUE TITLE
Upload component: fires two FailedEvents after interruptUpload() 

### ISSUE THREAD

**Issue by enver-haase** [vaadin/framework#10516]
I tried when uploading a 45MB file, using updateProgress() to track when the maximum allowed size og 16MB is crossed, call interruptUpload() there.

uploadFailed() is called twice, equal-looking events but different System.identityHashCode.

Investigation reveals that the code in Upload.java:616 ( streamVariable.streamingFailed(event) ) is called twice; from different threads.
In my case they were called http-nio-8080-exec-3 and http-nio-8080-exec8 .

Expect: only one call-back into client code per registered Upload.FailedListener .

I could witness this only happens the first time some instance of "Upload" is used in a new session; any next instance of "Upload" does not expose this behaviour. I tried this with two
"Upload" side-by-side and it does not matter which one I pick first to upload: the one I pick first is the one that exposes the above behaviour. Using Vaadin Spring.

**Comment by Ansku** [comment]
Wasn't able to reproduce with Vaadin 8.3.0.beta2 without Spring at least.

**Comment by enver-haase** [comment]
Present still in Vaadin-8.4.1 breakpoint in Upload.java:1126, StreamVariable.streamingFailed(StreamingErrorEvent event) method.

**Comment by tsuoanttila** [comment]
After testing this for an extended amount of time, I noticed a change of behaviour when running it in the provided test project and the same test UI in the framework project. The main difference between the two is the used Jetty version. The bug seems to happen pretty consistently on Jetty 9.3 and 9.4, but not on Jetty 9.2. I tested the Tomcat 9.0.8 and 8.5.28 without being able to reproduce it. Something in Jetty has changed that makes us not handle properly some events. For now please don't use Jetty 9.3 and 9.4 to avoid this issue. Latest 9.2 was released on the 6th of June this year, so it should be "good enough" replacement for now, while we figure out how to make a proper fix for this issue.

**Comment by Koklin** [comment]
I have same problem with vaadin 7.7.12 - three uploadFailed events are generated after Upload.interruptUpload()

**Comment by Koklin** [comment]
Issue solved by using http://mvnrepository.com/artifact/org.eclipse.jetty/jetty-server/9.2.25.v20180606

<plugin>
<groupId>org.eclipse.jetty</groupId>
<artifactId>jetty-maven-plugin</artifactId>
<version>9.2.25.v20180606</version>
<configuration>
<scanIntervalSeconds>2</scanIntervalSeconds>
</configuration>
</plugin>

<properties>
<jetty.plugin.version>9.2.25.v20180606</jetty.plugin.version>
</properties>
