### ISSUE TITLE
AbstractSingleSelect allow selecting unspecified items

### ISSUE THREAD

**Issue by dangerground** [vaadin/framework#10620]
Vaadin 8.2.1

AbstractSingleSelect inheriting classes like RadioButtonGroup<T> allow selection of items that are of class T, but are not part of the list in setItems(T...).
The problem with this approach is, if using an enum where not all values should be selectable and using a binder with asRequired will not work, because technically the RadioButtonGroup has a value.
There even is a nice TODO in the sourcecode in setSelectedFromServer(T item).

pseudocode:
```
enum Type {
  UNSELECTABLE,
  VALID_VALUE1,
  VALID_VALUE2
};

RadioButtonGroup<Type> field = new RadioButtonGroup<>();
field.setItems(VALID_VALUE1, VALID_VALUE2);
field.setValue(UNSELECTABLE); // works
```

**Comment by Legioth** [comment]
The problem here is that there is no generic way of testing whether the object passed to `setValue` is actually present. It would be doable by iterating through all items when `setItems` is used, but we wouldn't want to iterate through the entire database if a lazy-loading `DataProvider` is used to find items.

**Comment by TatuLund** [comment]
> There even is a nice TODO in the sourcecode in setSelectedFromServer(T item)

This has been implemented by https://github.com/vaadin/framework/pull/10796
