### ISSUE TITLE
ComboBox selected item change on blur

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/framework#10707]
Vaadin version: 8.1.5, but probably this can be reproduced with newer versions.
If there is a ValueChangeListener that takes a long time to process, this problem is more noticeable.
If you select an option that triggers a `ValueChangeListener`, and while you're waiting it to finish, you lose focus by (for example) clicking outside the component, it will change the selection to the previous selected one, until the request finishes, and then it will change it again to the one that you have selected.
That is confusing for users. I'm attaching an animated gif that shows the problem. It's easy to reproduce, just add a `ValueChangeListener` that sends the _Thread_ to sleep for some time and then select an option, while you're waiting the request to end, just click outside and you will see how the selection changes to the previous one until it's done, and then will change back to the selected item.

![comboboxblurproblem](https://user-images.githubusercontent.com/28312758/37308727-a8769078-261d-11e8-93ed-ebcef3e5a3c8.gif)

**Comment by tsuoanttila** [comment]
Using long running operations in `ValueChangeListeners` will always be a bit confusing for users. There are some tricks you can use to make it a bit less confusing at least.

First I'd suggest running the long part in a separate thread and using `@Push` and `UI.access` to run the parts of code that do the modifications to the UI.

Since there's a potential conflict with user continuing to use the UI component while your thread is running, you can limit what the user can do while it is running by setting the `ComboBox` to be read-only when the operation is running, and returning the control to the user at the end of the operation:

```
comboBox.addValueChangeListener(e -> {
  comboBox.setReadOnly(true);
  new Thread(() -> {
    longRunningTask();
    comboBox.getUI().access(() -> {
      comboBox.setValue(someValue);
      comboBox.setReadOnly(false);
    });
  }).start();
});
```

In addition you can display some animated spinner icon on the ComboBox when the action is running to make it evident for the user that the change is being processed.

**Comment by mlopezFC** [comment]
Your idea is great. Here's a code snippet just in case somebody is interested:

```
@Theme("mytheme")
@Push
public class MyUI extends UI {

	@Override
	protected void init(VaadinRequest vaadinRequest) {
		final VerticalLayout layout = new VerticalLayout();

		ComboBox<String> cb = new ComboBox<>();
		cb.setItems("Option 1", "Option 2", "Option 3", "Option 4", "Option 5");
		cb.addValueChangeListener(ev -> {
			cb.setReadOnly(true);
			new Thread(() -> {
				try {
					Thread.sleep(5000);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
				cb.getUI().access(() -> {
					cb.setReadOnly(false);
				});
			}).start();
		});

		layout.addComponents(cb);

		setContent(layout);
	}

	@WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
	@VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
	public static class MyUIServlet extends VaadinServlet {
	}
}
```
