### ISSUE TITLE
VaadinIcons.java links incorrect page

### ISSUE THREAD

**Issue by mvysny** [vaadin/framework#10804]
The `com.vaadin.icons.VaadinIcons` in `vaadin-server-8.3.3.jar` links to https://vaadin.com/vaadin-icons in the Javadoc, but that's a 404. The correct link should be https://vaadin.com/components/vaadin-icons/html-examples/icons-basic-demos

**Comment by anasmi** [comment]
Hi @mvysny ,

I am not sure this is correct link either. Maybe [https://vaadin.com/docs/v8/framework/themes/themes-fonticon.html](https://vaadin.com/docs/v8/framework/themes/themes-fonticon.html)? 

Because you link is pointing to components, I am not sure that the one that should be mentioned in javadocs.

(Through issue is valid,the page in javadocs is showing 404)

**Comment by mvysny** [comment]
Or even https://pro.vaadin.com/icons

**Comment by mvysny** [comment]
Please find the first PR here: https://github.com/vaadin/vaadin-icons-addon/pull/17
