### ISSUE TITLE
Menubar repaint issue on browser resize

### ISSUE THREAD

**Issue by tomekkup** [vaadin/framework#10814]
**Scenario:**
When user resize browser window then menubar component paints triangles which shows that menubar has items which cannot fit on screen. 
When we maximize browser window then all items should be shown again.
**Issue:**
After resizing items are duplicated.

![dzwonki3](https://user-images.githubusercontent.com/1681135/38628788-80c7e14c-3db2-11e8-95fe-fee32fb08731.png)

**Comment by Wnt** [comment]
Seems to be caused by a client-side `IndexOutOfBoundsException`:
![image](https://user-images.githubusercontent.com/886091/47808405-f99c0100-dd46-11e8-8238-83e7d9a63b66.png)
the root cause is the `getParentMenu().getItems().get(0)` call in `VMenuBar`:
![image](https://user-images.githubusercontent.com/886091/47808473-2223fb00-dd47-11e8-8d57-326708644da2.png)
