### ISSUE TITLE
Binder writing to bean only when readOnly == false?

### ISSUE THREAD

**Issue by krizda** [vaadin/framework#10897]
Why did you change this? We have a application that has buttons that change only status when read only. This means a readOnly binder with active workflow buttons.
When setting value to Combobox ir changes everything on the UI and Combobox, but when I call binder.getBean() it returns old value(not the one at UI). This means that user sees new workflow status, and when saving on bean is called, the old value is saved.

  if (!isReadOnly()) {
         result.ifOk(value -> setter.accept(bean, 
}

This is a huge problem to our application.
Maby add another parameter - Boolean setIfReadOnly = false; and provide user with setter.

This is critical to our application.

Problematic method:
 private BindingValidationStatus<TARGET> writeFieldValue(BEAN bean) {
            assert bean != null;

            Result<TARGET> result = doConversion();
            if (!isReadOnly()) {
                result.ifOk(value -> setter.accept(bean, value));
            }
            return toValidationStatus(result);
        }

**Comment by tsuoanttila** [comment]
The `isReadOnly` you're seeing there is the `setReadOnly(boolean)` of the `Binding`. This does not prevent you from setting the `HasValue` to be read-only and have the `Binder` still write the values. If you are facing issues with this, please provide a failing code sample with steps to reproduce along with expected and actual results, so we can validate the issue and fix what is in need of fixing.

**Comment by krizda** [comment]
I attached a demo project where you can see how UI provides information that is not relevant to info that will be saved. 

[demoVaadin.zip](https://github.com/vaadin/framework/files/1982874/demoVaadin.zip)

**Comment by tsuoanttila** [comment]
From your example I switched the `setReadOnly` button to call `binder.getFields().forEach(field -> field.setReadOnly(!field.isReadOnly))` instead of toggling the `readOnly` status of the whole `Binder`. This makes the UI components read only but will make the `Binder` update the values as expected.

Before this semantics changed there were lots of discussion on the weird behaviour of read-only. So instead of keeping it in a broken state where you could start throwing `NPE`s from calling a wrong method, we provided explicit control over each and every individual part of the whole structure. `Binder.setReadOnly()` is a shorthand for marking every `Binding` read-only. Marking a `Binding` read-only also marks the `HasValue` read only to indicate to the user that changes in this component will not be saved. `Binding` that is read-only will not be handled by the `Binder`.

When making these changes we were aware of the use-case of yours and made sure that it's still doable. You can control the read-only state of an individual `HasValue` instead of the `Binding`, preventing the user from making changes but still allowing programmatic changes. 

To read parts of the discussion on this topic, you can go through the discussions in #10252 #10368 and #10476

If you have enhancement suggestions on how to make it even better for an application developer, please voice your ideas and concerns, so that I can take them into account when looking how to develop things further in 8.5.

I will close this ticket, but you can still comment here and any enhancement ideas you have should go to a new ticket. If you don't want to open one yourself, just comment here and I will open one for you.
