### ISSUE TITLE
FileDownloader: Dynamically generated files not generated in Firefox due to caching

### ISSUE THREAD

**Issue by mirkoliver** [vaadin/framework#10909]
I'm using the Vaadin FileDownloader.

When clicking on the corresponding button for the first time, Firefox caches the downloaded file. If I'm not refreshing the screen, the second time the browser doesn't contact FileDownloader anymore but immediately offers the cached file.

The files I'm downloading are dynamically generated before download - so I need an option to switch off this browser behaviour.

I've found this link: https://stackoverflow.com/questions/12331993/how-to-disable-browser-caching-in-vaadin?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa ...

... but how can I do this with FileDownloader?

**Comment by mcollovati** [comment]
Have you tried with `StreamResource.setCacheTime(0)`?

**Comment by mobileWMS** [comment]
yes, in my case `FileResource.setCacheTime(0);` fixed my Firefox issue.

**Comment by mirkoliver** [comment]
Great! Thanks for the hint. This works!

**Comment by ideat** [comment]
Hi, thanks for you answer, please you can can share part of your code, still have the problem

**Comment by mobileWMS** [comment]
I literally just called the setCacheTime(0) method, nothing much else.  Here is some code:
```
FileResource csvFileResource = generateCsvDataFile();
csvFileResource.setCacheTime(0);
```
And generateCsvDataFile() talks to backend process to construct a CSV:
```
	private FileResource generateCsvDataFile() throws WMSException {
		String fileName = getCsvDataFileName();

		if( fileName == null || fileName.trim().isEmpty() )
			throw new WMSException("No data file to download");

		File csvFile = new File(fileName);
		if( !csvFile.exists())
			throw new WMSException("Data file " + fileName + " does not exist");

		LOGGER.info(
				"File " + csvFile.getName() +
				" at " + csvFile.getParent() +
				", size " + csvFile.length() );
		FileResource csvFileResource = new FileResource(csvFile);

		return csvFileResource;
	}
```
Maybe you are having another issue.  This issue seems to only happen with Firefox, and is easily repeatable - every single time in a single session it will get the same file you downloaded the first time.  It was rather consistent.  The above code so far has NOT broken the other browsers, but in my case it actually makes sense to turn off caching anyway.  Hope that helps.
