### ISSUE TITLE
RequiredFieldConfigurator should support javax.validation @NotEmpty annotation

### ISSUE THREAD

**Issue by dominic-simplan** [vaadin/framework#10914]
Currently, be RequiredFieldConfigurator only supports the `org.hibernate.validator.constraints.NotEmpty` annotation.
Instead (or additionally), it should support `javax.validation.constraints.NotEmpty`.

**Comment by mlopezFC** [comment]
Vaadin 8 depends on `javax.validation:validation-api:1.0.0.GA` and `javax.validation.constraints.NotEmpty` is implemented [since version 2.0.0](https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints/NotEmpty.html), so that would require an update of that dependency.
But given that the actual check is done by reflection (hibernate-validator is not a transitive dependency) it might possible to implement it easily, but without the correspondent unit test (adding the dependency just for testing would be impossible given that validation-api is a transitive dependency).
