### ISSUE TITLE
Vaadin Grid .setColumns() causes client side exception

### ISSUE THREAD

**Issue by keshan-git** [vaadin/framework#10928]
_Vaadin Framework version - 8.4.2
Browser version - Google Chrome Version 66.0.3359.139 (Official Build) (64-bit)_

**Description of the bug**

1. Create a basic vaadin grid with multiple columns
2. Sort the grid based on one column (explicitly)
3. Use setColumns() method to show only the columns, except the column used to sort

**Minimal reproducible example**
``` java
protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
	Grid<Person> grid = new Grid<>();
	grid.setSizeFull();
	grid.addColumn(bean -> bean.id).setId("id");
	grid.addColumn(bean -> bean.name).setId("name").setCaption("Name");
	grid.sort("id", SortDirection.ASCENDING);
	grid.setColumns("name");
        layout.addComponents(grid);
        setContent(layout);
}
```
**Expected output**
Grid should show other columns (except the id column) and sort based on the id

**Actual output**

- Throws an exception in client side
- Grid is not rendered properly
-- Cell headers are missing
-- Grid doesn't resize properly

_SEVERE: Error sending state change events
com.google.gwt.event.shared.UmbrellaException: Exception caught: Grid column reference can not be null!_

**Comment by tsuoanttila** [comment]
Hi @keshan-git and thanks for the bug report. 

It seems that the sort order in the state of the Grid is not properly updated when a column is removed. This makes the client-side try to display the sorting on a column that does not exist in the Grid.

You can work around this issue by either setting the `id` column `setHidden(true)` and `setHidable(false)`. This will make the id column exist but not be visible nor can it be made visible by the end user. 

If you're using an `InMemoryDataProvider` you should provide the default sorting via `InMemoryDataProvider::setSortOrder(ValueProvider, SortDirection)` rather than making it through the Grid. When you use the `setSortOrder` meaning any sorting set in the Grid is checked first and in case of ties the provided sort order is used.
