### ISSUE TITLE
Grid Editor does not open for the first row

### ISSUE THREAD

**Issue by pepkaQQ** [vaadin/framework#10931]
### Description
Editor does not open for the first row

### Steps to reproduce
```
        Grid<Person> grid = new Grid<>();
        grid.getEditor().setEnabled(true);

        //Add data to grid
        //Double click on first row, editor doesn't open.
```

**Comment by tsuoanttila** [comment]
I tested this quickly with a single module archetype using 8.4.2 and I was unable to reproduce this issue.

**Comment by TatuLund** [comment]
We have observed this in another project and it seems that it is reproducible also with Sampler. We did some further observations.

- The problem seems to appear only with Chrome when browser window is smaller than full screen
- The problem seems not to reproduce with IE11 or Firefox
- The problem does not reproduce when you have browser in full screen mode in Windows
- 8.3.3 works, so this is probably a regression

**Comment by sergey-vaadin** [comment]
Reproduced also with small demo project, screen size ~ 650 x 275 px, zoom 110%.

**Comment by sergey-vaadin** [comment]
https://github.com/vaadin/framework/pull/10674/commits/10a4b7ed14cd658bdc348b99d032aae0514e4846
Grid.java row 1606
in row 1609 ()->show(rowIndex, columnIndexDOM))  is never called

**Comment by sergey-vaadin** [comment]
This patch fixed the problem in my custom build: in Grid.java::waitUntilVisible (row 7471): replace rowElement.getAbsoluteTop() with rowElement.getAbsoluteTop() + bottomBorder

**Comment by asarraf21** [comment]
I had the same problem with Vaadin `8.5.0`, where editing a single row wasn't working and was also affecting editing of subsequent rows that were added later. After reading the comments, I increased the grid height and the problem was solved.
