### ISSUE TITLE
Remove Vaadin version mentions in the webapp client side

### ISSUE THREAD

**Issue by fabcan** [vaadin/framework#10958]
This ticket is a revamp of #8330 as per `stale bot` request.

- **Vaadin Framework version**
8.4.2 and 7.7.13 (we use both in ifferent projects)

- **Browser version**
Google Chrome 67.0.3396.62 64 bit

- **Web container name and version**
Apache tomcat 8.5.31, Java 1.8.172

- **Description of the bug**
From a security standpoint, making it easy for an attacker to know the usage of specific frameworks within a web application (Vaadin and Atmosphere specifically, but also the themes) and furthermore knowing their version, is without any doubts wrong. While using Vaadin, even if the `productionMode` parameter is set to `true`, the client side code is full of Vaadin references also specifying its version.
I am not naive, I know that there are still ways to fingerprint the application and to understand which version or version might use, but is far more complicated than reading the web page source code.

- **Minimal reproducible example**
Open browser, digit the URL of a running web application and open it. Open the browser console (`F12` in Chrome), click on the Elements tab,  press `CTRL+F` and search for the query string `v=`.

- **Expected behavior**
Best case scenario, no reference to Vaadin, Atmosphere and any other framework/theme or versions of any kind.
Acceptable scenario, no references to the software versions used.

- **Actual behavior**
It shows a lot of information that could help an attacker and which should be irrelevant for the correct execution of the application (at least client side).

**Comment by Legioth** [comment]
I listed the reasons for having the version number available in https://github.com/vaadin/framework/issues/10955#issuecomment-393536219.

1. Could be fixed by automatically using a hash if the file is available on the app server and otherwise fall back to using the version number.
2. Would have to be handled by the application developer. We could help out by implementing a property that can be set in the application's own `.gwt.xml` file to configure it to not compile in the version number.
3. Is impossible to fix.

**Comment by fabcan** [comment]
1. I wonder how other frameworks and applications do, because I'm sure that, at least for the non trained eye, it seems they can avoid listing the version. Using a hash seems a reasonable way, even though in the end it will be possible to fingerprint the set of hashes with a specific version or with a range of versions, but it is still more work to do for the attackers.
An interesting thing could be to have a `no-cache` param in the `web.xml`, that way if the application is not cacheable (for several reasons, for example we force `no-cache` headers) the version number it is not required anymore and not even the hash.

1. Being able to have a production and a debug widgetset is an interesting opportunity, in the end everyone is using ant, maven or other tools to create its distribution, so it won't be a problem I guess. 

1. As stated above, those are just ways to delay a motivated attacker and discourage unmotivated ones, it is impossible to have 0 risk and 0 vulnerabilities, so it is fine.

**Comment by Legioth** [comment]
1. Most frameworks don't do it because they are either purely client-side or purely server-side. Not caching mostly-static files such as the bootstrap script or the main theme would be bad for performance. It's not something we'd like to recommend or ship as the default solution. Fingerprinting based on the hash shouldn't really be a problem since you could just as well fingerprint based on the actual file contents instead.
2. It would surely be doable, but it would still require some effort in any application to e.g. configure the `vaadin-maven-plugin` in a slightly different way for a separate production profile. Some extra complexity would be needed in an application without any own GWT code or add-ons since they woudl then be using the bundled `DefaultWidgetSet` for which there would also have to be two separate versions in separate jar files. I actually also realized that there's a similar version compiled in to the theme version as well.

One interesting observation is also that e.g. https://www.youtube.com/ doesn't bother hiding the versions of their client-side dependencies. You can open the browser console there and type in `Polymer.version` to see that they're currently using version `1.11.3`. Vaadin is in that sense in a special position since the client-side version number also gives away the version that is running on the server since those two are always the same.
