### ISSUE TITLE
TwinColSelect low performance

### ISSUE THREAD

**Issue by AndreiBoaghe** [vaadin/framework#11025]
**- Vaadin Framework version**
8.4.3 (but I think you can reproduce it with all 8.x versions)

**- Browser version:** 
Chrome 67.0.3396.99 (64-bit), Firefox 61.0 (64-bit)

**- Web container name and version**
Apache Tomcat 7.0.47, Java 1.8.0_151

**- Description of the bug**
I am using TwinColSelect with ListDataProvider (with amount of items (10k+) ) and have noticed that its performance drastically differs in Chrome in comparison with Firefox. Selecting items using double click in Chrome takes around 5 seconds+ when in Firefox it works almost instantly (1 - 2 seconds). 

**- Minimal reproducible example**

```sh

...

TwinColSelect<String> twinColSelect = new TwinColSelect<>(); 
twinColSelect.setDataProvider(DataProvider.ofCollection(generateRandomStrings(10000)));
UI.getCurrent().addWindow(new Window("Test TwinColSelect performance", twinColSelect));

...

private List<String> generateRandomStrings(Integer count) {
        Random random = new Random();
        List<String> resultList = new ArrayList<>();

        for (int i = 0; i < count; ++i) {
            byte[] bytes = new byte[25];
            random.nextBytes(bytes);
            resultList.add(new String(bytes));
        }

        return resultList;
    }
```

**Comment by TatuLund** [comment]
TwinColSelect does not have server - client lazy loading, which means that if you have 10 000 items in it, that starts to be slow, since all of those items needs to be loaded to Browser at once, etc. This problem can be avoided if you write custom component (it is fully possible to do one as server side custom component) which mimics TwinColSelect using two Grid's instead. Grid has lazy loading mechanism.

**Comment by ZheSun88** [comment]
Fixed by Javadoc improvements
