### ISSUE TITLE
Vaadin Grid Row Header does not display text when header only contains one column

### ISSUE THREAD

**Issue by andrewsavino1** [vaadin/framework#11027]
Scenario: create a Grid and append a new header row.  Then, add columns to the grid.

join these columns into the headerRow (myHeaderRow.join(getColumn("1"),...), etc)

If I then try to add a label to this header row cell (myCell.setText("[label]")), the text will only appear if the headerRow contains multiple columns.  If the headerRow contains only 1 column, the text will not appear, but no Java exception appears.

Looking into it further, an exception is thrown somewhere in the JavaScript.

Vaadin Framework version (e.g. 8.3.1) for Java 8
- Google Chrome, or Safari
Using Spring

**Comment by elmot** [comment]
Can you reproduce your case at https://vaadinfiddle.com/editor/? 
(And share the link here)

**Comment by andrewsavino1** [comment]
This website loads a blank page for me.

**Comment by elmot** [comment]
Ok, can you, please provide a minimal reproducible example code?

**Comment by tsuoanttila** [comment]
Tested this just now with both 8.3.1 using the following simple Grid setup:
```
Grid<String> grid = new Grid<>();
grid.addColumn(t -> t).setCaption("Foo").setId("foo");
grid.addColumn(t -> t).setCaption("Bar").setId("bar");
grid.appendHeaderRow().join("foo", "bar").setText("Baz!");
```

Seemed to work as expected in both cases. How does your setup that is broken differ from this?

**Comment by Ansku** [comment]
@quartelh is that by any chance a vaadin-grid that you are using in your example? This repository is for Vaadin 8 issues and the example code doesn't compile with that. Vaadin 10+ issues live in [vaadin/platform](https://github.com/vaadin/platform) and vaadin-grid issues in particular go to [vaadin/vaadin-grid](https://github.com/vaadin/vaadin-grid).

I tried stripping down and modifying the example for Vaadin 8 compatibility, but couldn't reproduce the issue. It's of course entirely possible that I removed something crucial in my conversion project, or the issue is only present in newer Vaadin versions.

**Comment by quartelh** [comment]
> @quartelh is that by any chance a vaadin-grid that you are using in your example? This repository is for Vaadin 8 issues and the example code doesn't compile with that. Vaadin 10+ issues live in [vaadin/platform](https://github.com/vaadin/platform) and vaadin-grid issues in particular go to [vaadin/vaadin-grid](https://github.com/vaadin/vaadin-grid).
> 
> I tried stripping down and modifying the example for Vaadin 8 compatibility, but couldn't reproduce the issue. It's of course entirely possible that I removed something crucial in my conversion project, or the issue is only present in newer Vaadin versions.

You are absolutely right. My code is Vaadin 14 (hence flow) and not Vaadin 8.
I m sorry for opening this issue in the wrong repo.

**Comment by TatuLund** [comment]
@quartelh , thanks for confirming. I closed this issue as cannot reproduce to avoid further confusion.
