### ISSUE TITLE
TabSheet  - "Add new tab" button

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1106]
**Originally by _bfreitas_**

___
Firefox UI pattern for dynamically add new tab.[[BR]]
Forum discussion topic:[[BR]]
[http://vaadin.com/forum/-/message_boards/message/161706]

___
 Imported from https://dev.vaadin.com/ issue #5034

**Comment by anasmi** [comment]
Hi,

I am not able to view the post anymore, therefore I am not sure, what the exact discussion was and how feature should look like.
Hi!

We are going through the process of closing issues, which were fixed in the newer versions of the framework, won't be fixed or have never been verified. 
If it's still not implemented in newer versions, please, ping us and we will re-open this issue or create a new one, with a description, how you want to see it.

Thanks for your help and contributions!
