### ISSUE TITLE
Expanding a component in a PopupView

### ISSUE THREAD

**Issue by HappyLuke** [vaadin/framework#11187]
I believe this issue is a bug in the PopupView Component and therefor I open a GitHub issue for this.
I already ask a question in StackOverflow, describing this issue:
https://stackoverflow.com/q/52296259/9687804

I am using Vaadin 8.5.2, and tested it with Chrome 68.0.3440.106 (64-bit) and Firefox 62.0 (64-bit).

I am using an embedded Tomcat Container (version 8.5.32) with Spring Boot (version 2.0.4).

Here you find a working code example to reproduce the issue: https://github.com/HappyLuke/vaadin-issue-1

I expect the button to be inside the PopupView, however, it is shown outside the PopupView. When expanding a tree component or changing the DateField value, the button will move into the PopupView as expected.

Thanks for any support!

**Comment by scardanzan** [comment]
The issue is reproducible in 8.10.4. In your sample project you could set the expand ratio of the button to something like 0.2f, that will make the initial render look better, but the button will still move after you take an action just like its does in your sample. It will move a lot less and look better but its not really a solution.
