### ISSUE TITLE
7.7.16 release/changelog missing

### ISSUE THREAD

**Issue by tzaeschke** [vaadin/framework#11271]
The website references a release 7.7.16:

[https://vaadin.com/download/release/7.7/7.7.16/release-notes.html#changelog](https://vaadin.com/download/release/7.7/7.7.16/release-notes.html#changelog)

However, if I click on the changlelog, it references 7.7.16 on GitHub, which does not exist:

[https://github.com/vaadin/framework/releases/tag/7.7.16](https://github.com/vaadin/framework/releases/tag/7.7.16)

Workaround: Is there another way to view the Changelog?

**Comment by tzaeschke** [comment]
There are also no artefacts on maven central (vaadin-server, vaadin-client, ...) for 7.7.16. It appears 7.7.16 has never been released?

**Comment by anasmi** [comment]
Hi,

and thank you for bringing up this issue : )

First of all, sorry for the inconveniences! As you have noticed, there is no artifacts on maven central, this is because we haven't planned to release 7.7.16. It looks like notes were out by an accident.

Therefore, there is no 7.7.16 release and we will try to remove release notes as soon as possible. Thank you for reporting the issue and sorry again for the misleading information.

**Comment by anasmi** [comment]
Hi,

the 7.7.16 was released yesterday and all the relevant files should be now in place. 
Sorry for the confusion again!
