### ISSUE TITLE
Allow setting the HTML "name" attribute

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1129]
**Originally by _Michel Jung_**

___
The browser's suggestion doesn't work with text fields created by vaadin, as there is no "name" attribute.
Even new suggestions (values entered in vaadin applications) won't be added by the browsers, it's desirable to be able to set the name attribute. If a field is named "email", the user at least gets the e-mail addresses he entered before somewhere else.

And we never now; maybe the browser programmers conditions of whether to add a value or not.

Without a name attribute, vaadin will probably never be able to support suggestion. Setting the "id" attribute using setDebugId() is at most a bad workaround.

___
 Imported from https://dev.vaadin.com/ issue #5146

**Comment by marcieldeg** [comment]
Chrome fills user and password fields using the name property. Because this property is not created by Vaadin, Chrome automatically fills out undue fields. For example, I have a user registration form, where there are the user and password fields. When you try to register a new user, the fields are populated by the browser, which is not expected behavior. The "id" field is not considered by Chrome for this purpose.

**Comment by marcieldeg** [comment]
Please reconsider this call.
