### ISSUE TITLE
Grid selection not cleared on DataChangeEvent

### ISSUE THREAD

**Issue by FSchliephacke** [vaadin/framework#11344]
Vaadin Framework version: 8.6.2
Browser: Firefox: 60.3.0esr (64-Bit)
Web Container: Apache Tomcat 9.0.5

On recieving a DataChangeEvent, the Grid Component does not clear its selection, keeping data in the selection that is actually not in the Grid anymore.
We fixed this by overwriting the Grid::internalSetDataProvider(DataProvider) method and registering a DataChangeListener calling Grid::deselectAll.

Minimal example:

```Java
Collection<String> c = new ArrayList<>();
CallbackDataProvider<String, ?> dataProvider = new CallbackDataProvider<>(q -> c.stream(), q -> c.size());
Grid<String> grid = new Grid<>(dataProvider);
grid.addColumn(s -> s);
grid.setSelectionMode(Grid.SelectionMode.MULTI); // MULTI or SINGLE does not matter
Button refresh = new Button("Refresh", e ->
{
    c.clear();
    c.add(String.valueOf(ThreadLocalRandom.current().nextInt(20)));
    c.add(String.valueOf(ThreadLocalRandom.current().nextInt(20)));
    c.add(String.valueOf(ThreadLocalRandom.current().nextInt(20)));
    dataProvider.refreshAll();
    System.out.println(grid.getSelectedItems().stream().collect(Collectors.joining(", ")));
});
Button deselect = new Button("Deselect all", e -> grid.deselectAll());
setContent(new VerticalLayout(grid, refresh, deselect));
```

1: Hit refresh
2: Select some items
3: GOTO 1

This becomes of course even more obvious if you replace the Strings with plain Objects.

```Java
Collection<Object> c = new ArrayList<>();
CallbackDataProvider<Object, ?> dataProvider = new CallbackDataProvider<>(q -> c.stream(), q -> c.size());
Grid<Object> grid = new Grid<>(dataProvider);
grid.addColumn(s -> s);
grid.setSelectionMode(Grid.SelectionMode.MULTI); // MULTI or SINGLE does not matter
Button refresh = new Button("Refresh", e ->
{
    c.clear();
    c.add(new Object());
    c.add(new Object());
    c.add(new Object());
    dataProvider.refreshAll();
    System.out.println(grid.getSelectedItems().stream().map(Object::toString).collect(Collectors.joining(", ")));
});
Button deselect = new Button("Deselect all", e -> grid.deselectAll());
setContent(new VerticalLayout(grid, refresh, deselect));
```

Expected behaviour: Items that are no longer in the DataProvider should not be in the selection
Actual behaviour: Items stay in the selection until deselectAll is called

**Comment by Legioth** [comment]
You're making assumptions that `dataProvider.refreshAll()` implies that everything has changed. What if the only change is that value of one cell has changed but everything else is the same. Should the user's selection be discarded then as well?

Another alternative would be that after every `refreshAll()` event, the component would go through the whole list of currently selected items and ask the data provider whether each item is still available. This would have terrible performance impact with a big selection, and would furthermore require that all `DataProvider` implementations would have a method for checking whether a previous item still exists (with a given filter).

Neither alternative is reasonable in the generic case. It will always be up to the application developer to choose what to do on a case-by-case basis. This is by design and not in any way a bug.

What could be done is to enhance the APIs to make it easier to support those kinds of cases without resorting to internal methods like `internalSetDataProvider`. The documentation could probably also be improved to clarify the situation.

**Comment by FSchliephacke** [comment]
Thanks for the clarification. It just took us quite a while to locate the problem while implementing a drag and drop functionality between multiple grids. Maybe the right way would anyway be to call deselectAll after a drop action.

**Comment by jonathanjt** [comment]
The more fundamental problem in my mind is that the grid is holding a copy outside of the data provider. This seems to break the MVP model.

**Comment by Legioth** [comment]
@jonathanjt To deal with that, we would basically have to require that all `DataProvider` implementations would also implement a method for fetching an instance based on an id. Furthermore, there would still also be the question about whether the component should forget about ids of items that are no longer available.

We were contemplating the pros and cons of each approach when designing the new APIs for Vaadin8. We ended up doing the thing that would  be simpler for the developer, i.e. only requiring callbacks for fetching items by an index range and for counting the number of items. It would in theory be possible to add a variant of `DataProvider` that would also be capable of fetching an item by its id and then transparently make `DataCommunicator` use that one if available instead of keeping copies of the items.
