### ISSUE TITLE
Internet Explorer: loading indicator permanently shown on tab change

### ISSUE THREAD

**Issue by nittka** [vaadin/framework#11408]
Between Vaadin 8.5.1 and 8.6.0 (problem remains in 8.6.3) the following problem was intoduced for Internet Exlorer (at least for 11).
If you have a TabSheet with two or more tabs and switch between tabs, the loading indicator is shown permanently - if it is not hidden by the content of the tab's component.
I could reproduce the problem with tabs containing just a label.

My current workaround is to disable the loading indicator completely.

`<my theme> .v-tabsheet-loading .v-tabsheet-deco{ display: none !important;}`

**Comment by anasmi** [comment]
Hi,

is there any change, you could you provide a reproducible example?

**Comment by nittka** [comment]
I could reproduce the problem using the following steps

* create a project as described in https://vaadin.com/docs/v8/framework/getting-started/getting-started-maven.html with Vaadin version 8.6.0
* replace the body of the init-Method in MyUI with
```
final VerticalLayout layout = new VerticalLayout();
        TabSheet tabs=new TabSheet();
        tabs.setStyleName(ValoTheme.TABSHEET_EQUAL_WIDTH_TABS);
        tabs.addTab(new Label("tab1"), "tab1");
        tabs.addTab(new Label("tab2"), "tab2");
        layout.addComponents(tabs);
        
        setContent(layout);
```
* run the war and open the page with Internet Explorer 11
* switch between the two tabs
* the loading indicator is shown permanently

**Comment by anasmi** [comment]
Hi,

I've been trying to reproduce the problem for some time, but LoadingIndicator for me is visible only during the Tab's initialization time and then it's removed, so it's not visible permanently. (when we are switching Tabs the content of it is attached/detached every time, so LoadingIndicator is indeed visible on every tab change, but it's an expectable behavior in a way) 

Also I have tested with a couple of previous versions and behavior seems to be exactly the same.

Have I missed anything? Or did you refer to the visibility of LoadingIndicator during the switch between the Tabs? (But in this case, it's also visible in Chrome for me and is an expected behavior)
![11048](https://user-images.githubusercontent.com/15248706/51101566-cca6a880-17e3-11e9-9426-8c8f3a221e76.gif)

**Comment by nittka** [comment]
The behaviour you describe is as expected. When time allows, I will go back and try to give more detailed information.

**Comment by nittka** [comment]
The initial bug report was based on building the application under Linux and then accessing it via a Windows maching with Internet Explorer 11. I now also built the application under Windows (using the above mentioned steps) and get the same behaviour.

* Windows 7 Professional
* Java 1.8.0_202
* Internet Explorer 11, Version 11.0.9600.19230, Updateversion 11.0.101
* Eclipse 2018-12 (built-in Maven)

I set up the project using Vaadin version 8.6.3 and after switching the tab, the loading indicator will remain. The same is true if I set the vaadin versions in the pom.xml to 8.6.0, repackage and run the application. If I set the version to 8.5.1, the loading indicator disappears.
