### ISSUE TITLE
TextField's ValueChangeEvent could provide a detail about cursor position

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1142]
**Originally by @mstahv**

___

Due to the client-server nature we cannot provide a properly working getCursorPosition() method for TextField (without server push). On value change events happening from client we could however provide this information. This would be useful for usability aspects in many cases.

___
 Imported from https://dev.vaadin.com/ issue #5218

**Comment by anasmi** [comment]
@KatriHaapalinna has created an add-on [SelectionRangeExtension](https://github.com/KatriHaapalinna/SelectionRangeExtension)which just greatly suits the needs for this case : )

**Comment by anasmi** [comment]
Hi again,

actually after we have investigated it further, it looks like there is a method, which suits your needs: [getCursorPosition](https://vaadin.com/api/com/vaadin/ui/AbstractTextField.html#getCursorPosition--)

I will close this issue due to this, but if you disagree with this decision, please, comment here and we will re-open it or create a new issue with description, what particularity you want to be implemented.

Thanks for your help and contributions! 
And have a nice day! :)
