### ISSUE TITLE
Compatibility package: rows inserted in grid are blank if selected

### ISSUE THREAD

**Issue by alessandroguarascio** [vaadin/framework#11477]
On Vaadin 8.7.0 (compatibility mode) when adding an item into an IndexedContainer bound to a Grid the corresponding row is displayed as blank in grid and it is not selectable. This problem occurs only if:
- the method {{container.addItemAt(...)}} is used,
- the index of the added item is greater than the currently selected row,
- the new row is programmatically selected immediately after insertion..

This used to work in Vaadin 7.x

Attached there is a sample UI [MyUI.zip](https://github.com/vaadin/framework/files/2919593/MyUI.zip) showing this problem

**Comment by anasmi** [comment]
Hi,

I've been trying to locate today when problem occurred first, but didn't manage to find the place. I checked that both 8.1 and 8.6 with compatibility packages have the issue already, so _most likely_ the problem was introduced from the beginning of compatibility package.

My best **guess** at this point, that when you are trying to select the row, which was just added, the client side is not aware, it exists. Since adding the row without selecting works jut fine. (So the container has item on server side, but grid is not aware of that on client)

The workaround for the issue is to delay the selecting of the row. This worked for me: 
```
Class variable: 
 final ScheduledThreadPoolExecutor executor = new ScheduledThreadPoolExecutor(
            1);
///
from Button Listener:
executor.schedule(() -> getUI().access(()->{
                selectOnlyLastItemIfRequested(checkBox);
                currInsertionIndex++;
            }), 100, TimeUnit.MILLISECONDS);
        });
```
That's not a proper solution, but a workaround. Someone will have to look closer into the problem, to investigate it further. I hope you can use the code above in meanwhile (It needs push through)

**Comment by alessandroguarascio** [comment]
Thank you for the workaround,

Unfortunately this requires push to be enabled (several legacy infrastructures do not allow websockets, neither long polling calls) and, in addition, is not always working with a delay of 100ms. 

With a longer delay it seems to be more reliable but longer lags  introduce some noticeable sluggishnesh in the UI compromising the general User Experience.
