### ISSUE TITLE
Performance problems switching a Grid via TabSheets

### ISSUE THREAD

**Issue by Dummdudeldumm** [vaadin/framework#11481]
- **Vaadin Framework version**
8.6.3, 8.7.0

- **Browser version**
Chrome 71.0.3, Chrome 72.0.8, Firefox 65.0.2

- **Description of the bug**
I have a Grid with 60 columns and 100 rows that is placed in a TabSheet. Initially the Grid is empty. With a button click I can add 100 rows and I can select another, nearly empty TabSheet

- **Minimal reproducible example**
See [TestApplication_Table.txt](https://github.com/vaadin/framework/files/2931363/TestApplication_Table.txt)

- **Expected behavior**
There should be no/nearly no difference in time consuming between adding the data via button click or switching to another Tab and switch back to the Grid Tab

- **Actual behavior**
Switching back to the Tab with the Grid takes a lot more time than clicking on the button. The time consuming also depends on the number of columns. If there are two columns, it works well. If there are 60 columns, switching back to the tab with the grid needs exorbitant more time than adding these 100 rows with the button click.

**Comment by TatuLund** [comment]
TabSheet removes the content from the DOM when switching Tabs in order to conserve Browser memory usage.

This will result Grid to re-calculate column widths when Tab is switched and Grid is re-attached. 

Calculation of the Column widths is O(n x m) operation, where n is number of columns and m number of rows in cache (since those are used as sample data to adjust column widths)

There are two alternatives you can do

1. Set defined widths to columns in the Grid, which will result much faster time for setting Grid up when re-attached

2. If you cannot do 1. you could do custom component to use instead of Grid. Basically have multiple Layouts with different z-index and create logic to switch them to top when buttons similar to Tabs are clicked. This way you can create your own TabSheet component, which has Grids in Tabs allways attached and no-recalculation is done when switching between layouts on top.

**Comment by Dummdudeldumm** [comment]
But I can't understand why it is much faster showing an empty grid and adding rows afterwards instead of "re-showing" a filled table. Why the second case can't do the things in the same way as the first case? Or is there a bug in the first case and the calculation of column width should be done much more often?
And more columns have more negative impact on performance than more rows.

**Comment by Dummdudeldumm** [comment]
I did some testing with explicit column widths. Sure, it is much faster, but still it is slower as creating the table and adding the rows. I extended my testcase in that way, that I added a create button that creates and add the table to the layout. So i can fetch the time for creating the table and for adding the rows.
The tesrtcase "switch back to tab with the grid" is round about 60-70 % slower than creating the grid and adding the rows. And I am not talking about microseconds. 60-70 % is nearly a second in my setup.
How can it be? I would expect nearly the same time consuming for both testcases.
I also asked before: Or is there a bug in the first case and the calculation of column width should be done much more often? Yes, there is a bug. If I define no column widths and add some rows, the columns widths do not change. If I switch the tab and switch back, all columns have other width. I expect the columns should have the same width as they had before switching the tab.

**Comment by TatuLund** [comment]
If you need to switch two Grids fast, the TabSheet is not likely to be the best option, since it does not hold the Grid in Browser memory, thus Grid is needed to be redrawn. Better approach would be to have the both Grids rendered in the beginning (the first render will be thus slower), and after that Grids are just swapped, which will be super fast. 

There is more than one way to achieve this, one of the techniques is presented in this demo app https://github.com/TatuLund/GridFlip
