### ISSUE TITLE
asMultiSelect().updateSelection modifies Sets passed into it

### ISSUE THREAD

**Issue by lennartfricke** [vaadin/framework#11520]
Vaadin Framework version : 8.7.1
Browser version: Chromium Version 73.0.3683.75
Web container name and version: jetty 9.4.14

Description of the bug:
on Grid asMultiSelect().updateSelection modifies Sets passed into it.
This is not expected or documented. I can create a patch, if it is decided whether to document or change

Minimal reproducible example
```java
final Grid<Integer> test = new Grid<>();
test.addColumn(i -> i);
final List<Integer> items = IntStream.range(0, 10).boxed().collect(toList());
test.setItems(items);
test.setSelectionMode(SelectionMode.MULTI);
test.asMultiSelect().updateSelection(
  unmodifiableSet(singleton(1)),
  unmodifiableSet(singleton(2))
);
```

**Comment by TatuLund** [comment]
I inspected the implementation in 

https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/components/grid/MultiSelectionModelImpl.java#L423

And it clearly looks clearly intentional that sets are processed first so that they do not overlap.

You are correct that this should be menioned as a note in JavaDoc
