### ISSUE TITLE
Vaadin TreeTable, Broken Multiselect-Mode on Windows 10

### ISSUE THREAD

**Issue by LazarTodorov** [vaadin/framework#11601]
The Selection in the Vaadin TreeTable seems to be not working correctly on some devices with Microsoft Windows 10.
Without holding the CTLR-Key, each click on a row selects and sets the focus on the row, and the previously selected and focused row is not deselected (defocused). By this way the row is added to the selection. This behavior is expected on touch devices, but not on a desktop devices or laptops without touch screen.  
The similar issue has been already reported https://vaadin.com/forum/thread/14078036

Any ideas how to overcome the issue?
Vaadin Version 7.7.10
Microsoft Windows 10
JxBrowser 6.19 (Chromium Engine), Google Chrome

**Comment by TatuLund** [comment]
This looks like same thing as reported here https://github.com/vaadin/framework/issues/6356

**Comment by LazarTodorov** [comment]
Here the list of devices who are affected from this issue:
Hewlett-Packard, HP Pro x2 612 G1
Lenovo Thinkpad x1 Yoga
Lenovo t440

Probably is caused by the same issue, since all of them have both, touchscreen and keyboard. The Selection-Mode is set in the VScrollTable:

private void setMultiSelectMode(int multiselectmode) {
        if (BrowserInfo.get().isTouchDevice()) {
            // Always use the simple mode for touch devices that do not have
            // shift/ctrl keys
            this.multiselectmode = MULTISELECT_MODE_SIMPLE;
        } else {
            this.multiselectmode = multiselectmode;
        }

    }

The devices listed above have the shift/ctrl keys and touchscreen, so they should be covered by this case.

**Comment by LazarTodorov** [comment]
Update: We are facing the same issue on Lenovo Thinkpad T540p, with touchpad switched off.

**Comment by TatuLund** [comment]
In the linked forum discussion two years ago I wrote

"My understanding so far has been, that the issue is that 2-in-1 hybrid devices and laptops with touch screen can be detected as touch devices also while keyboard attached, since they have touch input. This issue cannot be handled fully automatically. Hence some additional API is needed, so that application can define which mode to use and user can for example set preferences in application settings. This kind of improvement has been in our discussions. It would be nice to hear your oppinnion about it?"

And that is still correct. The problem is not really in the framework, but in the way how these devices and browsers report themselves. 

As I mentioned, almost the only way to address this from framework side is to introduce API that forces the Table to use normal multiselect mode regardless of what BrowserInfo.get().isTouchDevice() happens to return, since with some devices it cannot be trusted.

Having this API gives the option to application developer to use it, when he knows that the users do not have touch devices.

**Comment by LazarTodorov** [comment]
I agree with the fact that we cannot trust the result that BrowserInfo.get().isTouchDevice() returns. From my point of view the solution that you propose is fine, by this way the application developer has the possibility to control the behavior of the Table.  Such a API will help us solve this problem.
