### ISSUE TITLE
VaadinSession lock changed in multi thread

### ISSUE THREAD

**Issue by winionc** [vaadin/framework#11611]
In function  refreshLock(),
 lock = service.getSessionLock(session);
But in multithread, this function may be invoked in diffrent thread, so the lock variable is changed. And meantime, if some thread invok lock() and finally   unlock(),  and during lock() and unlock(), the lock variable changed, then in unlock(), there will be report an error as java.lang.IllegalMonitorStateException.
In fact, in refreshLock(), change as 
  if(lock==null)
        lock = service.getSessionLock(session);
will avoid this.

**Comment by Legioth** [comment]
Under what conditions does this occur?

The theory behind that logic is that `service.getSessionLock(session)` would still return the same value every time, even if called concurrently. There are also other invocations of `getSessionLock` in some places in `VaadinService` and `VaadinSession`, and all of them are based on the same assumption. Only changing the logic in `refreshLock()` would thus only cause similar problems to show up in other circumstances, since the root cause hasn't been addressed.

**Comment by winionc** [comment]
Well, I use it in this way, tomcat9, liferay framework, under fedora linux(fc29), openjdk1.8. I created a portlet with vaadin chart which use Groovy script to create the chart, and created two portlet instances in the same page. With diferrent config parameters, the two instances would display diffrent charts. Then sometimes the "java.lang.IllegalMonitorStateException" would be throwed. I traced the code, and the error was produced in `VaadinService.handleRequest()` . In `for` loop, I checked `getRequestHandlers()`, and found  it was `HeartbeatHandler`,  which was inherited from `SynchronizedRequestHandler`. In `SynchronizedRequestHandler.handleRequest()`, 
` session.lock();
        try {
            return synchronizedHandleRequest(session, request, response);
        } finally {
            session.unlock();
        }
`
Then I checked the `session.lock()` and `session.unlock()`. I printed the thread ids in lock() and unlock(), and found sometimes,  they were not the same. Then the exception was thrown.  I checked the `ReentrantLock`, and found 
`if (Thread.currentThread() != getExclusiveOwnerThread())
                throw new IllegalMonitorStateException();
`. That's all.

**Comment by TatuLund** [comment]
>  I use it in this way, tomcat9, liferay framework, under fedora linux(fc29), openjdk1.8. 

Is this happening in specifically in Liferay 7.2?

**Comment by winionc** [comment]
@TatuLund Not tested under in Liferay 7.2 yet.

**Comment by TatuLund** [comment]
@winionc , which Liferay version you used. I have some contacts who have seen seen this in 7.2, but not in older versions.

**Comment by SopaSeca** [comment]
We have a similar same issue: we have a portlet (Vaadin 8.9.0) deployed on 2 pages and when switching between these pages this exception is, most of the times, thrown. We are running on Liferay 7.2 with the latest patches.

**Comment by winionc** [comment]
@TatuLund I tested  in Liferay 7.1.0.

**Comment by TatuLund** [comment]
The root cause of this problem is that VaadinPortletService stores the portlet using PortletSession.APPLICATION_SCOPE

https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/server/VaadinPortletService.java#L349

However the lock is stored using the default PortletSession.PORTLET_SCOPE

The workaround is to override the methods in the linked position to use PortletSession.PORTLET_SCOPE instead.
