### ISSUE TITLE
Column width information lacking in ColumnResizeEvent

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1162]
**Originally by @magi42**

___
In a situation where you have two or more columns and then you resize the columns by dragging the handle between them, the ColumnResizeEvent is fired only for the column left of the resize handle. The event object provides the new width of the left column, but not of the column(s) on the right, which have also been resized.

I don't know what the purpose of the width information is if you don't have it for every affected column.

Or should the event be fired separately for also every affected column right of the resize handle?

**Comment by anasmi** [comment]
Hi!

We are going through the process of closing issues, which were fixed in the newer versions of the framework, have never been verified or won't be fixed. It looks like this issue is concerning Table, which is depreciated and it's suggested to switch to the Grid, if possible. Therefore, most likely this issue will never be fixed,

If you disagree with the decision of closing this particular issue, please re-open it or create a new one, with explanation and/or example to reproduce.

Thanks for your help and contributions!
