### ISSUE TITLE
Lambda expression in VaadinService cause the serialization fail in HA environment

### ISSUE THREAD

**Issue by yurili8** [vaadin/framework#11661]
Vaadin Version: 8.8.5.
Nothing to do with Brwoser version.

In HA environment, VaadinSession need to be replicated. Generally VaadinService should not.
But the lambda expression of the following will make VaadinService class to be serialized, which will fail the whole session replication.

    public Registration addSessionDestroyListener(
            SessionDestroyListener listener) {
        sessionDestroyListeners.add(listener);
        return () -> sessionDestroyListeners.remove(listener);
    }

the Registration instance returned will contain the Service "this" reference. will will be saved in the attribute in VaadinSession. so even though VaadinService has the "transient" keyword in VaadinSession, It will still be serialized when commit the session.

I have tried to replace lambda expression with anaymous class like following, it works:

    public Registration addSessionDestroyListener(
            SessionDestroyListener listener) {
        sessionDestroyListeners.add(listener);
        return new SessionDestroyListener(){
                  sessionDestroyListeners.remove(listener);
               };
    }

**Comment by Legioth** [comment]
Calling `remove()` on a `Registration` that has been migrated to a different node in the cluster would not do anything useful: it cannot remove the listener that may still be registered at the original node, and the listener instance it wants to remove has never been registered at the current node.

What you need to do instead is probably one of these options:
* Implement all state related to service listeners so that it doesn't need to move between nodes in the cluster. This would most likely mean that you have one "singleton" listener per node and then some way for the replicated state to find the local state on demand.
* Mark the field that references the registration as `transient` and then use a `HttpSessionActivationListener` that unregisters the listener from the previous node the the session is about to be serialized and then adds a listener in the new node once the session is deserialized there.
* Use a regular `ServletContextListener` annotated with `@WebListener` to do any necessary cleanup.

**Comment by yurili8** [comment]
> Calling `remove()` on a `Registration` that has been migrated to a different node in the cluster would not do anything useful: it cannot remove the listener that may still be registered at the original node, and the listener instance it wants to remove has never been registered at the current node.
> 
> What you need to do instead is probably one of these options:
> 
> * Implement all state related to service listeners so that it doesn't need to move between nodes in the cluster. This would most likely mean that you have one "singleton" listener per node and then some way for the replicated state to find the local state on demand.
> * Mark the field that references the registration as `transient` and then use a `HttpSessionActivationListener` that unregisters the listener from the previous node the the session is about to be serialized and then adds a listener in the new node once the session is deserialized there.
> * Use a regular `ServletContextListener` annotated with `@WebListener` to do any necessary cleanup.

Thanks for your suggestion.
But I am afraid I am not making me clear.
Actually the method "addSessionDestroyListener" is the one Vaadin provided in VaadinService.  Also I didn't call this method. All this is done by Vaadin Framework. I could not mark it as transient. But I agree with you that this should be transient. 

The issue is that we could not replicate the session in the current implementation. we will have serialization problem.

**Comment by Legioth** [comment]
> Also I didn't call this method. All this is done by Vaadin Framework.

I found one potential case where this is happening in `UIScopeImpl.UIStore` from the Spring add-on. Is this the case that you have in mind, or do I have to search more carefully?

**Comment by TatuLund** [comment]
Closed by https://github.com/vaadin/spring/pull/468
