### ISSUE TITLE
Slider components are not rendered correctly inside of Grid

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/framework#11877]
- Vaadin Framework version 8.9.4
- Browser independent (Chrome / Firefox / Edge / IE11)

- Description of the bug
Slider components that are not initialized when the grid loads are not rendering correctly.
![slider2](https://user-images.githubusercontent.com/11554739/72834891-7b3bbf80-3c68-11ea-9c5a-d132205d3fb9.gif)

- Minimal reproducible example
```
Grid<Integer> grid = new Grid<>();		
grid.setItems(IntStream.rangeClosed(0, 100).mapToObj(x->x));		
grid.addColumn(x->x%5);
grid.addComponentColumn(x->{Slider s = new Slider(0,4); s.setValue((double)(x%5)); return s;});
layout.addComponent(grid);
```

**Comment by TatuLund** [comment]
I studied this a bit and found out that the same workaround as described in ticket https://github.com/vaadin/framework/issues/11836 is also working with this one.

**Comment by Ansku** [comment]
I don't want to add the experimental fix into the framework itself because it's ugly and contains API changes and I don't want to be stuck with those API changes forever (I'm convinced there has to be a better way to do this, but I haven't found it yet). Instead, there is now an add-on that extends ComponentRenderer that you can use instead if you don't want to go the remove-and-replace route proposed earlier: https://vaadin.com/directory/component/refreshcomponentrenderer-add-on/

**Comment by mpittkin** [comment]
I've tried the RefreshComponentRenderer but am still having the issue where Slider is not rendered properly when I scroll past the initial Grid render...

Tried updating to latest Vaadin 8 (8.11.2), still not working.

Any other suggestions?

**Comment by Ansku** [comment]
Already mentioned in the comments of the RefreshComponentRenderer, but adding here as well to keep everyone on the map: I haven't found a way to reproduce this issue while using the add-on. If someone can provide me with a (preferably simple) test project where the problem is still present I can take a look, otherwise I can only say that it sounds like yet another timing issue.
