### ISSUE TITLE
RichTextArea link doesn't work properly in Firefox or IE

### ISSUE THREAD

**Issue by hajame** [vaadin/framework#11888]
In other browsers such as Chrome or IE, when the link button is clicked and link URL is given, the link appears in the RTA, its text being the URL. 

But when the same is done in Firefox 72.0.2 64-bit or IE 11.592, nothing happens. No link appears in the RTA. A link can only be entered by selecting text, and then clicking the link button.

Tested in [sampler](https://demo.vaadin.com/sampler/#ui/data-input/text-input/rich-text-area) and in production running Vaadin 8.

**Comment by tarekoraby** [comment]
After some debugging, the issue seems related to the fact that RTA relies (through GWT) on the Document.execCommand() web API, and the latter is behaving strangely with the "CreateLink" command when it comes to Firefox and IE (on chrome it seems to be working fine). Basically, the following command will run fine on chrome, but not on Firefox, IE, or Edge:

`document.getElementsByClassName("gwt-RichTextArea")[0].contentWindow.document.execCommand("CreateLink", false, "vaadin.com") `
