### ISSUE TITLE
Demo page is scrolled to much down in IE6/IE7

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1192]
**Originally by @Artur-**

___
Clicking on "Pure java" on http://demo.vaadin.com/ (IE6/IE7) scrolls the page down so far that the "Add-ons" link is the topmost item that is visible.

___
 Imported from https://dev.vaadin.com/ issue #5462

**Comment by anasmi** [comment]
Hi!

We are going through the process of closing issues, which were fixed in the newer versions of the framework, or have never been verified. The latest Vaadin Framework officially provides  and guarantees support for IE9+. Therefore, the possible solution for the issue would be to upgrade the browser version, if it's possible for you.

If you disagree with the decision of closing this particular issue, please re-open it or create a new one, with explanation and/or example to reproduce.

Thanks for your help and contributions!
