### ISSUE TITLE
TreeGrid SelectionListener out of sync with Dataprovider refresh

### ISSUE THREAD

**Issue by ShawnRG** [vaadin/framework#12017]
#### Info
-  Vaadin Framework version: 8.10.5
- Web container name and version: Tomcat 8.5.55

#### Issue description
Re-selecting cached item after a dataprovider refresh

> By dataprovider refresh I mean, clearing data from TreeData and adding data again

upon inspecting the the item returned by `TreeGrid.asSingleSelect().getValue()` I can verify that it's still the same cached item, when adding a small delay in the selection listener before printing the value, I **do** get the new item.

#### Steps to reproduce the issue
Here is the basic code setup I used to reproduce this issue

```java
        TreeData<Project> treeData = new TreeData<>();
        treeData.addItems(getProjects(), Project::getProjects);
        TreeDataProvider<Project> tdp = new TreeDataProvider<>(treeData);
        treeGrid.setDataProvider(tdp);
        layout.addComponents(treeGrid);
        setContent(layout);

        Button selectAndRefresh = new Button("Select and Refresh");
        selectAndRefresh.addClickListener(e -> {
            final Project cached = treeGrid.asSingleSelect().getValue();
            logger.info("Cached value " + System.identityHashCode(cached));
            tdp.getTreeData().clear();
            tdp.getTreeData().addItems(getProjects(), Project::getProjects);
            tdp.refreshAll();
            treeGrid.setDataProvider(tdp);

            treeGrid.asSingleSelect().select(cached);

        });

        treeGrid.addSelectionListener(selectionEvent -> {
             new Thread(() -> {
            // Adding the sleep here will give my my desired object
//                try {
//                    Thread.sleep(3000);
//                } catch (InterruptedException e) {
//                    e.printStackTrace();
//                }

                logger.info("Selection listener " + System.identityHashCode(treeGrid.asSingleSelect().getValue()));
            }).start();
        });
```

**Comment by Ansku** [comment]
The code example isn't reproducible as is, but I assume Project has equals implementation where the cached version matches the updated version. You are selecting an outdated item so the listener is triggered with an outdated item, and because the selection comes from the server-side it triggers the selection event right away without waiting for the refresh that happens in `beforeClientResponse`. There is no trivial way for the selection model to trigger that refresh itself before sending the value change event, but there is a pretty simple workaround of doing the selection with an already refreshed item instead. If you don't have an easier way to find that instance, you can find it e.g. like this:
```
            if (cached != null) {
                Project parent = tdp.getTreeData().getParent(cached);
                List<Project> children = tdp.getTreeData().getChildren(parent);
                int index = children.indexOf(cached);
                treeGrid.asSingleSelect().select(children.get(index));
            }
```

**Comment by ShawnRG** [comment]
Thanks @Ansku ! That indeed solved my issue.
