### ISSUE TITLE
Implement drag'n'drop support in VerticalLayout

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1202]
**Originally by @Artur-**

___
VerticalLayout should be a drag source and a drop target. By default it should be neither and the implementation should not affect the layout in any way when d'n'd is turned off.

When it is a drag source it should:
 - Allow dragging of the components inside it
   - Give a reference to the component in the Transferable

When it is a drop target it should:
 - The actual drop target is a cell
 - Separate drop areas for "on/before/after component"
 - Drop location should be indicated as the index of the cell  and an indicator telling if the drop took place on/before/after the target.
 - Drop areas visualized as highlight (on component) or a line between cells (before/after component).
 - The "on" drop area should be used for something like 80% of the space and only a small area to the left/right should be used for "between". 
 - When spacing is used the spacing area should also be a "between" drop target

**Comment by anasmi** [comment]
Based on the discussion it seems that the issue was resolved : )
Also, there is an example, in our docs, how it can be done: 
(Drop target section)[https://vaadin.com/docs/v8/framework/advanced/advanced-dragndrop.html]
Please, re-open it, if I am mistaken or something is still missing.

Thanks for your contributions and have a nice day! : )
