### ISSUE TITLE
The error notification widow does not move itself when browser is resized

### ISSUE THREAD

**Issue by SomMeri** [vaadin/framework#12036]
When I show the error and then resize the window, the position (left and top property) dont change.

Steps to reproduce:
1. Show error
1. Make window smaller

Expected result:
-  Error window moves to the left to be centered again.

Actual result:
- Error window stays where it is, in the thin column on the right side of the window.

**Comment by Ansku** [comment]
I'm afraid this is expected behaviour. Notifications are absolutely positioned, centering them is something that happens by calculating where the current centered position is and setting those coordinates. This could be worked around with a browser window resize listener that retriggers the calculations, but the use case isn't significant enough to warrant adding the extra weight to the notification handling on framework level.
