### ISSUE TITLE
Dots near checkbox in Grid in SelectionMode.MULTI in some browsers..

### ISSUE THREAD

**Issue by InnaSnytkina** [vaadin/framework#12048]
Hi,

I'm using Vaadin 8.11.0. I see checkbox with 2 dots in EDGE, Chrome, Opera browsers when for the Grid the SelectionMode is MULTI. In Mozilla looks good, without dots. 
Any advise how to fix or workaround that issue?
![image](https://user-images.githubusercontent.com/43446807/85756680-b65e8500-b717-11ea-8a89-0d9ddc77475d.png)
![image](https://user-images.githubusercontent.com/43446807/85757220-f3c31280-b717-11ea-9178-f7f6d52a163d.png)

_Originally posted by @InnaSnytkina in https://github.com/vaadin/vaadin-grid-flow/issues/552#issuecomment-649665786_

**Comment by TatuLund** [comment]
As there is no demo application attached, I checked how it looks with the Sampler, and there check box column shows up with Chrome correctly. I am using Windows 10.

https://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/multi-select

**Comment by InnaSnytkina** [comment]
![image](https://user-images.githubusercontent.com/43446807/86469753-ba575c00-bd42-11ea-9207-b5373b41f452.png)

**Comment by Ansku** [comment]
The screenshot is cropped so that I can't see, is your browser zoomed by any chance? That can cause rounding issues, which might trigger the `text-overflow:ellipsis;` in `v-grid-cell`. 

Unfortunately zoom-related rounding errors are an endless swamp, but as a workaround you could try using `text-overflow: clip;` in your theme -- although you might want to keep the ellipsis overflow for any columns that actually contain text that might overflow. I'm afraid there is no default style to target the selection column in particular, though, unless it's the only frozen column in your Grid, in which case you could target `frozen` instead. I can't off the top of my head remember any way to add a StyleGenerator to a selection column from the server-side, but you can of course add them to any other column and do another style override back to ellipsis that way.

**Comment by InnaSnytkina** [comment]
My browser is not zoomed, I see that the same issue is for the Microsoft EDGE, Opera, Google Chrome browsers. All browsers have zoom 100%.

After your response I've tried to change the zoom in all browsers listed above and see that 3 dots presenting really depends on zoom.
For example EDGE - for 80%, 100%, 150% zooms - 3 dots present
- for 90%, 110%, 125% -  no dots.

Thank you for the provided workaround.

**Comment by Ansku** [comment]
Hm, interesting. I don't recall ever running into that with default zoom myself while using Chrome, Firefox, or IE11/Edge with Win 7 and Win 10. I wonder if it could potentially be an issue with OS-level zoom as well, do you have that enabled? I know my new laptop came with default 250% zoom that wreaked so much havoc with all kinds of things like installation dialogs of some of my default software that I had to switch back to 100% and tweak the default resolution instead.

**Comment by DALDEI** [comment]
I see issues in with 100% Zoom frequently.  I have not totally nailed down why it shows sometimes and not others. I've tried every 'hack' in the forums (cliping, nbsp; etc)

**Comment by jbreitung** [comment]
I have the same issue with Google Chrome 84.0.4147.105 at none zoom level (100%) with Linux OpenSuse Leap 15.2. 

I tried to reproduce the issue on multiple platforms:

**Windows Server 2012 R2**
- Google Chrome 83: Not reproducable
- Mozilla Firefox 70: Not reproducable
- MS Internet Explorer 11 (sorry for that...): Not reproducable

**Linux OpenSuse Leap 15.2**
- Google Chrome 84: **Reproducable** (at any zoom-level)
- Mozilla Firefox 78: Not reproducable

**Ubuntu Desktop 18.04**
- Google Chrome 80: Not reproducable
- Mozilla Firefox 79: Not reproducable

**Comment by jbreitung** [comment]
Problem still exists with new Vaadin 8.11.2 version.
