### ISSUE TITLE
Out of order invocation of binder's setter callback and value changed handler

### ISSUE THREAD

**Issue by DSanborn** [vaadin/framework#12057]
'm using Vaadin 16 and am still seeing the behavior (reply from post since Vaadin 8). This should be identified as a bug; the value-changed-handler is invoked before the binder's setter. That is, the underlying model's value hasn't actually been modified when the value-changed-handler is invoked.

This becomes a serious problem when your binder's setter modifies other properties that are then referenced in the value-changed-handler. You would expect that the setter has already been invoked. See psuedo code below for reference:
```
MyObject myModel = new MyObject();
Select<MyProperty> slctProtocol = new Select<>();
slctProtocol.addValueChangeListener(
        event -> {
			System.out.println(myModel.otherProperty.toString()); // myModel.otherProperty will always be null because setProperty is called after this listener :(
        });
		
selectBinder
        .forField(slctProtocol)
        .bind(MyObject::getProperty, MyObject::setProperty);
    selectBinder.setBean(myModel);
	
	
public class MyObject {
	
	private MyProperty property;
	public MyOtherProperty otherProperty = null;

	public void setProperty(MyProperty property){
		this.property = property;
		this.otherProperty = new MyOtherProperty();
	}
}
```

https://vaadin.com/forum/thread/16619118/vaadin-8-order-of-change-listener-and-binding-calls

**Comment by TatuLund** [comment]
This is not a bug. Value change event from a field is lower level event, that happens with or without Binder. 

What you need here, there are two alternatives:

1. To define a custom event of your own, which you can fire in setProperty method and then you can listen to that event elsewhere in your application.

2. Binder has binding level `withValidationStatusHandler(..)`. But also that is not directly applicable here, since validation is executed before the setter. However, you could entertain the idea of setting the value of the other property in ValidationStatusHandler instead of setting it in the setter in case validation status is ok. This would be alternative to the creation of the custom event.

**Comment by DSanborn** [comment]
Why wouldn't you want to change the order in which the events are fired so that the API acts as one would expect? If I'm constantly writing workarounds to get the API to work as needed, I start questioning why I am even using this framework in the first place? There are a lot of simpler solutions out there.

**Comment by Ansku** [comment]
I can't speak for Vaadin 16 since I work pretty exclusively with Vaadin 8 and older, but at least for Vaadin 8 changing the order is not technically possible when you attach the ValueChangeListener to the field itself. It cannot know anything about the status of the bean, and the field's internal value has indeed already changed by the time Binder gets notified that anything is happening.

However, Binder itself also has a `addValueChangeListener` method, and that gets triggered after the setter. Note that it gets triggered whenever **any** bound field's value is changed, though, so if you have several fields bound to the same binder you need to compare against the event.getComponent() to limit your actions to specific field(s).
