### ISSUE TITLE
8.12.0 set a custom theme => page loading hangs with blinking progress indicator

### ISSUE THREAD

**Issue by dex-ds** [vaadin/framework#12151]
- Vaadin Framework version 8.12.0 (with compatibility)
- current Browser versions of Edge, Vivaldi, Firefox, Chrome, Safari
- setTheme programmatically in UI
- the custom themes are derived from ValoTheme
- empty cache and hard reload on browsers (mostly CTRL-F5), page loading hangs with blinking progress indicator
- button actions etc. are unresponsive
- after a normal reload (preservedOnRefresh needs to be true) the page is loading successfully

8.11.3 and previous version work properly

**Comment by TatuLund** [comment]
There has been a change in 8.12.0 what comes to programmatic theme change, as there was documented bug in earlier versions, see https://github.com/vaadin/framework/issues/11954 The symptoms documented are very similar to yours, with the difference that PreserveOnRefresh was not used in that scenario.

The fix is https://github.com/vaadin/framework/pull/12043/files

**Comment by Ansku** [comment]
I managed to reproduce something like this once on my first try with both Chrome and Firefox, but after normal reload (without @PreserveOnRefresh, all other conditions match except I'm running the test on current master, which contains a few more changes on top of 8.12.0) it started working again, and after that I haven't been able to get the problem to happen again on either browser, so I'm not entirely certain that was actually the same issue that you reported. If the problem is still present for you in 8.12.1 (released last week), could you attach a simple test UI that reproduces the error state, so that I can give it a closer look? I'm also interested in what kinds of errors or warnings you might have in your browser console when the application gets stuck.

**Comment by dex-ds** [comment]
Sorry for the delay, I'am very busy these days in projects.
The issue still exists in 8.12.1 However, it has become better because you can reproduce it less.
When the problem occurs, the following warning is displayed in the Browser Console:
> Wed Dec 09 20:10:42 GMT+100 2020 com.vaadin.client.communication.MessageHandler
> WARNING: Dropping the response of a request before a resync request.

**Comment by Ansku** [comment]
Thank you! I'm sadly still unable to reproduce the issue, so can't really dig in deeper for now, but that's a good starting point.

**Comment by TatuLund** [comment]
I managed to reproduce this locally. It requires the combination of `@PreserveOnRefresh` and `@Push(transport = Transport.WEBSOCKET_XHR)`. Also I tested the patch locally and it indeed seems to fix the issue.

**Comment by gnkuzmin** [comment]
It seems I have the same problem("page loading hangs with blinking progress") with Vaadin 8.12.1 
but without @PreserveOnRefresh (with @Push and without @Push).
But this works with Vaadin 8.11.1.
How often this happens apparently depends on the connection speed.
Unexpectedly, "browser cache dieable" makes it better.
With @Theme (without setTheme)
there is no problem.

**Comment by dex-ds** [comment]
I confirm the issue is fixed.
8.12.3 tested with all standard browsers on 10 deticated custom environments.

**Comment by Ansku** [comment]
Great to hear, thank you for testing!
