### ISSUE TITLE
Get ConcurrentModificationException in background tasks

### ISSUE THREAD

**Issue by MrConturIX** [vaadin/framework#12180]
We are using TabSheet, inside which we display lists of VerticalLayout elements. Inside the list items, we have buttons that appear asynchronously, depending on the relationship with the object. At the moment of opening a list with a large number of elements or when a large number of users are working at the same time, we get ConcurrentModificationException.

We have a BackgroundTaskManager that implements a queue of threads to perform background tasks. Executed code inside thread:

CompletableFuture<E> backendWorker = CompletableFuture.supplyAsync(() -> perform(params));
        backendWorker.thenRunAsync(() -> {
            try {
                E result = backendWorker.get();
                onFinish(result);
            } catch (InterruptedException | ExecutionException e) {
                e.printStackTrace();
            }
        });
		
In the perform() function, we select relations from the database. The result is passed to the onFinish() function, in which we draw the result for each item in the list:

VaadinUI.getInstance().access(() ->
                                Utils.doOnAttach(CheckBoxTable.this, () ->
                                        rowElementComponentHashMap.forEach((components1, dataHandler) ->
                                            components1.getRowElement().drawAsyncComponents(dataHandler)
                                        )));
										
Function doOnAttach:

public static void doOnAttach(ClientConnector connector, Runnable runnable) {
        if (connector.isAttached()) {
            runnable.run();
        } else {
            AtomicReference<Registration> registrationAtomicReference = new AtomicReference<>();
            ClientConnector.AttachListener attachListener = event -> {
                runnable.run();
                registrationAtomicReference.get().remove();
            };
            registrationAtomicReference.set(connector.addAttachListener(attachListener));
        }
}

We use Vaadin 8.6.4 with WildFly 11

**Comment by TatuLund** [comment]
ConcurrentModificationException is usually tricky to debug, since the exception is thrown typically at ui.access(..) call, as it fails to get lock as some other part of your code is currently modifying UI without locking it. Vaadin contains some assertions, which may help you in debugging this, if you run your application using -ea jvm parameter to enable them.

I also pointed out that your code is peculiar looking. I have composed one example how to do UI update from a background thread sort of "best practice" way, see the code 

https://github.com/TatuLund/cdi-demo/blob/master/src/main/java/org/vaadin/cdidemo/views/admin/AdminPresenter.java

and

https://github.com/TatuLund/cdi-demo/blob/master/src/main/java/org/vaadin/cdidemo/views/admin/AdminViewImpl.java

> We use Vaadin 8.6.4 with WildFly 11

I would like to point out that 8.6.4 is outdated version and you should consider upgrading to the latest, however I do not suspect a bug in framework in this case.

**Comment by MrConturIX** [comment]
We replaced `backendWorker.thenRunAsync()` on `backendWorker.thenAccept()` as in yours example and now we get same error every time when opening the list, regardless of the number of elements.

With `-ea` JVM parameter we get error:

```
components.tabs.TabPanel(25) claims that com.vaadin.ui.GridLayout(1) is its parent, but the parent does not acknowledge the parenthood.
java.lang.AssertionError: The connector hierarchy is corrupted. Check for missing calls to super.setParent(), super.attach() and super.detach() and that all custom component containers call child.setParent(this) when a child is added and child.setParent(null) when the child is no longer used. See previous log messages for details.
```

Maybe you can help with this parameter too and we will find out where the error occurs. We have `GridLayout `at the `UI `class and in one of the cell we have `TabPanel ` with content witch extends `TabSheet`
