### ISSUE TITLE
Can a DateTimeField with resolution DateResolution.YEAR hold a value with precision higher than YEAR?

### ISSUE THREAD

**Issue by alexandru-prigoreanu** [vaadin/framework#12182]
- Vaadin Framework version : 8.12.1
- Browser version : chrome 87.0.4280.141
in Vaadin 8.8.6 the DateTimeField with resolution DateResolution.YEAR was able to hold a value with precision higher than YEAR.
in Vaadin 8.12.1 this behaviour seems lost, probably it was lost in Vaadin 8.9.0.

I have a DateTimeField dateFrom with resolution YEAR and value dd/mm/yyyy 01/01/2021.
I have a comboBox with trimesters (1,2,3,4).
Choosing a trimester updates the value of dateFrom to one of the following 01/01/2021, 01/04/2021, 01/07/2021, 1/10/2021
the value of dateFrom first gets updated to the expected value and later it gets updated without user interaction to the original value of 01/01/2021.

I attached the debugging on valueChange for the later valueChange (the one that resets the value to 01/01/2021).
the valueChange is reached without user interaction with event.isUserOriginated = true
is this the expected behaviour?
![vaadinDebugAbstractDateField](https://user-images.githubusercontent.com/74921454/104466466-457f9d00-5583-11eb-9098-6c874b3c85a3.png)

thank you!

**Comment by Ansku** [comment]
The mentioned change was introduced as a fix for the event order issue reported in #11316. It doesn't change how the dates themselves are handled (choosing a date with DateResolution.YEAR always leads to a midnight of 1st of January date, choosing a date with DateResolution.Month always leads to a midnight of 1st of that month date, and so forth), but the difference is that after the change the date sync is done more often (triggered by every state change, delivered with a delay whenever the next RPC call happens), not only when a user changes the value.

As for whether this more eager syncing is intentional or not, It's been a while, so I can't actually remember what we discussed about the matter at the time or whether we even came to think that somebody might be relying on the underlying date having different resolution than the displayed one. Personally I'd like that every DateTimeField that shows 2021 would also hold an equal value with each other, whether the value was set programmatically or through user interaction.

Consequently, when I test this, the part I'm not entirely happy about is how the delay works, and I'm quite certain I missed some of the implications there back when I reviewed the change. Right now it's possible to change the resolution and then request the value programmatically and still get the old value that wasn't updated to match the resolution. It only updates to what I think it should be when something else triggers an RPC call, e.g. if I click an unrelated button.

Anyway, I'll discuss this with the team, but from my side I'd say that it would be better to save the more precise date somewhere else than within the date field. I can see how it could be handy for some use cases, but it feels a bit messy and inconsistent.

**Comment by alexandru-prigoreanu** [comment]
@Ansku thank you for looking into this. If there is no other solution feel free to close this and I shall save the trimester start date in some other way. Thank you

**Comment by Ansku** [comment]
We talked about this, and decided to keep the version where it's not possible to keep a more precise value than what is displayed. Thanks for bringing it up, though, it was good to think it through and make sure that's how we actually want it!
