### ISSUE TITLE
Grid - does handleWidgetEvents work well with ComponentColumns that contain a CheckBox?

### ISSUE THREAD

**Issue by alexandru-prigoreanu** [vaadin/framework#12297]
- Vaadin Framework version: 8.12.3
- Browser version: Chrome Version 90.0.4430.93 (Official Build) (x86_64)
- Description of the bug
Apparently, on clickEvent, CheckBoxes in ComponentColumns (column with ComponentRenderer) of a column with handleWidgetEvents set to true are not able to change state from checked to unchecked and viceversa.
When I click on a checkBox for a brief second i am able to see it change state but then, very fast it goes back to the previous state.
- Expected behavior
Click on checkBox in a column with a ComponentRenderer of a column with handleWidgetEvents set to true, changes it state to checked/unchecked
- Actual behavior
Click on checkBox in a column with a ComponentRenderer of a column with handleWidgetEvents set to true does not change its state to checked/unchecked.

Hello! Thank you for your work. Can you confirm this? Should I not use handleWidgetEvents on ComponentRenderer columns that contain CheckBoxes?

**Comment by Ansku** [comment]
Sorry for the confusion with the labels, I need to refresh my mind on what the handleWidgetEvents really does under the hood. I can reproduce the issue, but none of our test classes use that with components that you'd actually want to interact with (rather than e.g. Label), so I think it's not really recommended for those. It might still be a bug, but requires a deeper look before I can say for certain.

**Comment by Ansku** [comment]
Right, my test was actually broken in other ways, no wonder I had trouble with the feature 😅  A common problem with ComponentColumn is that the component provider keeps creating new components rather than reusing the old one. It's not noticeable if the value can never change, but it's very relevant with fields like CheckBox. You can work around that by keeping track of the component yourself in some `Map<MyPojo, CheckBox> checkBoxes`, and creating the column e.g. like this:

```
        Grid<MyPojo> grid = new Grid<>();
        grid.addComponentColumn(myPojo -> {
            if (checkBoxes.containsKey(myPojo)) {
                System.out.println(
                        "Reusing old CheckBox for: " + myPojo.getStringValue());
                return checkBoxes.get(myPojo);
            }

            CheckBox checkBox = new CheckBox(myPojo.getStringValue());
            checkBox.setValue(myPojo.isBooleanValue());
            checkBox.setWidth("100%");
            checkBox.addValueChangeListener(event -> {
                System.out.println("Value change! " + checkBox.getCaption()
                        + " " + event.getValue());
                myPojo.setBooleanValue(event.getValue());
            });
            checkBoxes.put(myPojo, checkBox);
            return checkBox;
        }).setId("checkBox").setCaption("CheckBox").setHandleWidgetEvents(true);
```

Note that this is just a quick-and-dirty example, you might want to polish it further than just removing the logging, but if you test it out, you'll notice that the reuse message happens with each click and selection change, which is why the selection disappears if you don't have explicit reuse in there.

**Comment by alexandru-prigoreanu** [comment]
thank you @Ansku ! should we close this?

**Comment by Ansku** [comment]
Closing. Adding a final reminder to pay attention to potential memory leaks with the manual storing of the component (if rows are removed from the Grid, they should be cleaned out the map as well. And if you have huge amounts of rows, that collection can easily grow massive after scrolling, unless you prune out components that are outside of the cached rows.
