### ISSUE TITLE
setting theme in URL allows file system navigation on server

### ISSUE THREAD

**Issue by nittka** [vaadin/framework#12292]
We have a penetration test finding for a Vaadin-8 application (compatibility layer). If a theme set via query parameters contains path navigation, a corresponding style sheet is actually resolved (`appURL?theme=../../../../pentest%23`)

I was not able to prevent the UIConnector from trying to resolve the corresponding style sheet (...VAADIN/themes/../../../../pentest#/styles.css - checked in the browser's console output). Overriding the UI.setTheme-Method or UIProvider.getTheme-Method did not suffice. The only fix I found so far was overiding VaadinServlet.service in order to check for the presence of a theme parameter in the request and using a wrapper request eliminating illegal theme definitions.

Is there another central hook for doing a sanity check on the theme parameter?

environment: Vaadin 8.11.1, local tests with Jetty and firefox, pen-test with Wildfly 18 (browser unknown but probably irrelevant).

**Comment by Legioth** [comment]
From my understanding, what you've discovered is that if `?theme=../../../../pentest%23` is included in the URL when the page is loaded, then that will make the browser make a request to `VAADIN/themes/../../../../pentest#/styles.css`. What is not clear is whether a request like that can ever disclose any sensitive information, regardless of whether that request is sent directly as an URL or indirectly through a malicious `?theme` parameter when bootstrapping.

The regular logic in Vaadin that serves files for `/VAADIN` is supposed to verify that the location it loads the file from is indeed inside the actual `/VAADIN` directory and reject anything that goes outside. A smilar check is also performed for `getThemeResourceAsStream` that directly reads theme resource values based on `UI.getTheme()` on the server in some special cases. 

Can you confirm whether you're only observing that an invalid request is being made, or whether there's also the case that this request leads to disclosing any data?

There should not be any need to filter the `theme` parameter value since it's not supposed to be used in any dangerous context by the framework itself. If there's logic in the application that uses the value of `UI.getTheme()` in a potentially dangerous way, then it's possible to override `UI.setTheme` to sanitize the value as necessary.

**Comment by nittka** [comment]
Thank you for your reply. I only have a short summary of the external penetration test. The finding seems to be that the stylesheet link in the generated html header actually contains the "navigation" `<link rel="stylesheet" type="text/css" href="./VAADIN/themes/../../../../pentest#/styles.css?v=8.11.1">` as well as another one with the full URL (including host, context etc).
So far, I was not able to find a configuration that actually uses the style sheet, but due to the above navigation, the style sheet would probably be resolved relative to the wildfly's welcome content directory.
Placing the (copy of the actual) style sheet there (in the corresponding pentest-subdirectory), an infinite loop of requests seems to be triggered (browser shows no content - usually after some seconds the page appears with broken rendering due to the missing styles). The wildfly log fills up with warnings: `[com.vaadin.server.communication.ServerRpcHandler] (default task-56) Unexpected message id from the client. Expected: 81, got: 85` where the last number increments and the process does not end.

I think I can understand the concern of the finding (potential css injection) even if I was not able to create an actual attack. However, the DOS-like behaviour of causing constant communication due to one request is not nice either.

When I override UI.setTheme to set a default theme in case the given one contains "..", the stylesheet link with the absolute URL is fixed, however the one starting with "./VAADIN/themes..." still contains the "attacking theme", so for now, I will wrap the request just to be on the safe side.

My proposal would still be to sanitize the theme, making sure that the resulting link does not leave /VAADIN/themes.

**Comment by TatuLund** [comment]
> environment: Vaadin 8.11.1, l

and 

> The wildfly log fills up with warnings: [com.vaadin.server.communication.ServerRpcHandler] (default task-56) Unexpected message id from the client. Expected: 81, got: 85

Indicate that you should upgrade to the latest Vaadin version. 

It looks like https://github.com/vaadin/framework/issues/11954, which has been fixed in 8.12.2, 8.13.0 is the latest at the moment.

This is finding is unrelated to your first concern.

**Comment by nittka** [comment]
I have a slightly more detailed information on the test. If via the above parameter, the attacker is able to reference a page with mimetype html, an error occurs and the application adds style sheet headers over and over, potentially freezing the browser.

(regarding the log: after updating to 8.13.1, the log now fills up with deprecation warnings from the EventRouter, because an add-on without an update uses deprecated API...)

I have not reproduced the actual attack. As I said, we simply filter problematic requests.
