### ISSUE TITLE
Grid details content of third item will disappear if the first item is removed

### ISSUE THREAD

**Issue by Flaurite** [vaadin/framework#12328]
### Environment
- Vaadin Framework version: 8.13.1
- Browser version: Google Chrome 91.0.4472.114
### Description of the bug
Grid does not correctly handle removing **first** item with opened row details.
<details>
<summary>Minimal reproducible example</summary>

```
@Override
protected void init(VaadinRequest vaadinRequest) {
    List<String> data = new ArrayList<>(Arrays.asList("row1", "row2", "row3"));
    Grid<String> grid = createGrid();
    
    ListDataProvider<String> dataProvider = new ListDataProvider<>(data);
    grid.setDataProvider(dataProvider);
    data.forEach(item -> grid.setDetailsVisible(item, true));
    
    Button removeBtn = new Button("Remove item");
    removeBtn.addClickListener(event -> {
        data.remove(grid.getSelectedItems().iterator().next());
        dataProvider.refreshAll();
    });
    VerticalLayout layout = new VerticalLayout();
    layout.addComponent(removeBtn);
    layout.addComponent(grid);
    setContent(layout);
}
private Grid<String> createGrid() {
    Grid<String> grid = new Grid<>();
    grid.setHeight("300px");
    grid.addColumn(item -> item).setCaption("column").setId("column");
    grid.setDetailsGenerator(item -> {
        Button closeBtn = new Button("Close");
        closeBtn.addClickListener(clickEvent -> grid.setDetailsVisible(item, false));
        return new HorizontalLayout(new Label("Item details: " + item), closeBtn);
    });
    grid.addItemClickListener(itemClick -> grid.setDetailsVisible(itemClick.getItem(), true));
    return grid;
}
```

</details>

1. Launch the app. 
2. All rows with opened details. Select and remove first item.

![image](https://user-images.githubusercontent.com/22093943/123224326-c6ec3b80-d4e2-11eb-80ea-0652bbccbdbb.png)

There is an exception in dev tools of the browser:
```
SEVERE: Error performing server to client RPC calls
java.lang.IllegalStateException: Cannot set a new parent without first clearing the old parent
```

**Expected behavior**
First item is removed and all details are opened

**Actual behavior**
Details content of the last item is disappeared

**Comment by Ansku** [comment]
Updated the title because if you add one more row, it's the initial third row's details contents that disappear. Likewise if you remove second row when there is four rows, the initial fourth row's details disappear. The problem appears in the details content refresh, which is done from top to bottom. When the first non-removed row tries to attach the new details contents, those contents are still attached to the following row's details. The exception kills the refreshing process, so if there are more than three rows, the details row that used to contain the moved contents is left empty, and every row below that is left with the non-refreshed contents. I'll see what I can do about this.
