### ISSUE TITLE
Scrolling possible in a disabled Table

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1270]
**Originally by @Artur-**

___
It should not be possible to interact with a disabled component. A disabled Table can be scrolled both down and right. 

Scrolling down is possible at least in Firefox 3.6.10 and results in the Table being scrolled back directly afterwards.

Scrolling right if possible at least in Firefox 3.6.10 and Chrome6. Scrolling right only affects the contents, leaving the headers in place (out of sync with the contents).

___
 Imported from https://dev.vaadin.com/ issue #5798

**Comment by anasmi** [comment]
Hi,
it looks like, this issue still exists and the scroll jumps back after attempting to scroll table in  the disabled mode. 
Unfortunately, the table component was depreciated prior to the Grid and most likely the issue will not be solved. 
We are currently going through the process of closing issues, which haven't  been active for a while, were fixed or won't be fixed , in order to get more attention to the ones, which are still outstanding.
I will close this issue, but If you disagree with this decision, please, re-open it or create a new one.
Thanks for your help and contribution!
