### ISSUE TITLE
Table.RowGenerator should support creation of components (patch provided)

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2360]
**Originally by _ReuDa_**

___
There is a possibility to replace whole rows in table with custom content. The Table.RowGenerator actually supports text (spanned or not), you can even use HTML. But if I look into the table-implementation, I think the RowGenerator was designed to support also components. For example there is an if-clause, which checks the value of an generated row to be a Component:
```
if (... && generatedRow.getValue() instanceof Component) {
```
I try to use the api like this:
```
	table.setRowGenerator(new RowGenerator() {
	    public GeneratedRow generateRow(Table table, Object itemId) {
		GeneratedRow row = new GeneratedRow() {
		    protected Object getValue() {
			VerticalLayout layout = new VerticalLayout();
			// layout.addComponent(...);
			return layout;
		    }
		};
		row.setSpanColumns(true);
		return row;
	    }
	});
```

Doing this, I get a ClassCastException here:
```
VScrollTable.VScrollTableBody.VScrollTableGeneratedRow.addCellsFromUIDL(...) {
  ...
  final Object cell = cells.next();
  if (cell instanceof String) {
    ... 
  } else {
    addSpannedCell(uidl, (Widget) cell, aligns[0], "", false, colCount);
  }
```
The problem is the cast from cell to Widget. There is an easy fix for that. We can use the same implementation like in VScrollTableRow.addCellsFromUIDL(...). See attached patch-file.

___
 Imported from https://dev.vaadin.com/ issue #8775

**Comment by svraj** [comment]
I think this should be supported as this may be a very common case in many of the projects. In our project, we are struggling a lot because we are unable to render a component for certain rows (similar to DetailsGenerator in Grid)

**Comment by Ansku** [comment]
Components within row generator is not an officially supported feature. They can cause quite a few issues, which can lead to the components disappearing without warning if they aren't properly cached so that they won't get garbage cleaned, and to all kinds of height handling problems (particularly with scrolling) if care isn't taken to keep the row heights the same between regular and generated rows (Table does not support variable row height and there is no special handling for generated rows that would be along the lines of Grid's details row handling). That said, I merged the proposed pull request to make it easier to use components anyway if the downsides don't outweigh the benefits for some individual projects, but this is not something we are planning to develop into a fully fledged feature. Use at your own risk.
