### ISSUE TITLE
BeanFieldGroup does not recognize @NotNull annotations

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3518]
**Originally by _jflatt_**

___
Moving from the Bean Validator addon in 6 to BeanFieldGroup to 7 it seems that @NotNull fields are not supported.  The form fields using @NotNull do not show up as required nor are the validated as being required.  If I manually add setRequired(true) to the fields then that interferes with the other validators set by BeanFieldGroup.  It seems that a field cannot be both required and validated by other validators.

___
 Imported from https://dev.vaadin.com/ issue #11014

**Comment by AlphaJuliettOmega** [comment]
... 
has there been any changes related to this issue since this issue was raised?

**Comment by pleku** [comment]
Hello. We have actually [just resolved](https://github.com/vaadin/framework/commit/1309be6c20316e50ccc959f7f17f64b7a4585c07) this issue in FW version 8.0, which is just around the corner.

Because the whole data binding concept (`FieldGroup`) has been reinvented in 8.0 (with `Binder`), we are not able to backport this directly to the 7 series.

To be honest, we currently don't have any plans for doing further enhancements for BeanFieldGroup for version 7.
