### ISSUE TITLE
Allow positioning the ColorPicker popup

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3666]
**Originally by @magi42**

___
The popup opens by default at the top-left corner of the screen. More typically, you might want to have it open at the center of the screen or next to the button/area used to open it. It has setPosition(), but the position needs to be calculated at the time when the button is created, and the browser window could be resized after that. It might also be useful to position the popup anchored to the launch button/area. It might also be necessary to make the popup modal.

So, minimally there should be a `center()` or `centerPopup()` method, but also a bit similar API as in the Overlays add-on could be useful:

 - `setPopupAnchor(Alignment)` - sets the position of the popup relative to the button, for example, MIDDLE_RIGHT opens it on the right side of the button
 - `setPopupAnchorOffsetX/Y(int x/y)` - offset from the position defined with `setPopupPosition()`, for the purpose of giving a bit more space between the button and the popup.
 - `centerPopup()` - centers the popup in the browser window and keeps it at the center if the browser window is resized. Or `setPopupAlignment/Position(Alignment/Position)`, although I'm not sure if many more positions than the center are very useful.
 - `setModal(Boolean)`

Well, using either the Alignment or Position constants...not sure which is more proper term here.

As mentioned in [this forum thread](https://vaadin.com/forum/-/message_boards/view_message/2774449).

___
 Imported from https://dev.vaadin.com/ issue #11323

**Comment by anasmi** [comment]
Hi!

We are going through the process of closing issues, which were fixed in the newer versions of the framework, or have never been verified. There is a **setPosition(int x, int y)** method available for ColorPicker, which sets the position of ColorPicker from top left corner.

Also, we are now in process of reviewing [Modality](https://github.com/vaadin/framework/pull/10815) feature for the ColorPicker.

I will close this issue for those reasons. 
Through, if you disagree with the decision of closing this particular issue, please comment here and we will  re-open it or create a new one, with explanation and/or example to reproduce.

Thanks for your help and contributions!

Have a nice day! :)
