### ISSUE TITLE
Unable to use a SQLContainer with ListSelect and TwinColSelect

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4098]
**Originally by @hesara**

___
When using SQLContainer with ListSelect or TwinColSelect, the following exception is triggered:
```
java.lang.IllegalStateException: A connector should not be marked as dirty while a response is being written.
```

See the corresponding ComboBox ticket #10458 for more information. This ticket can further be split in two if separate issues affect these selection components.

___
 Imported from https://dev.vaadin.com/ issue #12085

**Comment by Pereitor** [comment]
Yeah, suffering from this bug, too. In my case, when trying to set an SQLContainer as a DataSource for a ListSelect. It's very confusing and didn't notice the underlying cause (an "IllegalStateException") because my app was finishing with a sudden "Internal Error - please notify the administrator" error.

Anyway, I know this won't be fixed as SQLContainer is deprecated, but having this issue laying around for at least 4 years is a... hmm... how to say it?

**Comment by Pereitor** [comment]
By the way, in case anyone still interested, there's a working (I tested it) "workaround": 

> "manually calling container.getItemIds() should get rid of the error since the container caches the results for 10 seconds"

It was suggested by Thomas Mattsson in [this forum thread](https://vaadin.com/forum/#!/thread/8032847)
