### ISSUE TITLE
Heartbeat should respond 404, not 410, when session expired

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4417]
**Originally by @jdahlstrom**

___
`HeartbeatHandler` currently sends 410 Gone if the session is expired. This is arguably semantically wrong, as a user agent is within its rights to assume that the resource uniquely identified by the URI (and only the URI - cookies don't matter) will never be available again and any future requests to the same URI should not be made. A 404 Not Found should be returned instead.

___
 Imported from https://dev.vaadin.com/ issue #12526

**Comment by Emmenemoi** [comment]
This cached headers following a 410 on /APP/PUBLISHED/* is a real problem for loading js: there's no error (session exists) but scripts are not loaded because of 410 being cached.

This still exists in 8.5.2.

**Comment by mvysny** [comment]
I agree with changing that to 403, maybe with an error message of "no session" or such.

**Comment by edler-san** [comment]
403 would be semantically wrong as well since no authorisation takes place. 404 is the right code. As per RFC: ` The 404 (Not Found) status code indicates that the origin server did
   not find a _current_ representation for the target resource` (emphasis mine) - which is exactly what happens.

I think more relevant would be to add `response.setHeader("Cache-Control", "no-cache");`  to handleSessionExpired in 
https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/server/communication/HeartbeatHandler.java

**Comment by ffdybuster** [comment]
This actually caused random session expired messages in our Vaadin 7 apps with Safari (macOS). One way to reproduce: start a Vaadin 7 app, wait until the session expires, then reload the page, log in, and wait for the next heartbeat. It will be the cached 410, resulting in a session expiry shown in the client, while the backend still has the session.

(Also, as commented in #11556, I think the current fix for this isn't perfect since it removes the session expiry message when it would correctly appear as well.)
