### ISSUE TITLE
Changing textfield value in a popup window causes scroll to jump to top

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4690]
**Originally by _kerb_**

___
Steps to reproduce (in attached project:

1. Run project
2. Scroll to the field, let's say 25
3. Start changing textfield value
4. After some seconds scroll jump will happen

___
 Imported from https://dev.vaadin.com/ issue #12972

**Comment by TatuLund** [comment]
I migrated the test app to Vaadin 8 and checked that the issue is reproducible with latest Vaadin 8.7.2 version using Chrome 73.

**Comment by TatuLund** [comment]
In this case the problem is not a framework issue.

This code in the test app is flawed

```
            c.addTextChangeListener(new FieldEvents.TextChangeListener() {
                @Override
                public void textChange(FieldEvents.TextChangeEvent event) {
                    c.setValue(c.getValue() + "_1");
                }
            });
```
The programmatic value change c.setValue(..) will also trigger text change event (or value change event in Vaadin 8) and that will quickly produce stack overflow, it is the resulted exception that as side effect causes the view to scroll to top. When corrected this does not happen, e.g. the following works

```
        for (int i = 0; i < 30; i++) {
            TextField c = new TextField("Field " + i);
            final Integer field = i;
            c.setWidth("400px");
            c.addValueChangeListener(event -> {
            	System.out.println("Field: "+field+" Value: "+c.getValue());
            });
            content.addComponent(c);
        }

```
