### ISSUE TITLE
Setting styles for individual columns in a GridLayout

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#472]
**Originally by @vaadin-kim**

___
It would be nice if one could specify a style for a specific column in a GridLayout. This feature could work as a combination of setComponentAlignment and setStyleName - setComponentStyleName(Component childComponent, String style)

___
 Imported from https://dev.vaadin.com/ issue #1735

**Comment by anasmi** [comment]
Hi,

as it noted here , the recommended way of styling components inside the GridLayout is to style the component itself:

> For styling the individual grid cells, you should style the components inserted in the cells. Normally, if you want to have, for example, a different color for a certain cell, just make set the component inside it setSizeFull(), and add a style name for it. Sometimes, you may need to wrap a component inside a layout component just for styling the cell.
[CSS Style Rules GridLayout](https://vaadin.com/docs/v8/framework/layout/layout-gridlayout.html)

As this issue is quite old and there is a proposed solution for it, I will close this issue, but , please, create a new one if the feature is still important for you to be implemented !

Thanks :)
