### ISSUE TITLE
Exceptions during initial view change not handled properly

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4995]
**Originally by @jdahlstrom**

___
Exceptions during `UI.doInit()` are not handled by the `ErrorHandler` mechanism but are simply propagated to the servlet. This is especially a problem if the initial `Navigator.navigateTo` call throws. It's not completely clear how this should be handled - any custom UI error handler might work in an unexpected way if the UI is not completely initialized yet. On the other hand, at least after `UI.init` is run it should be safe to use the normal mechanism, and this would resolve the mentioned navigator issue.

**Comment by sergetania** [comment]
We have also run into this problem. 

Here are two scenarios to further illustrate the issue:

1. The Vaadin session exists for the user. The user may be on the Home page, for example. Next, the user attempts to go to a specific URL in the application and it results in an exception that is caught by a registered error handler that navigates to the error page with the error details. Everyting works fine, the user sees a friendly error message with explanation what happened/what to do next.

2. The user is not on any of the application pages therefore there is no Vaadin session. The user enters a URL that takes him to one of the application pages. In the process, a session is initialized and an error handler gets registered. Then in the further process of the request, an exception is thrown, same as in the scenario #1. It is caught by the registered error handler which attempts to navigate to the error page to show error information to the user. This time the navigation to the error page fails and the user is presented with very "user-unfriendly" error information from the application server itself with full stack trace. 

It seems in the second scenario, the lifecycle of the request processing is different from the first scenario when the session already exists. In the first scenario, the exception is caught earlier and not propagated outside of the request processing. In the second, while caught and processed by the custom handler, it is done in the catch clause of the VaadinService.handleRequest method that returns the exception back to the servlet container that, in turn, generates the standard error message with stack trace into the response.

It would be very nice if this issue is fixed. We have an unhappy customer who don't want to see stack traces instead of civilized user notifications.

**Comment by mstahv** [comment]
I think I have faced this issue as well, I think this is an issue that should be tackled. Do you happen to have a reduced example code to reproduce the issue? That would help the team a lot to attack on this. If fixing needs behavioural changes, now would be the time with Vaadin 8 coming out soon.

**Comment by sergetania** [comment]
I can probably put something together fairly quickly to illustrate the issue

**Comment by sergetania** [comment]
[error-handling.zip](https://github.com/vaadin/framework/files/652858/error-handling.zip)

Matti

I have attached a very simple project that illustrates the issue. Every other time the init method will throw an exception that will not be properly handled despite the fact that the error handler will be invoked. I don't think it needs to be inside of the init method as long as it is on the first request when the session is not yet created. If you click the button you can see the error handler properly handling the same exception.

Please let me know what else I can do to help with this. Thanks a lot!
Sergei

**Comment by mstahv** [comment]
The call to init method don't appear to be handled so that UI error handler (nor session error handler) are used. Without knowing the reasons why it is built this way, I'd say this is a bug. @Artur- , @Legioth ?

**Comment by sergetania** [comment]
An exception does not need to be thrown from the init method to be left uncaught but from (almost) anywhere on the first(session does not exist yet) request to Vaadin. If it was only the init method it would be easy to catch in the application. Because it is not the framework needs a fix. The same exception can be handled or not depending on whether it is the first an app is invoked or not.

**Comment by sergetania** [comment]
@Artur- , @Legioth 

Thank you fro looking into this!

I am sorry but you may be fixing only a small part of the issue. I only took a quick look at the fix so it is possible I didn't understand everything that is going on. I apologize if I am wrong but I feel responsible because the project I have created is too simple to show the root issue. To help with this, I am attaching a slightly advanced version of the original project that shows how an exception thrown on the first request (but not from the init method) is not handled.

To see the problem, go to 
http://localhost:8080/error-handling/#!Error
and you will see web container's stack trace; the exception thrown from the view is not handled

Now if you go to 
http://localhost:8080/error-handling/#!View
and click the button you will see exactly the same exception handled correctly.

If your fix allows to catch the exception thrown after going to the first URL then the root problem is fixed. If not, you might have fixed it only in the init method.

[error-handling-v2.zip](https://github.com/vaadin/framework/files/664279/error-handling-v2.zip)

**Comment by Artur-** [comment]
Hi,

As you see from the stack trace, the exception originates from `UI.doInit`, which is what here is wrapped in a `try` `catch`. The second case also works as expected, the `#!Error` view looks the same, regardless of if you navigate to it or reload it

**Comment by sergetania** [comment]
Artur,

Great! I have just checked a stack trace of our original issue and it also can be caught and handled in the UI.doInit. Perfect, the fix works!

Thank you for fixing!
Sergei
