### ISSUE TITLE
Drag'n'Drop doesn't work in Tables on IE with touch screen

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5170]
**Originally by @zch**

___
Drag'n'drop in a Table component is tricky, because we cannot disable the touch actions (like in #13368), because we must allow the Table component to be scrollable.

___
 Imported from https://dev.vaadin.com/ issue #13737

**Comment by sarahfuchs** [comment]
For our project the problem can be summarized as follows:
vaadin version 8.6.0
used code: grid with drag & drop
Classes Grid, GridDropTarget, RowMoveListener
Bug: on Notebook touch, IE the drag&drop does not work.
The notebook touch is: Suface Pro 4, Windows 10
Other setups (IE on  a PC or Chrome on Notebook touch) are working fine

Our code base is quite large. If you need specific Code snippets, please let me know.
Since its only the customer who works wich Notebook touch its complicated to write a simple test case.

**Comment by TatuLund** [comment]
@sarahfuchs Your description matches the issue https://github.com/vaadin/framework/issues/11219
