### ISSUE TITLE
Tree should show the expand/collapse icon only if node actually has children

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#518]
**Originally by _-Sami-_**

___
I'd like that the Tree component would automatically show the expand/collapse icon if the Item node has children and hide it if not. Now it shows the icon for every node unless explicitly denied.

At the moment our own Container.Hierarchical implementation handles this when adding Items, but it would be great if the Tree itself would do this. And we have situations where if we use some non-hierarchical Container with the Tree. Then we have to manually call setChildrenAllowed(, false) for each item, which isn't nice..

This could be a settable option for the Tree. And maybe the visibility of the icon shouldn't be directly based on the Item's capability to have children (set/areChildrenAllowed) as it's now (right?). I think the capability to have children is a separate thing from actually having children at the moment.

___
 Imported from https://dev.vaadin.com/ issue #1950

**Comment by anasmi** [comment]
Hi!

We are going through the process of closing issues, which were fixed in the newer versions of the framework, or have never been verified. This feature has been implemented in the newer versions.

If you disagree with the decision of closing this particular issue, please re-open it or create a new one, with explanation and/or example to reproduce.

Thanks for your help and contributions!
