### ISSUE TITLE
Favicons for windows

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#529]
**Originally by _dysii_**

___
Some way to add custom favicons to windows.

Using Window.setIcon() with the main Window or any opened (non-sub) Windows doesn't seem to do anything. 

There doesn't seem to be any way to add favicons with the Toolkit, as they are defined inside the <head> part of the page which we can't access.

___
 Imported from https://dev.vaadin.com/ issue #1984

**Comment by anasmi** [comment]
Hi,

there are lot of issues left without attention, so we are verifying which ones are still relevant as of Vaadin 8 . It seems that setting favicons for the window is now can be done modifying BootstrapPage as described here : https://stackoverflow.com/questions/25660659/vaadin-how-to-change-favicon if you have your custom named favicon, otherwise you can simply replace the Vaadin's default one preserving the name `favicon.ico`

Due to this, I will close this bug report. Through, please, create a new one if the issue is still outstanding or there is something I have missed in description.

Thank you for your investigation and contribution! :)
