### ISSUE TITLE
Overlays can't be made responsive to browser size.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5307]
**Originally by _ssindelar_**

___
When you want to make some parts of the application responsive to the size of the browser, e.g. font size, it is currently not possible to adjust it in overlays.

To make an application responsive to the browser the easyiest way I know is to add the Responsive Extension to a (full size) UI. The problem with overlays is that in the generated DOM they are outside of the UI and the responsive css selectors don't match the overlays. According to [Jouni Koivuviita](https://vaadin.com/forum#!/thread/7622424/7632051) he did forget to consider overlays when creating the Responsive-Addon.

Reproduction: Take the responsive demo, add an overlay and try to adjust the font size in the overlay the same ways it is adjusted in the normal demo.

___
 Imported from https://dev.vaadin.com/ issue #14020

**Comment by jouni** [comment]
As an effective workaround, regular CSS media queries should suffice for normal Vaadin applications that occupy the whole browser viewport, since the UI and overlay container elements are both as wide as the viewport.

The Responsive extension is more useful for resizable places inside the UI, and for browsers that do not support CSS media queries (IE8 only).

I’m closing this as wontfix, as version 8 does not support IE8 anymore, so the workaround is feasible for all supported browsers.

If you disagree, that CSS media queries fulfill this need, please reopen this issue.
