### ISSUE TITLE
MenuBar bugs on Android platform

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5873]
**Originally by _ngsage_**

___
Android version  4.2.2

With Android default browser, the popup containing the MenuItems of a MenuBar can't be dismissed. Maybe this bug is related to https://github.com/vaadin/framework/issues/5870?

With Chrome and Firefox, when the MenuBar is setAutoOpen(true), clicking on  a "root" MenuItem will show the popup for a very short time. Clicking on it a second time will work correctly (as long as the MenuBar doesn't loses focus).

See attached file.

___
 Imported from https://dev.vaadin.com/ issue #15188

**Comment by mvysny** [comment]
The issue is easily reproducible with Vaadin 8.12.0 as well. To reproduce, unzip the attached example app and run it via `./gradlew build appRun`. Then navigate to the app from your Android phone; I used Android 10 and newest Chrome.

The workaround is to set `isAutoOpen` to false - then the menu behaves nicely from the Android device. To detect a mobile device, just query `UI.getCurrent().getPage().getWebBrowser().isTouchDevice();`.

**Comment by TatuLund** [comment]
> I would expect that the MenuBar would ignore the autoOpen setting on touch devices, since the hover feature is not present on touch devices, and therefore the autoOpen setting doesn't make any sense and only breaks the component on touch devices.

That sounds like an acceptable solution to the problem.

**Comment by mvysny** [comment]
Excellent remark from Tatu: If you have hybrid laptop with both mouse and touch screen reporting itself as touch device

Therefore, a better check would be `BrowserInfo.get().isAndroid() || BrowserInfo.get().isIOS()`.
