### ISSUE TITLE
Grid cell focus indicator clipped

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6383]
**Originally by @magi42**

___
The cell focus indicator border is clipped in the rightmost column, and also half-way (maybe 1 pixel) in the bottom row.

___
 Imported from https://dev.vaadin.com/ issue #16864

**Comment by OlliTietavainenVaadin** [comment]
Reproducable in Sampler. Scrollbar overlaps the rightmost column by maybe 2px. Issue also reported in Support ticket #1760. See attached images:

![grid](https://cloud.githubusercontent.com/assets/15027701/23256627/e992b88e-f9c8-11e6-80d0-84072d408123.jpg)

![grid-cell-size](https://cloud.githubusercontent.com/assets/15027701/23256634/ee4e85d8-f9c8-11e6-9ecb-a87f8ad12a7e.png)

**Comment by pleku** [comment]
Apparently this is very fundamentally broken in the V7 and V8 Grid because it uses its own way of rounding the pixel calculations, which differs to from how what the browser does. Unfortunately it is far from trivial to fix this and from the original team implementing this there is nobody left.

Thus, sadly, we currently have no plans for rewriting how this rounding is going is done in V7 and V8. It has been fixed for V10 Grid which is based on the `vaadin-grid` Web Component.

As a workaround for the issue use the following css to apply proper offset for the `:before` pseudo element (which shows the outline) for the last cell:
```css 
.v-grid-cell-focused:last-child:before {
    right: 2px; /* This is how much the focus outline is clipped in Sampler */
}
```
If you have multiple grids where the outline is clipped a different amount, you can use a custom style name to make the selector more specific to match only that grid.
