### ISSUE TITLE
ComponentTree

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#672]
**Originally by @jouni**

___
Create a new widget similar to ITree, but with the option to use other widgets as node captions.

___
 Imported from https://dev.vaadin.com/ issue #2661

**Comment by anasmi** [comment]
Hi!

We are going through the process of closing issues, which were fixed in the newer versions of the framework, or would not be resolved for some reason. This feature has been implemented in the newer versions of Framework. [Vaadin Tree](https://vaadin.com/docs/v8/framework/components/components-tree.html)

If you disagree with the decision of closing this particular issue, please comment here and we will re-open it or create a new one, with explanation and/or example to reproduce the problem or how the desired behavior should be implemented.

Thanks for your help and contributions!

**Comment by AlexByte** [comment]
@anasmi how to show add checkboxes to a Tree?
