### ISSUE TITLE
Add orientation support for OptionGroup

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#681]
**Originally by @Artur-**

___
A OptionGroup is always vertical. Add support for a horizontal OptionGroup.

___
 Imported from https://dev.vaadin.com/ issue #2716

**Comment by anasmi** [comment]
Hi!

We are going through the process of closing issues, which were fixed in the newer versions of the framework, will not be fixed or have never been verified. This feature has an implementation in the newer versions of framework. (The decision is to use CSS, as mentioned above, but it's correct way to go)[HorizontalLayout part](https://vaadin.com/docs/v7/framework/components/components-optiongroup.html)

If you disagree with the decision of closing this particular issue, please comment here and we will re-open it or create a new one, with explanation and/or example to reproduce.

Thanks for your help and contributions!

And have a nice day :)
