### ISSUE TITLE
Text selection is not possible in a Notification window

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6904]
**Originally by _ivan.belis_**

___
It is not possible to copy/paste a message from a Notification window.
The notificiation window is sometimes used for displaying error messages.
The end-users cannot select this error message to pass the information to the help desk.

Feedback from the forum:
https://vaadin.com/forum#!/thread/10373762/10374161 

Indeed it looks like text selection doesn't work there. Apparently, VNotification eats up mouse-down events in onEventPreview(), so you can't select anything.

___
 Imported from https://dev.vaadin.com/ issue #18348

**Comment by sirbris** [comment]
will there be an option one day to copy the notification text?

**Comment by Legioth** [comment]
Might be the same root cause as #5963. In that case, you can fix it in your own theme simply by defining   e.g. `user-select: text` for `div.v-Notification`.

**Comment by sirbris** [comment]
doesn't seem to work with NOTIFICATION_ERROR though... any hints?

**Comment by Legioth** [comment]
@sirbris I assume your already found a solution for the error notifications based on your comment in #5946?

**Comment by sirbris** [comment]
I'm afraid not... the solution with css (user-select) works for component error and some Notifications but not notification with NOTIFICATION_ERROR style. The other problem of course is that's kind of tricky to select and copy the text without closing the notification ;)

**Comment by Legioth** [comment]
Oh right, the error notifications eat mouse events for closing themselves, in addition to the `user-select` CSS that is also applied to them.

I cannot come up with any simple solution here, short of modifying the implementation to e.g. only trigger the closing for click events instead of mousedown. That might then of course also have other side effects...

I sometimes use the browser's DOM inspector to get hold of stuff that e.g. disappears when clicked or hovered, but that's of course not something that regular users can be expected to do.

**Comment by sirbris** [comment]
exactly... in my case I'm talking about a business application, in which it's not uncommon for a server error or such... so if anybody can think of a slick way to show growling like notifications with the ability to copy the text, I would greatly appreciate it :)
