### ISSUE TITLE
Number spinner widget

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#691]
**Originally by @freducom**

___
A textarea with up and down buttons and increase and decrease the value in the "textarea" or whatever. So that you on the serverside could define e.g. 

NumberSpinner(int maxValue, int minValue, int increaseStep, int decreaseStep) and it would create the numberspinner which incremenets and decreases as defined in the constructor above.

___
 Imported from https://dev.vaadin.com/ issue #2768

**Comment by anasmi** [comment]
Hi,

We are going through the process of closing issues, which were fixed in the newer versions of the framework or have been worked through some other way. As it mentioned above, the similar component *Stepper*  is implemented as add-on and it provides the desired functionality.

If you disagree with the decision of closing this particular issue, please comment it here and we will re-open it or create a new one, with explanation and/or example to reproduce.

Thanks for your help and contributions!
