### ISSUE TITLE
Fisheye widget

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#692]
**Originally by @freducom**

___
Similar as in the OS X dock. e.g. Dojo has this. 

___
 Imported from https://dev.vaadin.com/ issue #2769

**Comment by anasmi** [comment]
Hi!

We are going through the process of closing issues, which were fixed in the newer versions of the framework, will not be implemented or verified. 
It looks like this feature was not implemented.

If you disagree with the decision of closing this particular issue, please comment here and we will re-open it or create a new issue, with explanation and/or example to reproduce. Might be in this particular case it would be better to create a new issue with an example how component should feel/look like.

Thanks for your help and contributions!

And have a nice day! : )
