### ISSUE TITLE
request properties are mutated while in the init method

### ISSUE THREAD

**Issue by Flamenco** [vaadin/framework#7951]
I have an init method that looks like this:

```java
init(VaadinRequest request){
   String idBefore = request.getParameter('id');
   doWorkAndPush()
   String idAfter = request.getParameter('id');
}
```
Intermittently the idAfter is NULL even though the request did have an id query parameter and the idBefore is the correct value.  I would assume the request object would be locked for the duration of the method.  I would understand that if I launched a thread and returned from init() that there could be issues, but that is not the case here.

The workaround is to cache the request at the beginning of the method.

**Comment by Flamenco** [comment]
Why do I event bother filing these issues?

**Comment by tsuoanttila** [comment]
Hi @Flamenco, you bother filling out these issues, because they cause trouble for you. Unfortunately the number of incoming tickets is more than we can handle right now, so we try to at least get the old ones (already fixed, no longer relevant, or otherwise unnecessary) out of the way and make the total number of tickets actually manageable.

I took a quick look at the short code snippet you had and tried to make it break in a test project, but unfortunately I was unable to figure out what `doWorkAndPush()` is doing that makes it break.

**Comment by Flamenco** [comment]
Do work and push meant block for a while on a function and call methods that push data via the atmosphere channel.  This was 1.5 years ago though and it's a big foggy at the moment.  I think that question should have been asked 500+ days ago. 

Perhaps it was fixed. IDK.  I applied the workaround back then and have just kept it in place.

**Comment by Flamenco** [comment]
FYI I also called Thread.sleep in the doWork method while waiting for bundles to load and pushing messages to the client.
