### ISSUE TITLE
Tree.getChildren(Object itemID) yields only one child in the collection.

### ISSUE THREAD

**Issue by enver-haase** [vaadin/framework#7984]
Here's example code that shows only one child is returned, should be two (BAR and BAZ).

```
package com.example.myapplication;

import java.util.Collection;

import javax.servlet.annotation.WebServlet;

import com.vaadin.annotations.Theme;
import com.vaadin.annotations.VaadinServletConfiguration;
import com.vaadin.server.VaadinRequest;
import com.vaadin.server.VaadinServlet;
import com.vaadin.ui.Tree;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

@Theme("mytheme")
public class MyUI extends UI {

	private final static String FOO = "Foo";
	private final static String BAR = "Bar";
	private final static String BAZ = "Baz";
	
	
    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        
        Tree tree = new Tree();
        tree.addItem(FOO);
        tree.setChildrenAllowed(FOO, true);
        tree.addItem(BAR);
        tree.setChildrenAllowed(BAR, false);
        tree.addItem(BAZ);
        tree.setChildrenAllowed(BAZ, false);
        
        tree.setParent(FOO, null);
        tree.setParent(BAR, FOO);
        tree.setParent(BAZ, FOO);
        
        if (tree.hasChildren(FOO)){
        	@SuppressWarnings("unchecked")
			Collection<String> children = (Collection<String>) tree.getChildren(FOO);
        	for (Object id : children){
        		System.out.println(id);
        		tree.removeItem(id);
        	}
        }
        else{
        	System.out.println("No children of foo known.");
        }
       
         
        layout.addComponents(tree);
        layout.setMargin(true);
        layout.setSpacing(true);
        
        setContent(layout);
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
```

Output: 'Bar' (only that is returned and removed).

See also:
https://vaadin.com/forum/#!/thread/14729190/14729189

**Comment by enver-haase** [comment]
Tested in Framework 7.7.6 .

**Comment by Legioth** [comment]
This happens because you're iterating over the same collection that is being modified (indirectly through `removeItem`). From what I can see, there are two potential things that the framework could do about this, and neither is really good.

1. Change the underlying `HierarchicalContainer` to use `ArrayList` instead of `LinkedList` since `ArrayList` would throw an `ConcurrentModificationException` instead of silently returning an unexpected value.
2. Make `getChildren` return a copy of the collection instead of just an unmodifiable view into it. This would instead have a performance impact that should in most cases be quite small, but I'm still not sure if it's worth the hassle.

**Comment by enver-haase** [comment]
Above iterates over the collection being modified.

However: Should we not return a copy instead of the very collection at heart of the Tree?

I'll leave the bug open so that at least the issue can be documented, as in "make sure when you modify, this is not a copy" or such.

**Comment by enver-haase** [comment]
I really do like 1. above, Legioth.
