### ISSUE TITLE
Wish: add Sanitizers to Framework for XSS security

### ISSUE THREAD

**Issue by enver-haase** [vaadin/framework#8000]
A customer has this idea:

Analogous to the use of Validator to validate,
a (chain of) Sanitizer could be added to components that render HTML, e.g.
to filter out malicious user-entered content.

```
extField field = new TextField("Name");
field.addValidator(new StringLengthValidator());
field.addSanitizer(mySanitizer);
```

This, in his opinion, would make the promise
"Cross-Site Scripting (XSS)
Vaadin has built-in protection against cross-site scripting (xss) attacks. Vaadin converts all data to use HTML entities before the data is rendered in the user's browser.*"
(https://vaadin.com/security)
more credible.

**Comment by Legioth** [comment]
What's the difference between a sanitizer and a converter?

Please also keep in mind, that XSS is specific to the context where data is shown, not the source of the data. Therefore, the sanitization should in general be done for the output (e.g. a `Label`) and not the input (e.g. `TextField`).

And the statement from our Security page is still 100% credible in my opinion. All components (except `Component.setDescription(String tooltip) and `RichTextArea.setValue(String value)` that are explicitly special) already show all contents as plain text instead of interpreting it as HTML.

**Comment by WoozyG** [comment]
Actually, there are more places raw HTML is output, some with little or even no warning, see my comprehensive list in 

[https://github.com/vaadin/framework/issues/7542]

In some cases you have to escape it yourself, in others you need to pass a constant flag, in still others it's a boolean property... confusing and ripe for mistakes by the developer.

This suggestion could get part way to a solution, but among other things the wide array of standards and styles need to be converged on a single well defined set of interactions and patterns.
