### ISSUE TITLE
Please add addValueChangeListener override with possibility to give ValueChangeMode to TextField

### ISSUE THREAD

**Issue by johannesh2** [vaadin/framework#8101]
Please add the following method to TextField API in Vaadin 8
TextField.addValueChangeListener(ValueChangeListener<T> listener, ValueChangeMode mode)

**Comment by Artur-** [comment]
That would imply that the value change mode is connected to the listener, which it currently is not.

**Comment by johannesh2** [comment]
I'll make an: "improve documentation ticket" in final then.

**Comment by mstahv** [comment]
IMO it don't need to be and it could be maybe made such in the future (if somebody will get very bored in his/her life). The suggested API addition would remove an extra line in almost all "search field" implementations, I think it would make sense to help our users here instead of aiming for "academically correct" API.

**Comment by samie** [comment]
This could use different name to avoid implying what @Artur- suggested?

**Comment by Legioth** [comment]
What about setting the change mode through a constructor?
