### ISSUE TITLE
Rename HasValue.setReadOnly to something which describes what the method does

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#8152]
"Read only" sounds like the value can't be changed. The javadocs, however, specify that the *user* can't change the value. Could it be something descriptive, like `setUserInputAllowed`?

**Comment by pleku** [comment]
I disagree. What good is a read-only component, that I cannot change the bound data on (like in V7)? 

Is userInputAllowed used elsewhere instead of read-only? What if the component has controls that don't influence the value - should user input be allowed on those or not?

**Comment by Artur-** [comment]
This is about naming only. I do not think the V7 "readonly for everybody" feature makes sense

For simple input components like TextField I can very well understand what read only means. If the same concept is used in other cases like Grid selection models, I think another name would be more descriptive/intuitive

The same questions about what should be allowed in components apply regardless of the naming.

**Comment by pleku** [comment]
There is two tickets about making Grid SelectionModel read-only API it more visible, since currently it is only visible when binding it to binder with asSingleSelect and asMultiSelect. 

Perhaps read-only is best for all text input based fields, and for Grid and some selects it would make more sense to have userSelectionAllowed. Anyway I think read-only is the best for HasValue. UserInputAllowed is to me much more confusing, because I'm not sure what input it means in some cases.

**Comment by Legioth** [comment]
`HasValue.setReadOnly` makes very much sense from the point of view of `HasValue`, and it's also in sync with how e.g. `<input readonly>` works in HTML.

The problem here is really that the `HasValue` semantics do not make sense for `Grid`, in part because it's not a `HasValue`. There should instead be a "direct" way of setting grid to not allow user selection that isn't based on the naming used for `HasValue`, e.g. `GridSelectionModel.setUserSelectionAllowed(boolean)` that I suggested in https://github.com/vaadin/framework/issues/8150
