### ISSUE TITLE
Consider supporting "old style" removeFooBarListener methods

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#8159]
removeFooBarListener style methods now seem to be deprecated (and no methods for some new listeners). This adds a new code in case one implements listeners directly to the class adding/removing listener, which is a pretty common habit among Vaadin developers. Now need to add extra field for each listener Registration.

I don't know the full story/discussion about this change (available somewhere ?), but maybe it would be helpful for users if the old style remove listener methods where still available/non-deprecated.

**Comment by Legioth** [comment]
Could you please elaborate what the habit you're referring to looks like?

**Comment by mstahv** [comment]
class MyClass implements ClickListener {
    
         void init() {
            addClickListener(this);
         }
    
         void cleanup() {
            removeClickListener(this);
         }
    
          void onClick(CklickEvent e) {}
    }

See for example com.vaadin.navigator.Navigator.UriFragmentManager in the framework itself.

**Comment by jreznot** [comment]
Old style add/remove is really useful. I believe that you will not deprecate it.

**Comment by Legioth** [comment]
Why do you want `MyClass` to have `onClick` in its public API?

Before Java 8, the pattern of making the main class implement a listener interface was a tradeoff between code size (you don't need to do `new SomeListener() { ... }`) and bloated public API (since the listener method becomes public API).

With Java 8 and lambdas / method references, this tradeoff no longer makes sense since using a lambda needs even less code, still without bloating the public API. See an example of this improvement in https://github.com/vaadin/framework/pull/8164/files#diff-b412c4a2bde9fed33e8e3781f06a9e3bL104

The full story for `Registration` instead of `removeXyzListener` is basically like this:

* Identical lambas or method references are not equals with themselves, so you cannot do `someComponent.removeXyzListener(this::doSomething)`. You'd need to know that you must store the lambda as an instance field (with a non-obvious type) and then remove that particular instance.
* The existence of a `removeXyzListener` would most likely cause unexpected memory leaks because many developers wouldn't realize the above point.
* This entire problem can be avoided by making `addXyzListener` return a `Registration` instance and removing `removeXyzListener`. You'd still need to have one instance field (either the listener instance or the registration instance) regardless of which pattern is used. The only exception to this is the pattern discussed here where `this` is used as the listener and no separate instance field is needed. But as described above, this pattern is no longer a sensible tradeoff.
* Supporting both `Registration` and `removeXyzListener` would be confusing and would still invite to doing `someComponent.removeXyzListener(this::doSomething)` which won't work.
* Getting rid of `removeXyzListener` makes it easier to implement listener delegates in custom components. To support `removeXyzListener`,  you'd need to have some bookeeping to know which other listeners to remove when the high level listener is removed. Without `removeXyzListener`, you can instead do like this:
```
public Registration addHighLevelListener(HighLevelListener listener) {
  return addLowLevelListener(lowLevelEvent -> listener.onHighLevelEvent(createHighLevelEvent(lowLevelEvent));
}
```

**Comment by jreznot** [comment]
Our classes do not expose its public API since we do not use concrete classes but use interfaces instead. So we can safely implement additional interfaces using root class. 

Often we reuse the same listener (e.g. inside of Composite components) for all the buttons of layout and in case of Registration we need to store List of registration objects.

**Comment by Legioth** [comment]
After discussing this with the team, the conclusion is that we do not want to have to different ways of removing listeners, and that the one based on `Registration` is in general more user friendly (because of lambdas).

There are of course also some cases where `removeXyzListener` would be more convenient, and we're considering adding a helper class to slightly help deal with such situations.
