### ISSUE TITLE
Add DropTarget Extension

### ISSUE THREAD

**Issue by pleku** [vaadin/framework#8170]
The whole component is the _dropTarget_.

**Comment by jouni** [comment]
Is this (and DragSource extension) going to replace DragAndDropWrapper?

**Comment by Legioth** [comment]
> Is this (and DragSource extension) going to replace DragAndDropWrapper?

They will allow roughly the same kinds of use cases, but in a different way. They will thus replace `DragAndDropWrapper`, but they wouldn't be drop-in replacements.

**Comment by jouni** [comment]
Check. Just checking and making sure we design the CSS for this festure better than we did for the dnd wrapper.

**Comment by Legioth** [comment]
@jouni Could you please elaborate on the CSS issues with the "old" implementation?

**Comment by jouni** [comment]
Here’s the original issue: #1748

I’ve of course already forgotten what the exact problems are. But I think it was the fact that the `.no-*-drag-hints` classes needed to be added to a parent component/layout rather than on the actual DragAndDropWrapper component, because IE6 CSS limitations (no support for multiple class selectors).

Valo theme has “fixed” this already by having both nested and combined class selectors. But, the naming is still wrong, and maybe the developers should explicitly opt-in to certain drop hints rather than opt-out.

**Comment by wbadam** [comment]
Firefox fires `dragleave` when element dragged on child.
For example when dragged onto `<div draggable=true>Some Text</div>`, Chrome will fire one `dragenter` whereas Firefox will fire `dragenter` on the edge of the element and then `dragleave` when dragged over the text.

**Comment by pleku** [comment]
Closed with #8264
