### ISSUE TITLE
Sensible getValue() and setValue() for RichTextAreaElement

### ISSUE THREAD

**Issue by hesara** [vaadin/framework#8184]
@vaadin-bot commented on [Wed Feb 04 2015](https://github.com/vaadin/testbench/issues/768)

**Originally by @Ansku**

___
There should be a sensible way for getting the text contents of RichTextAreaElement.

___
 Imported from https://dev.vaadin.com/ issue #16578

**Comment by Artur-** [comment]
`getValue()` should be easy to implement as something like `return getIframe().getContentBody().getBody().getInnerHTML()`
`setValue()` can assign the value to the same place but would need to have a way to fire an `input` or `blur` event so that the value is actually sent to the server. Alternatively use `sendKeys` to set the value

**Comment by Artur-** [comment]
```
var richTextArea = $0;
var body = richTextArea.querySelector("iframe").contentDocument.body;
body.innerHTML = "<b>Hello<b><u>world</u>";
body.dispatchEvent(new CustomEvent("input"));
```

works at least in Chrome
