### ISSUE TITLE
com.vaadin.v7.data.util.converter.Converter is not backwards compatible

### ISSUE THREAD

**Issue by eiswind** [vaadin/framework#8214]
version 8.0.0.beta1

Converter used to have two methods. The new one in v7 is breaking my code, it has four methods and different signatures

**Comment by Legioth** [comment]
Sounds like the wrong `Converter` type is imported in your code. There are two types named `Converter` in Framework 8 if you're also using the compatibility packages.
* `com.vaadin.data.Converter` in is intended to be used with the new `Binder` API and has has two abstract methods: `convertToModel` and `convertToPresentation`.
* `com.vaadin.v7.data.util.converter.Converter` is in the compatibility package and is intended to be used together with `Field` components in the compatibility package. It has the same four abstract methods that `com.vaadin.data.util.converter.Converter` used to have in Framework 7: `convertToModel`, `convertToPresentation`, `getModelType` and `getPresentationType`.

Could you try changing the import to `com.vaadin.data.Converter` instead of `com.vaadin.v7.data.util.converter.Converter`?

**Comment by eiswind** [comment]
WTF! My fault. As I first tried the alpha I changed this single class. This happened quite a while ago and I did not remember. Now at least it compiles!
