### ISSUE TITLE
Grid creation with many columns is slow (blocks browser)

### ISSUE THREAD

**Issue by pichlerm** [vaadin/framework#8216]
We observed that creation of a Grid with many columns takes up much client time (browser javascript).

The grid has a large number of columns (e.g. 500), where only a small number thereof (e.g. 10) is visible and the user can select which additional information he wants to see.

When the grid is created, the server request is fast (less than 0.5 ms), but then the browser is busy (blocks) to execute the javascript for a long time - over 45 seconds.
According to the browser log the expensive step is "Sending state change events".

The broswer DOM is very compact: it contains only tr's/td's for the visible rows/columns, thus this does not seem to be the limitation; scrolling the grid data is very fast. Also, filling the existent grid with new data is fast (less than a second).

Attached files:
VaadinlargegridUI.java ... test program
consoleLog.txt ... browser console log

Vaadin version: 7.7.6

**Comment by pichlerm** [comment]
[VaadinlargegridUI.java.txt](https://github.com/vaadin/framework/files/698909/VaadinlargegridUI.java.txt)
[consoleLog.txt](https://github.com/vaadin/framework/files/698910/consoleLog.txt)

**Comment by pleku** [comment]
Grid does not lazy-load columns nor recycle the elements in DOM (it does both for rows). For a really large amount of Columns, you should use our `Spreadsheet` add-on, since it lazy loads both columns and rows.

If you want to keep using Grid, you should maybe not using all of the columns to the users, having more than 20 columns might lead to UX issues unless they have really large screens. And even then, it might not be easy to interpret data from that many columns.

Closing this ticket as `wontfix`.

**Comment by pleku** [comment]
Ok, thanks for the info. For now, let's keep #10232 as the tracking point for making sure the V8 `Grid` performance would be on par with atleast V7 `Grid` and old `Table` component.
