### ISSUE TITLE
Add a method to specify filtering strategy in ComboBox

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#8285]
In Vaadin 8 beta 1 filtering strategy must be given (always) with the option in setItems(CaptionFilter, Collection<T>) method. It would be nice to set it separately as well, as options are often changed dynamically unlike the filtering strategy.

It is also quite hard to find, at least for this kind of Vaadin dinosaurs who is looking for setFilteringMode method.

**Comment by Legioth** [comment]
The reason why it's done in this way is that a filtering strategy only makes sense for in-memory data. 

With lazy data providers, there's no guarantee that the used data provider actually supports filtering according to any specific strategy since it might be backed by something like `PersonService.findPersonsByName(String name)` implemented using DeltaSpike or Spring Data. In that case, the actual strategy depends on how that method works and is something that ComboBox cannot control at all.

I understand that this is inconvenient if you want to change the options dynamically, but I cannot come up with any approach that would help that case without making more common cases more confusing or more complex.
