### ISSUE TITLE
MenuBar pop-up menu overlaps bar if space below is limited

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/framework#8326]
Vaadin version 7.7.6
If a MenuBar contains many items and there is not enough room below the menu, the pop-up menu will appear on top of the MenuBar and you can't choose items from the bar.

The problem is not solvable via CSS because
* The container for the opened menu is created outside of the structure which holds the button. Therefore it can't be accessed via style-class
* The position of the container is calculated from above, not from below. That makes it hard to calculate if the container reaches the bottom end.

The behavior is reproducible in Vaadin Sampler (although the menus there aren't very tall, so the window must be quite narrow to see the effect)
![menubar-overlap](https://cloud.githubusercontent.com/assets/15027701/22281628/ac822ea6-e2e0-11e6-8e96-20c3df2c5018.png)

The preferred behavior would be as follows:
* If there's not enough room below the menu bar but there is enough room above the bar, the pop-up menu should appear above the bar in a way that it doesn't overlay the bar itself 
* If there's not enough room above the menu bar either, the pop-up menu should be below the menu and get a scrollbar

**Comment by elmot** [comment]
Having scrollbars in menus is not the best idea from user experience point of view, especially for mobile users. 
Menus are supposed to be small enough to fit any reasonably-sized window. 
On the other hand, the existing menu popup which appears on top of the menu does not break the navigation nor inside the menu, nor outside it.

It looks like the described problem could be solved using `ComboBox` component instead of `MenuBar`, which has both popup paging and popup scrolling modes (see `setPageLength()`), never overlaps the component, and, as a benefit, supports text filtering out of the box.

Another option is to build a custom component, with all the desired functionality.
