### ISSUE TITLE
Shorter Initialization for BeanBinder

### ISSUE THREAD

**Issue by amahdy** [vaadin/framework#8358]
Vaadin 8

Would be better to initialize BeanBinder with the bean as a parameter only, without the need to give it one more time as a parameter in the constructor.

cc: @Legioth

**Comment by Legioth** [comment]
After our conversation, I realized why it would not be feasible to do things in the way we envisioned.

`Binder` (since the `BeanBinder` functionality has been merged into `Binder`) needs to know the class of the bean when you do e.g. `myBinder.bind(nameField, "name")` or when the same action is carried out indirectly through `myBinder.bindInstanceFields(myDesign)`. Without this, it cannot verify there really is a `getName()` method in the bean and that it returns a type that is compatible with `nameField`.

There are at least two ways around this, but both options have side effects that I don't think are worthwhile.
1. We could do the validation lazily when `setBean` is actually called based on `bean.getClass()` of that instance. The problem here is that we'd need to do this separately for each time `setBean` is called (since each bean might be of a different subclass) and that resulting stacktraces would give no indication of where in the code the actual problem is (e.g. a typo in a property name string).
1. We could require you do run `setBean` with a non-null instance (or pass an actual bean instance to the constructor instead of currently required class literal) before running any `bind` method. In addition to the same kind of problem as with approach 1., this also requires a bean instance to be available when the view is being initalized. This is not the case in many situations where the form is shown even before the user has selected a bean to edit.

Please also note that the required constructor parameter is the class literal, not a an actual bean, and that there is therefore technically no duplication, even though two pieces of similar information is given. `Person` is written out twice the the code, but the one in the type parameter is something that your IDE will auto complete for you if you've written out the class literal.
```
Binder<Person> binder = new Binder<>(Person.class); 
binder.bind(nameField, "name");
binder.setBean(personInstance);
```

It's also noteworthy that passing the class literal to the constructor is the "price you pay" for being able to define bindings based on just the bean property name. Without the class literal, you can still define a binding with explicit callbacks.
```
Binder<Person> binder = new Binder<>();
binder.bind(nameField, Person::getName, Person::setName);
binder.setBean(personInstance);
```
