### ISSUE TITLE
Report issue if Binder.bindInstanceFields doesn't find a single field to bind

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework#8362]
It is with very high likelihood a programming error if `Binder.bindInstanceFields` doesn't have any effect at all. It would be good to directly report this to the developer so that they can realize that the passed instance is probably not suitable for being used in that way. It's up to debate whether this should be reported by logging a warning message or throwing an exception.

**Comment by darkwitch** [comment]
I would take this even further - why not be able to specify how many fields are expected to be bound using binder, for ex:

`binder.bindInstanceFields(content).expectMinimalBindingsOf(5);`

And I'd go with the exception approach, It's way easier to detect exceptions when doing any sort of testing.

**Comment by denis-anisimov** [comment]
>binder.bindInstanceFields(content).expectMinimalBindingsOf(5);

This is a big magic:
- most simplest case is do not use proposed `expectMinimalBindingsOf` at all (and there will be a huge amount of people who don't use it at all). In this case I don't see at which time "binding" should be applied ? It can't be applied as a result of `bindInstanceFields` since `expectMinimalBindingsOf` should be taken into account. So it should be inside `expectMinimalBindingsOf` but in this case `bindInstanceFields` won't work without `expectMinimalBindingsOf()` additional call at all.
- `expectMinimalBindingsOf` could do postcheck though when binding is already done. This will requires a track of fields bound using this method.
- I don't think it's useful in reality to have hardcoded number of fields that have to be bound: this number has a tendency to change during development (which means that each time when fields are updated the piece of the code in the different part should be changed as well). The other reason is: the number is not 1:1 with the list of the fields that have to be bound.

There is a very good reason of the suggestion : how 0 bound fields (original issue) is better than any other number of "incompletely" bound fields  ?

So I would suggest to introduce rather something like `@Required` annotation which can be attached to fields that expected to be bound and throw an exception if such field is unbound .
But this is separate issue.
I will fix here the original one only.

**Comment by darkwitch** [comment]
I agree having calls like `expectMinimalBindingsOf(5);` is BAD, but who says you should use it like this? 

With some reflections it could easily be used like this:
`binder.bindInstanceFields(content).expectMinimalBindingsOf(countHasValueFields(content));`

From what I see looking at Binder code there already is a track of fields, granted it's 'global', but this is actually perfect:

`private final Map<String, Binding<BEAN, ?>> boundProperties = new HashMap<>();`

So the simplest solution would be something along these lines:
```
public Binder expectMinimalBindingsOf(int minFieldsBound) {
   if (boundProperties.size() < minFieldsBound) throw new SomeBindingException();
   return this;
}
```
It's simple to implement, non intrusive, optional for users, quite safe, does not 'break' existing API. And it opens a lot of doors.

### `@Required` 
'@Required' could be achieved using the proposed solution:
`binder.bindInstanceFields(content).expectMinimalBindingsOf(countRequiredProperties(bean));`

### `@BindingRequired` 
However in some usecases `@Required` on Bean properties could be trouble, as some of them might be updated based on data from UI, but not directly by the UI. Also we still wanna bind not required fields for optional input from users.
A custom @BindingRequired on HasValue fields could be better in those cases, but would require support from the Designer, which I guess would take a while (and lack of it would cause trouble for designer users like myself :) )

However Designer users could develop field naming scheme, for ex: naming field with a Field postfix (ex. `TextField loginField;` instead of `TextField login;`) and using the original solution:
`binder.bindInstanceFields(content).expectMinimalBindingsOf(countRequiredFieldsByName(content));`
**But this would require fixing #8462 first.**

Non designer users could achieve the same as well with again some reflections + user defined annotations:
`binder.bindInstanceFields(content).expectMinimalBindingsOf(countRequiredFields(content));`

### Future?
A single expectMinimalBindingsOf() is enough to do quite a lot and it could be used for new methods like:

- for Annotated HasValue fields
`binder.bindInstanceFields(content).expectAllAnnotatedFieldsBound(BindingRequired.class);`
`binder.bindInstanceFields(content).expectAllRequiredFieldsBound();`

- for Annotated bean properties
`binder.bindInstanceFields(content).expectAllAnnotatedPropertiesBound(Required.class);`
`binder.bindInstanceFields(content).expectAllRequiredPropertiesBound();`

**Comment by denis-anisimov** [comment]
> boundProperties

This is not so easy as it's seen at a glance.

Even now there are already questions without obvious answer.
`boundProperties` at the moment is used to track explicitly bound properties. It means that there are 2 types if fields in a component class (actually even 4): bound explicitly and bound automatically via `bindInstanceFields`.
- The first type is the fields that are bound via the `Binder::forField(field).bind()` call ( and `field` here is a field from the component).
- The second type is the fields that are intended to be bound automatically via `bindInstanceFields`.

`boundProperties` are used to exclude the properties of the first type from the second type.

In reality there are two more types:
- The fields that are not bound automatically (intentionally or because of mistakes). We are trying to avoid mistakes exactly for those fields.
- The fields that are incompletely bound. Those fields are considered to be explicitly configured but bound via `bindInstanceFields`.

So it's already a mess. And it is not obvious which number of fields you are going to check using proposed `expectMinimalBindingsOf`: all the types? only second types ? some combination of types ?

It's an API question and it's very confusing.

At the moment in the implemented PR the last type is not considered as automatically bound fields. And I don't really know whether it should be considered or not.

Fell free to provide a PR for the functionality that you are requesting. Will see how it works.

**Comment by darkwitch** [comment]
Given the discussion above I think `expectMinimalBindingsOf ` should be a measure to check whether all 'required' fields are bound, no matter how the actual binding happened (a call to `Binder::bindInstanceFields` should not be even required). 
This would solve problems of missing bindings:
-  when refactoring fieldNames either when using 'Binder::bindInstanceFields' or 'Binder::bind(field, "propertyName")
- when user simply forgets to bind fields or makes naming mistakes

In the implemented PR you're checking whether a call to `Binder::bindInstanceFields` changes anything and It's ok. What I propose goes further as it validates all bindings. It also makes implementation simple, we just check all `private final Set<BindingImpl<BEAN, ?, ?>> bindings`, like this:

```
public Binder expectMinimalBindingsOf(int minFieldsBound) {
   final long boundFields = bindings.size();
   if (boundFields < minFieldsBound) throw new SomeBindingException();
   return this;
}
```

One issue though - even though `bindings` is a `Set`, BindingImpl does not override `equals` & `hashCode`, so multiple bindings of the same field are possible which makes the above solution faulty when combining manual & automatic binding.

I don't think this behaviour was intended (if so `bindings `should probably not be a `Set`, if not `equals` & `hashCode` should be implemented). Is that a bug ?

If this was intended then this should work

```
public Binder expectMinimalBindingsOf(int minFieldsBound) {
   final long boundFields = bindings.stream().map(BindingImpl::getField).distinct().count();
   if (boundFields < minFieldsBound) throw new SomeBindingException();
   return this;
}
```
