### ISSUE TITLE
Ensure vaadin-icons is OSGi compatible

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework#8471]

**Comment by alexweirig** [comment]
Hi,

I've included Vaadin-icons into a valid bundle (Sampsa Sohlmans compatibility pack).

Unfortunately it turns out that when I use Designer files in my OSGi portlet, vaadin-server seems to be invalid too.
There is no Import-Package for com.vaadin.icons in the MANIFEST.MF for vaadin-server.

This makes using Designer files impossible at the current state.

This is all beta2

Do you want me to open a ticket in Vaadin support for this?

Alex

**Comment by elmot** [comment]
We included VaadinIcons into the framework itself starting from RC1. So, there is no need to load VaadinIcons to OSGi container anymore, and it does not require any OSGi manifest. See #8485.
Please do not open tickets related to this issue.

**Comment by alexweirig** [comment]
Hello,

works like a charm.

Thank you

Alex
