### ISSUE TITLE
Migration to vaadin 8

### ISSUE THREAD

**Issue by mbx2015** [vaadin/framework#8697]
Hello,
I'm using Vaadin 7 + Spring boot + IntelliJ IDEA as IDE.
I am already migrated to Vaadin 8 using the framework8-migration-tool,  But I got the next error 

> Widgetset 'com.vaadin.DefaultWidgetSet' does not contain an implementation for com.vaadin.vv7.ui.TextField .....

**Comment by Legioth** [comment]
You'll also need to add `@Widgetset("com.vaadin.v7.Vaadin7WidgetSet")` to your UI class (and ensure you have added `vaadin-compatibility-client-compiled` as a dependency).

The migration tool doesn't automatically reconfigure your application to use the widgetset that contains the compatibility classes since that needs to be done in different ways depending on how the application is configured.

**Comment by mbx2015** [comment]
Thanks, It works!!
