### ISSUE TITLE
CSRF token passed in GET request

### ISSUE THREAD

**Issue by pwilkin** [vaadin/framework#8700]
According to the OWASP guidelines, the CSRF token should not be passed in a GET request. 

https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Disclosure_of_Token_in_URL

However, Vaadin discloses the CSRF token in PUSH requests:

ws://.../.../PUSH?v-uiId=1&**v-csrfToken=060bbda2-1acd-47ff-b9a8-4cc6b31946ee**&X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.2.13.vaadin5-javascript&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&Content-Type=application/json;%20charset=UTF-8&X-atmo-protocol=true

**Comment by Legioth** [comment]
The reasons described by OWASP are mainly about GET requests in the sense of embedding the token in a link. The pattern we are using only sends the token as an XHR request. This means that the concerns about HTTP log files network appliance logs are still valid, but the more significant concerns about browser history and Referer headers do not apply.

The request in question will probably have to be a GET request because of the way Atmosphere works, but we might consider whether the token is at all necessary for that request since it's still also included in the JSON payloads. Another option that would require some additional coding would be to pass the token in a handshake message or a HTTP header instead of sending it as a GET parameter.

**Comment by pwilkin** [comment]
The problem is we just got audited by an external security company and one of the flaws outlined was the CSRF GET request. While I understand the reasons outlined above, the ability to intercept HTTP logs / browser cache to forge CSRF tokens means that this is still a valid security issue. Removing the token and retrieving the data from the JSON payload would be the preferrable solution here.

**Comment by Legioth** [comment]
This turned out to be more tricky than anticipated. We cannot simply remove the token since a unique value is needed for distinguishing connection attempts from old sessions (see https://github.com/vaadin/framework/issues/3807). That id doesn't have to be the CSRF token, but using a value specific for this case would require implementing some additional bookkeeping.

Sending the value as an HTTP header instead of in the query string might also be possible, but Atmosphere discourages that since "Some browser only support the GET method with some transport and prevent setting headers" (https://github.com/Atmosphere/atmosphere/wiki/atmosphere.js-API#attachheadersasquerystring-default--true).

It seems like our options would be one of these:
1. Investigate whether the claimed browser limitation is actually relevant for the set of browsers that we support.
2. Make the server generate a random identifier for each UI instance and pass that identifier to the client for use when opening push connections.

**Comment by pwilkin** [comment]
Solution 2 might be actually preferrable in that it doesn't seem to be that difficult to simply pass some UUID.

**Comment by Legioth** [comment]
We don't consider this as a fix to a security vulnerability, but rather as one way of hardening the security defences provided by the framework. The reason for this point of view is the very limited applicability in this case.

The two main reasons for not including an CSRF token in a GET request are to prevent the token from being recorded in the browser history or through a Referer header. Neither of these two concerns apply in this case since the token was only included in internal XHR requests but never in any URL that the user would directly navigate to.

In order to discover the user's CSRF token, an attacker would thus need to gain control over some part of the network infrastructure between the server and the end user. In most such cases, the attacker would then also have access to the actual HTTP payloads in addition to only the requested URLs, thus being able to do lots of other things in addition to CSRF attacks. The most prominent case when requested URLs are available without further access to the payloads if for anyone with read access to the HTTP access logs of the server. The main attack vector is thus limited to insiders.

Even in the quite rare case where an attacker can get hold of some user's CSRF token without getting any further access to request payloads, various aspects of the way the framework manages the communication between the server and client still makes it quite tricky to perform a conventional CSRF attack.

Furthermore, the GET request that might expose the token is only sent by applications that use server push.

**Comment by tsuoanttila** [comment]
Fix for this issue was picked to 8.0.6
