### ISSUE TITLE
setEditable(false) on a grid column without editor binding throws Exception

### ISSUE THREAD

**Issue by azaberlin** [vaadin/framework#8718]
Hi,

I'm using Vaadin 8.0.0 and I want to disable editing for a grid column that shows a button in non edit mode, since by use tab the focus always land in that column / cell, too. 

When calling **com.vaadin.ui.Grid.Column.setEditable(false)**, a NullPointerException shows up:

> ...
> Caused by: 
> java.lang.NullPointerException: Column has no editor binding or component defined
> 	at java.util.Objects.requireNonNull(Objects.java:228)
> 	at com.vaadin.ui.Grid$Column.setEditable(Grid.java:1622)
>         ...

Since I want to DISABLE the editing for this column, it makes no sense for creating a binding first, so please fix the binding check for the case that one wants to ENABLE the editing for this column

Regards

PS: Here is the calling code snippet
`grid.addColumn(r -> "Delete", new ButtonRenderer<>(e -> { 
	// removing items and so on
})).setEditable(false);`

**Comment by TatuLund** [comment]
This behavior is intentional as can be seen in Grid's code

https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/Grid.java#L1956

Alternative approach would be to throw IllegalStateException. However the custom error message is given and it gives clear indication what should be done.
