### ISSUE TITLE
ComboBox doesn't allow a separate description so render html entities or be vulnerable to Javascript Injection

### ISSUE THREAD

**Issue by xenoterracide** [vaadin/framework#8731]
using vaadin 7.7.6
using example https://vaadin.com/docs/-/part/framework/components/components-combobox.html but with malicious text that assumes humans are adding the planet names via a form.

```
// List of planets
List<Planet> planets = new ArrayList<>();
planets.add(new Planet(1, "<iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1&rel=0" frameborder="0" allowfullscreen></iframe>"));


ComboBox<Planet> select =
    new ComboBox<>("Select or Add a Planet");
select.setItems(planets);
select.setDescription(""); // doesn't do anything
````

the combobox will "rick roll" you, or you can input  `<div onmouseenter="alert('hello')">:Goog</div>`, and get the hello alert. Obviously these are both innocuous, but more dangerous exploits could be written. If you encode it first converting `<` to `&lt;` then the list itself will have the ugly `&lt;` which isn't what you want to show for `<E> Corp` (Mr. Robot :D). The best way to fix this issue is to have an `ItemDescriptionGenerator` to allow a separate tooltip to be generated from the contents of the list.

**Comment by xenoterracide** [comment]
alse see #8310

**Comment by Legioth** [comment]
Slightly related to #2132 about allowing ComboBox items to be interpreted as HTML.

I think this was kind-of fixed in Framework 8 since all tooltips should now by be rendered as plain text (and if not, then that's a specific bug that should be fixed asap), which means that the item and the tooltip will be rendered in the same way.

**Comment by xenoterracide** [comment]
This vulnerability still exists in 7.7.9

**Comment by ilatypov** [comment]
The argument of the ``planets.add`` statement contains an iframe bringing up a Youtube video.  This does not agree with the ``div`` tag referred to by the description.  I failed to reproduce this at demo.vaadin.com, and I guess this is because the demo site runs the latest version (major number 8) of the product.

**Comment by xenoterracide** [comment]
> does not agree with the div tag referred to by the description.

ah sorry about that, I must have forgot to update the description when I decided to use the iframe, however, both strings could be inserted at that position and then would show up in that text. However, I am not sure if this impacts v8, it sounds like it doesn't but I haven't tested that.

**Comment by tyrel** [comment]
Why is this known vulnerability still just sitting here open, not even targeted?

**Comment by Legioth** [comment]
Seems like I read this ticket description carelessly the last time around and assumed that this was an inconsistency related to tooltips, which is apparently not the case since `ComboBox` doesn't show tooltips for individual items.

I wasn't able to reproduce any kind of vulnerability with variations of the code shown in this ticket or in the referred documentation. All I managed to achieve was an ugly popup: <img width="1189" alt="screen shot 2017-07-13 at 14 32 52" src="https://user-images.githubusercontent.com/1294657/28164514-66c010ea-67d8-11e7-87df-a1b3655ba93f.png">

The regular item description that is shown in the popup is escaped in [Framework 8](https://github.com/vaadin/framework/blob/master/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L151) and [Framework 7](https://github.com/vaadin/framework/blob/7.7/client/src/main/java/com/vaadin/client/ui/VFilterSelect.java#L147). There might of course still be some other part of the code that causes something similar, but nothing that was obvious from looking at the component's implementation.

Could it e.g. be that some part of the application also e.g. uses the selected item description to update a `Label` with `ContentMode.HTML` or to set the value as the tooltip of some component using `setDescription(String)`?

Could someone share a full code example that actually causes a `ComboBox` item description to be interpreted as HTML?

I would furthermore like to point out that the original description is invalid: it refers to Vaadin Framework 7.7.6, but the `ComboBox` class in that version doesn't have any type parameter and doesn't have a `setItems` method. Both those features were used in the example code but weren't introduced until 8.0.

**Comment by xenoterracide** [comment]
so... after working through to produce a full example, yes no `setItems` this is more or less what we're doing... except we're doing it through convoluted subclasses. This may not be a vulnerability (well any more than most of vaadin's descriptions supporting unsafe tooltips has been, and the only way to make this safe is to sanitize it ourselves

```
@SpringBootApplication
public class Application {


    public static void main( final String... args ) {
        SpringApplication.run( Application.class, args );
    }

    public static class Planet {
        private final long id;
        private final String name;

        public Planet( final long id, final String name ) {
            this.id = id;
            this.name = name;
        }

        public String getName() {
            return name;
        }

        public long getId() {
            return id;
        }
    }

    @SpringUI
    @Theme( "reindeer" )
    public static class VaadinUI extends UI {

        private static final long serialVersionUID = -7843692311814677343L;

        @Override
        protected void init( VaadinRequest request ) {

            List<Planet> planets = Arrays.asList(
                    new Planet( 1, "<script>alert('hello')</script>" ),
                    new Planet( 2, "<a href=\"\" onmouseenter=\"alert('hello')\"/>hello</a>" )
            );

            BeanContainer<Object, Planet> container = new BeanContainer<>( Planet.class );
            container.setBeanIdProperty( "id" );
            container.addAll( planets );

            ComboBox comboBox = new ComboBox();
            comboBox.setWidth( 100, Unit.PIXELS );
            comboBox.setImmediate( true );
            comboBox.setEnabled( true );
            comboBox.setItemCaptionMode( AbstractSelect.ItemCaptionMode.PROPERTY );
            comboBox.setItemCaptionPropertyId( "name" );
            comboBox.setContainerDataSource( container );
            comboBox.addValueChangeListener( event -> {
                long id = (long) event.getProperty().getValue();
                setDescription( comboBox.getItemCaption( id ) );
            });
            setContent( comboBox );
        }
    }
}
```

**Comment by Legioth** [comment]
`setDescription` is  [explicitly documented](https://vaadin.com/api/7.7.10/com/vaadin/ui/AbstractComponent.html#setDescription-java.lang.String-) to treat the contents as HTML instead of plain text in Vaadin Framework 7.x. The original reason for this potentially unsafe approach is that the tooltip is expected to contain formatted text that is part of the application's implementation. We have since then realized that developers will occasionally also show user-provided data in tooltips without proper escaping.

Starting from version 8.0, the default has been changed so that `setDescription(String)` automatically escapes the contents. We won't introduce this change in the 7.x series since that would break applications that use application-provided formatted contents in tooltips.

In this case, you can thus update to 8.x or explicitly escape the value passed to `setDescription` in the value change handler. When using Spring, there's a handy `org.springframework.web.util.HtmlUtils.htmlEscape` method that you can use, e.g. `setDescription( HtmlUtils.htmlEscape( comboBox.getItemCaption( id ) ) );`.

For those not using Spring, there are also similar helpers in e.g. Apache Commons and Guava. The JSoup library that is bundled with the framework also provides `Jsoup.clean()` that removes any dangerous HTML instead of escaping it.
