### ISSUE TITLE
Grid (v8) RendererClickEvent getRelativeX() and getRelativeY() always returns -1

### ISSUE THREAD

**Issue by ghost** [vaadin/framework#8797]
When using a Grid (v8) with ButtonRenderer, the RendererClickEvent methods getRelativeX() and getRelativeY() always return -1.
It is therefore not possible to compute the position of the button.

**Comment by Artur-** [comment]
Which element would you expect the coordinates to be relative to, the clicked element (i.e. the button in this case) or the cell in the grid? What are you looking to use the relative coordinates for?

**Comment by bc15** [comment]
We have a existing implementation of a button in Table to Grid, which opens a Window in order to present a list of options available to the user. The window opens right beneath the button.
With current information from RendererClickEvent  I can only get the position where the mouse click occured, not the absolute position of the button.

But I have seen that with vaadin 8.1 it will be possible to render components in Grid, so I think I will wait for that feature.
