### ISSUE TITLE
AbstractCompontent should support setting width and height with SizeWithUnit

### ISSUE THREAD

**Issue by bjung82** [vaadin/framework#8807]
SizeWithUnit is a nice little helper (especially the parse functionality).
There is no sensible reason why it is not directly supported in the API of components ;-)

**Comment by Legioth** [comment]
There is one reason, but I'm not sure it is "sensible": API bloat.

What is the use case for exposing this method? You can already get indirect access to the same parse functionality simply by using e.g. `someComponent.setHeight("15px");`.

**Comment by bjung82** [comment]
We have an internal legacy UI framework that is used by our developers. The developers can specify something like "15px", "15", "100%". Our task is adapting this framework to vaadin. Therefore we get the info from the existing layer, parse it using "SizeWithUnit" and generate nice Vaadin Layouts :-) In this generation we calculate a lot with the SizeWithUnit, and if we are finished we want to set the sizes into the Vaadin components. It's no problem to use e.g. setWidth(sizeWithUnit.getSize(), sizeWithUnit.getUnit()).

It just doesn't look as nice as it could be if the components could understand SizeWithUnit directly.

Of course it would be some kind of bloat.. that depends on your perspective ;-)

**Comment by Legioth** [comment]
I'm not completely sure I understand your case. `15px` and `100%` are already supported by `setWidth(String)`, but `15` isn't supported since there is no unit.

Are you using either of these options or some completely different pattern?
1. Your own parsing that runs `SizeWithUnit(float size, Unit unit)` based on that
2. Transforming `15` into some other string and using `SizeWithUnit.parseStringSize(String s)`
3. Passing the value directly to `SizeWithUnit.parseStringSize(String s, Unit defaultUnit)` with a `defaultUnit` of your choice

**Comment by bjung82** [comment]
Hi,

we use option all three options. Sorry, I didn't want to complicate things ;-)

If adding the setWidth(SizeWithUnit) and setHeight(SizeWithUnit) to AbstractComonent adds too much bloat to the API, I can live with the current state. In this case simply close the issue.

Regards
Benni

**Comment by Legioth** [comment]
Those additions would by themselves probably not be "too much" on the bloat scale, but it's a slippery slope.

It seems like your kind of case is quite rare and you already have a fully workable workaround, although you have to write some extra code, so let's stick to the two overloads that are already there.
