### ISSUE TITLE
Valo FORMLAYOUT_LIGHT style does not apply to nested fields

### ISSUE THREAD

**Issue by robinsonmark** [vaadin/framework#8837]
If you nest fields within a HorizontalLayout or CssLayout so that they are on the same row the ValoTheme.FORMLAYOUT_LIGHT style does not apply to the fields.

**Vaadin version**

8.0.2

**Example code**

```java
FormLayout form = new FormLayout();
form.addStyleName(ValoTheme.FORMLAYOUT_LIGHT);

HorizontalLayout l = new HorizontalLayout();
l.setCaption("time");
l.addComponents(new ComboBox<Integer>(), new ComboBox<Integer>());
form.addComponent(l);

```
**Output**

![original](https://cloud.githubusercontent.com/assets/8914481/23895108/93319298-089c-11e7-9abf-b6bfd7f77335.png)

**Fix**

Update the `valo-formlayout-light-style` mixin so that the line:
`> table > tbody > [class*="row"] > [class*="contentcell"]` 
becomes
`> table > tbody > [class*="row"] > [class*="contentcell"], > table > tbody > [class*="row"] > [class*="contentcell"] > [class*="v-layout"] > [class*="v-slot"]`

**Fixed output**

![after](https://cloud.githubusercontent.com/assets/8914481/23895229/f92f6fd4-089c-11e7-92a3-83c284934abe.png)

**Comment by carlislefox** [comment]
This would be _really_ nice to have out of the box.

**Comment by pleku** [comment]
Adding this to the existing style would be a change in the look of existing apps, so this cannot be introduced in a maintenance version, but at least on a minor update.

Another option would be to just add another style that applies the rules also for nested layout slots.

ping @jouni

**Comment by jouni** [comment]
Thanks for the report – sorry about forgetting this kind of a simple use case when implementing Valo originally!

I agree with Pekka, that we should avoid causing any breaking changes. So maybe the best option is to add the "light" style for other layouts as well, so that it modifies the contained components like the form layout does.

Or, maybe even better, have the light style per component instead, not coupled to any layout.
