### ISSUE TITLE
Allow using HTML in Grid cell tooltips

### ISSUE THREAD

**Issue by johannesh2** [vaadin/framework#8853]
It seems that it is not possible use HTML in Grid cell tooltips anymore. Could you please make it possible to configure cell tooltips to allow HTML content.

**Comment by bjung82** [comment]
There is a workaround for this: Use a custom connector for a  custom grid (needs own subclass to be able to use own connector). In this connector overwrite getTooltipInfo like this:

      @Override
	public TooltipInfo getTooltipInfo(Element element) {
		TooltipInfo tt = super.getTooltipInfo(element);
		if (tt != null){
			tt.setContentMode(ContentMode.HTML);
		}
		return tt;
	}

This solved the issue for us :-)

**Comment by brunojcm** [comment]
I just found this issue, after migrating an application from Vaadin 7 to Vaadin 8.

To be honest, I'm kind of disappointed in finding such a basic issue like that. I think it should be considered a regression and not a feature, as an app that relies on this is pretty broken right after migration.

Probably forking Vaadin to apply this workaround, I would be harder to change the reference to an extension of the Grid in tens of classes.

I'll try to provide a PR, if you're willing to apply such a patch.

**Comment by brunojcm** [comment]
@torok-peter and @tsuoanttila I cannot find this new method in `com.vaadin.v7.ui.Grid`.. Is it expected? I need either this method, so I can set ContentMode.HTML, or all v7 Grids working always in HTML mode, as they were in Vaadin 7.

My migrated app is still broken without it :(

**Comment by Legioth** [comment]
@brunojcm The changed behavior of `com.vaadin.v7.ui.Grid` compared to Vaadin 7 is indeed a regression.

At the same time, this implementation has been in `com.vaadin.v7.ui.Grid` for over 10 months already, which means that there's a significant risk that there are applications out there that are counting on the new behavior. Changing back would have been quite OK within a couple of weeks after 8.0.0, but the situation is quite different at this point in time.

The only option that would be risk free from that perspective would be to make the behavior configurable also for `com.vaadin.v7.ui.Grid`. The problem here is that we're then making it much more complex to keep `com.vaadin.v7.ui.Grid` consistent with the implementation from Vaadin 7.

All in all, this means that there are no good options for how to handle this case.

**Comment by brunojcm** [comment]
@Legioth Yes, I agree, but if it's a regression, I think the least worse option is to fix it, even though the bug is there for 10 months.. I don't think not fixing a bug because there are people relying on that bug is reasonable.

Another point worth mentioning is that no one should be creating "new" grids using the v7, so it's unlikely that someone (1) has created a new Grid using the v7 Grid and (2) is relying on the new preformatted behaviour.

Either way, we should do something. My app is broken since day 0 I migrated it to Vaadin 8, I have tens of Grids and I don't know what to do; if I refactor my code to use the preformatted (which wouldn't completely fit my needs, as I have some bold and italic on my tooltips) or if I keep waiting for a position from Vaadin team on this. Unfortunatelly, using the v8 Grid is not an option now because it still lacks some features from v7 Grid, like start editing a row by id.

PS.: About your option to make de v7 Grid also configurable: even if we do that, we still need to decide what's the default setting, and I think it should be HTML. I know many users have migrated already, but we have much more to come. I don't think it's acceptable to have them to change that configuration for each grid when v7 compatbility layer is supposed to be a drop-in replacement.

**Comment by Legioth** [comment]
One person's regression is another person's convenient feature. It doesn't have to be a new Grid, it can just as well be an old migrated view that someone has made one small enhancement to. 

It would be very bad if we willingly make changes that introduce security holes into our users' applications. With a community of over 150 000 developers, an unlikely 0.1% scenario means that 150 developers would be affected.

It might still be good enough to simply change the default in a minor update and make a really clear mention of the change in the release notes. But even with 99% of all users reading the release notes before upgrading, 1 or 2 developers out of the theoretically 150 affected would still miss the notice and end up with a vulnerable application. That's why I'm hesitant to changing the default at this point.

One alternative option specifically for anyone in the same situation as @brunojcm could be to include a locally patched Grid implementation in your widgetset. The changes needed to the code are quite minimal: https://github.com/vaadin/framework/pull/10389/files.

**Comment by brunojcm** [comment]
@legioth

So... Regressions are allowed, as long as they are convenient enough to someone?

Look at what you're saying: someone (that is by now a hypothetical one) that has inadvertently implemented a small enhancement over a compatibility layer in a wrong way, against what the v7 Grid documentation states, has more importance than myself, a legit real paying customer, complaining about an acknowledged regression defect. Is that it?

You must know that better than me: despite the 8 months passed, we have much more users still to migrate from 7 to 8 than users that have already migrated. My company as a example, I'm the first one to migrate an app and document the path and change our internal libraries so others can follow. And it's 4 months already and I cannot give a green light to the other projects, this issue being one of the reasons.

So, just to confirm so I can take an action here: official Vaadin tram position is that, even though the issue is acknowledged, it won't be fixed. You also refuse to implement a method to fallback to the old, proper, expected for a drop-in replacement behaviour, so my only to options are:
1. Fork Vaadin (as I am not able to extend a Grid in all cases I have) 
2. Change all my Grids to pre-formatted (and trust you will not end up fixing this properly and breaking my code again) 

Please, advise.

**Comment by Legioth** [comment]
@brunojcm 

The key aspect here is that fixing this regression has a nontrivial risk of causing **security vulnerabilities**. The security implications contribute to a significant shift in the balance between fixing a regression and leaving it there to avoid further surprises. Convenience of the new behavior doesn't by itself doesn't affect this balance, but it's a significant factor in determining the likelihood of the security risk.

As an example of an issue that was fixed despite the potential for breaking things for users that were relying on that defect, see e.g. https://github.com/vaadin/framework/issues/5650 and the follow-ups in at least https://github.com/vaadin/framework/issues/6963, https://github.com/vaadin/framework/issues/5880 and https://github.com/vaadin/framework/issues/5749.

I believe that the best course of action here would be that we backport the feature for configuring the content mode to Vaadin 7, and through that also introduce the feature to the `com.vaadin.v7.ui.Grid` version in 8. We should still preserve the current default setting of `com.vaadin.v7.ui.Grid` to avoid any security issues, but then also update the migration guide to highlight that it might be necessary to make a manual change for this case.

**Comment by brunojcm** [comment]
@legioth

If there is a security risk involved, then everything changes. I was not aware of it, sorry if I missed something.

If you are willing to also implement the configuration in the v7 Grid on Vaadin 8 and state this step on the migration guide, I find it perfectly acceptable, as it seems a legit way to fix the issue and clear the migration path to future Vaadin users.

Can I expect that to be ready for Vaadin 8.2? I'm more than willing to help you with anything to achieve that, as my second option is to fork Vaadin to do the same thing, basically.

Please, let me know if I can help. 

Cheers

**Comment by Legioth** [comment]
Unexpectedly rendering contents as HTML instead of plain text can lead to XSS vulnerabilities if user-provided data is included in a tooltip. The circumstances that lead to that scenario are quite unlikely in this case, but it cannot be ruled out.

I'm afraid we're slightly too late for 8.2. On the other hand, we're moving to a fixed schedule with minor updates to the 8.x series. 8.3 should be out already by the end of January 2018 and alphas can be released whenever appropriate.

**Comment by brunojcm** [comment]
@legioth, that's sad, I was hoping that for 8.2, as it seems a simple fix.
Should I create a new issue to track this request, as this one is closed?

**Comment by Legioth** [comment]
I already created a pull request: https://github.com/vaadin/framework/pull/10396

**Comment by brunojcm** [comment]
@Legioth, what about 8.3? We have betas already and it's still not merged.
