### ISSUE TITLE
JsonCodec doesn't allow to extends the logic.

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/framework#8875]
`JsonCodec` contains the method `encode` which serializes the object to Json.
The issue is: it's not extendable.

There is a customer request (from the support) to get a way to inject somehow a custom serializer so that the logic can be extended. But it's not possible to do with the current approach.

There is a static field which already contains something like this (`customSerializers`) but it's internal and it's not possible to inject anything there.

There should be a way to plug a custom logic into `JsonCodec` (doesn't matter which way exactly) so a custom serializer would be used in case it's added.

It looks like there is a way to do similar thing on the client side already.

**Comment by hesara** [comment]
"Injecting" a custom serializer should happen simply by defining a class that implements JSONSerializer, which is picked up by the GWT generator (see ConnectorBundle.findCustomSerializers()). See also Type.findSerializer() and TypeDateStore.findSerializer(Type) whose implementations are created by the GWT generator IIRC. Unfortunately, this feature seems to be almost completely undocumented.

**Comment by Legioth** [comment]
The `customSerializers ` field was introduced with the intention that there would some day be a proper API for customizing the serialization logic, even though there wasn't any specific known case for it at that time.

**Comment by croesch** [comment]
I'm a member of the customer organization requesting this customer serializer injection.

Our use case:

We have a `List<Superclass>` which contains either `Subclass1` or `Subclass2` (maybe 3-x later). Instead of serializing each entry itself Vaadin's serialization uses the `Superclass` to serialize the subclasses. Thus a lot of necessary information gets lost.

We currently use a custom Object/List which wraps `Map<ID, Subclass1>`, `Map<ID, Subclass2>` and a `List<ID>` to rebuild the original list after deserialization. But we would like to use a custom serializer to address this and serialize the list with all type information we need.
