### ISSUE TITLE
Clean up DropEvent and DragEndEvent properties

### ISSUE THREAD

**Issue by pleku** [vaadin/framework#8895]
- The DropEvent should not have the _dropEffect_ parameter at all, since it is reliably reporting the actual effect on drop.
- The DragEventEvent should have the _dropEffect_ parameter, since that is where it is reported on
- The DragEventEvent should not have the _effectAllowed_ parameter, since it makes no sense

**Comment by wbadam** [comment]
The spec of the above can be found here https://html.spec.whatwg.org/multipage/interaction.html#dndevents

According to spec, `drop` _should_ have the current drag operation and allowed effects, but Chrome thinks it otherwise. In Chrome, `dropEffect` is always `"none"`, while `effectAllowed` contains the actual effect.

Will test with other browsers to decide if it should be removed or should be made consistent.
