### ISSUE TITLE
Verify that ContextMenu works with TreeGrid

### ISSUE THREAD

**Issue by pleku** [vaadin/framework#8968]
It should be possible to use the ContextMenu add-on with TreeGrid. This needs to be verified, since the event handling has been modified in TreeGrid.

If there is any specific API that should be different from the `GridContextMenu`, then a `TreeGridContextMenu` could be added.

**Comment by sebastianfilke** [comment]
Is the ConextMenu working. Does someone verified it?

**Comment by beirtipol** [comment]
I can verify it doesn't seem to work with vaadin 8

**Comment by beirtipol** [comment]
Debugging in, it seems that the context menu is being created, and the event fires, but once it gets to:

GridContextMenu.open(int x, int y) it gets a handle to the proxy and calls 'showContextMenu' on it, but nothing appears.

```
    public void open(int x, int y) {
        getRpcProxy(ContextMenuClientRpc.class).showContextMenu(x, y);
    }
```

**Comment by beirtipol** [comment]
Going even deeper.... but I may have gone in the wrong direction as I'm hitting client vs server issues

It looks like 'ContextMenuConnector.init()' is never called. If I manually try and invoke the 'ContextMenuConnector' to get it to initialize, I get this error:

`java.lang.ClassNotFoundException: com.vaadin.client.extensions.AbstractExtensionConnector`

So, I added vaadin-client to my pom and then I got this error:
```
java.lang.UnsatisfiedLinkError: com.google.gwt.core.client.JavaScriptObject.createObject()Lcom/google/gwt/core/client/JavaScriptObject;
	at com.google.gwt.core.client.JavaScriptObject.createObject(Native Method) ~[gwt-user-2.8.1.jar:na]
	at com.vaadin.client.FastStringMap.create(FastStringMap.java:72) ~[vaadin-client-8.1.2.jar:8.1.2]
	at com.vaadin.client.ui.AbstractConnector.<init>(AbstractConnector.java:78) ~[vaadin-client-8.1.2.jar:8.1.2]
	at com.vaadin.client.extensions.AbstractExtensionConnector.<init>(AbstractExtensionConnector.java:28) ~[vaadin-client-8.1.2.jar:8.1.2]
	at com.vaadin.contextmenu.client.ContextMenuConnector.<init>(ContextMenuConnector.java:25) ~[vaadin-context-menu-2.0.0.jar:2.0.0]
```

I've dropped the reference to the ContextMenuConnector, but I'm still not clear how the RPC call is supposed to get registered so that the 'showConextMenu' actually gets invoked

**Comment by TatuLund** [comment]
Based on https://github.com/vaadin/framework/issues/9606 ContextMenu works with TreeGrid. It was not working with Tree prior to Vaadin 8.1.
