### ISSUE TITLE
FileDownloader: add listener for started, succeed, finished events 

### ISSUE THREAD

**Issue by anasmi** [vaadin/framework#8970]
Now it's not possible to execute any action right after downloading is finished.
The idea behind is that 
"it would be great if there was an event that filedownloader would fire after it finishes whatever it was doing
So I could put business logic somewhere other than get stream"

**Comment by Legioth** [comment]
It's not feasible to do this through `FileDownloader` – it has no way of knowing about when the browser is done downloading a resource. It could fire an event when the user interacts with the target (e.g. the Button) so that the download is first triggered, but there's no guarantee that the download actually starts. The browser might just as well block the download for some reason or just open a dialog for choosing where to download the file, and the user could then cancel that dialog.

Another approach to this would be to connect this to the processing of `ConnectorResource`, regardless of whether that resource is used together with `FileDownloader` or any other mechanism that uses resources, e.g. `Image`.

**Comment by ChirpChirp** [comment]
I do not need to determine whether file actually finishes downloading or not. 

It's not really good from the perspective of keeping things asynchronous.

But I do need to know when FileReference has obtained a stream, and finished all the server-side work. Then I would like to remove it from screen.

**Comment by denis-anisimov** [comment]
> I do not need to determine whether file actually finishes downloading or not.
I think you actually need.

The issue is that you can't be sure that once the method `getStream()` is called the download will succeed. And you can't even know when download starts because `getStream()` has no relation to the real data reading process. So there can happen a lot of things in between getting the stream and real data fetching. Is it OK for you ?

Now several observations:
- FileDownloader is just a _client side_ extension. Which _doesn't do any server roundtrip at all by itself_. This is important to understand. This is what Leif said above. It accepts a `Resource` which can be any resource e.g. an `ExternalResource` like "http://google.com". And framework cannot control any communication between external server and user's browser.
- It means that there is no any logical reason to extend API for `FileDownloader` itself. It just has no sense.
- If you want to know when something happens with the "link" which downloader is attached to then you can use e.g. a `Button` and just add a click listener to it. But the events (download starting and click) will be totally unrelated to  each other. They will be async as you want but is it really something you want ?
- We can add some listeners to `ConnectorResource` or `DownloadStream` classes. So their API can be extended instead of `FileDownloader`. This is what you really need since your resource is some server side stream resource. And again this is what Leif was talking about.
- If you don't want to care about real resource data reading (and keep it asynchronous) then I don't see any issue with that right now: just override `getStream()` method of the `StreamResource` class. But I've already mentioned above: real data reading doesn't correlate with this method call.
- It's very weird API to fire event when `getStream()` or whatever `get` is called. I doubt we will do it ever (moreover it's possible to do it as I mentioned already without any big effort). 
- If you want to know when data is finally read then the method `close()` in the input stream is what you need. Just override it. It won't be asynchronous. But again: should it be ? There is no any other way to understand that data is completely read. And without this you can't be sure that download has been successfully finished.
- As I said : we can implement API on the top of `ConnectorResource` or `DownloadStream` but it will be the similar implementation of the same things that you can do by yourself just overriding either `close()` method or `read()` ( to know that you have read the very first chunk of the data). It won't be asynchronous. But I don't think it should be.

In the end: 
- if you don't want to know whether the resource has been really downloaded or not then just override `getStream()` method and add your custom logic there. I'm pretty sure that we don't want this functionality in the framework. But please be aware that it won't guarantee that the resource will be downloaded at all (even download will be started).
- override `read()` ( to know that download has been started when the very fist chunk of the data is requested). But you can't be sure that download will be completed.
- override `close()`  method to make sure that download has been completed.
- The last two feature can be done in the framework, but : it's not a part of FileDownloader , it's not asynchronous and it can be done in your custom logic as well (and almost in the same way as it would be done in the framework).

Please let us know which way you really want to get it done.
Thanks.

**Comment by ChirpChirp** [comment]
So I have reviewed what you said, and I have to admit, I don't completely understand how FileDownloader works inside, but let me describe my use case.

Since previous communication I realized that getStream may not allow for a good error handling, so there is a problem again.

I am implementing registration based on private keys. So login by uploading private key, and sign up by getting private key saved to local folder.

I am trying to implement sign up button. On the click of the button, the server must create new user account, and offer the user the private key to save. I would like that both actions are done with one click.

So,

User clicks the button
Button reports request to the server
Server creates new account, and private key file
If it fails,
it must report back and the button must do nothing
If it succeeds,
It must report back to the button and the user must have file saving dialog open.
After saving file dialog is open, the button must be removed from the screen.

At the moment I don't know how to use getStream to handle failure case. I still feel like there got to be a better way to do it, and I strongly suspect I need a custom component for this. Please let me know if I am wrong.

**Comment by Legioth** [comment]
Web browsers try to protect users against [drive-by download](https://en.wikipedia.org/wiki/Drive-by_download) attacks: the browser will be suspicious of any download that is started by any other action than a direct click by the user.

This makes things tricky for the registration workflow that you want to implement since the download would then be started by the confirmation message received from the server instead of a direct user interaction.

I can come up with three different alternatives, each with some trade-offs:
1.  Change the interaction design so that the button creates the account, and then shows a confirmation message and a link for downloading the private key. The drawback here is that two clicks will be required, but the benefit is that it might be easier for the user to understand that a file is actually downloaded.
2. Let the browser send the download request immediately when the button is clicked (i.e. using `FileDownloader`), and then terminate the HTTP response e.g. by throwing an exception from some suitable place if the account couldn't be created. The drawback here is that the terminated response will show up as an error in the browser.
3. Try to trigger the download from the server after account creation has succeeded, but also show a message with something like "If the download doesn't start automatically, click here" with a link to the same private key file. To (try to) start the download when the account has been created, you can use the deprecated `Page.open(Resource, String, boolean)` method with the string set to `"_self"` and the boolean as `false`.
