### ISSUE TITLE
Important piece of Information missing in JavaDoc for refreshing all data of a Grid

### ISSUE THREAD

**Issue by Sharknoon** [vaadin/framework#8971]
Hello,
My Vaadin Version is 8.0.4.
Bug Description:
The method `refreshAll()` of the Interface `DataProvider<T, F>` is missing the important Information, that the items of the Grid must implement either `equals()` or `hashCode()` or the `getID(Object)` method in order to work properly.
![refreshall](https://cloud.githubusercontent.com/assets/16149608/24475029/f3a940ba-14ce-11e7-8925-b219cb495c41.png)

The method `refreshItem(T item)` contains this information, which is neccesary to work.
![refreshitem](https://cloud.githubusercontent.com/assets/16149608/24475030/f3b303a2-14ce-11e7-8ea4-289864f566c0.png)

Please add the same Informations to the method `refreshAll()`, so that new users, who want to use only this method know, what they have to implement to their bean in order to function.
![newrefreshall](https://cloud.githubusercontent.com/assets/16149608/24475668/f70ea6c6-14d0-11e7-880b-63969416013d.png)

Thank you very much for this great Framework!
Kind regards from Germany
Josua Frank aka Sharknoon

**Comment by Legioth** [comment]
I haven't tested this in practice, but I do believe that proper `equals` and `hashCode` implementations shouldn't be necessary for `refreshAll()`. `refrehsItem(T item)` needs those in order to identify the old item that should be replaced or refreshed, but it shouldn't be necessary for `refreshAll()` which simply discards all previous data and continues from a completely clean state.

If things for some reason doesn't work in that way, then I'd consider that a bug in the implementation instead of an omission in the documentation.
