### ISSUE TITLE
Valo Theme Primary button style has custom padding

### ISSUE THREAD

**Issue by taurus227** [vaadin/framework#8988]
I'm using two buttons of the same size, one above other, one is "friendly", the other "primary".
I tried to left-align the icon and text on both, but they don't align perfectly:

![screenshot](https://cloud.githubusercontent.com/assets/5892152/24558256/13b54c6a-166d-11e7-9cf8-52a82935897d.png)

By looking at the valo theme source, I found that "primary" buttons have a custom padding that is calculated differently from all other buttons:
[_button.scss line 19](https://github.com/vaadin/sass-compiler/blob/master/src/test/resources/vaadin-themes/scss/valo/components/_button.scss#L19)
```
.#{$primary-stylename}-primary {
  ...
  $padding-width: round($v-unit-size/2);
  padding: 0 $padding-width;
  ...
}
```
overrides
[_button.scss line 220](https://github.com/vaadin/sass-compiler/blob/master/src/test/resources/vaadin-themes/scss/valo/components/_button.scss#L220)
```
@mixin valo-button-style (...) {
  ...
  padding: 0 round($unit-size/2.4) + round($border-radius/3);
  ...
}
```
I found the solution, added this in my main mixin:
```
  .v-button-primary {
    padding: 0 round($v-unit-size/2.4) + round($v-border-radius/3);
  }
```
But it looks like this is a bug and the padding should be consistent across all styles.

**Comment by jouni** [comment]
Hi! Thanks for raising this issue and providing the PR.

I admit that having different padding for the primary button was not the right way to go. I think I was trying to compensate for the usual “OK / Cancel” button case, where the OK button would otherwise be a smaller click target than the cancel button. B

That said, I would not change the default styles at this point, because it would be a somewhat breaking change probably for many users. 

Do you consider it unacceptable to workaround the issue in a custom theme, by adding your own stylename to which you apply the primary button color?
