### ISSUE TITLE
Change the <init>(String caption[, ...]) constructors of all Components to <init>(Object caption[, ...])

### ISSUE THREAD

**Issue by gerib** [vaadin/framework#9044]
I'd like to propose this as an enhancement.

### Why? ###

I'm using the following idiom for i18n:

#### Enum PersonText ####
```java
    public enum PersonText {
      FIRST_NAME,
      LAST_NAME,
      //...
      SAVE,
      SAVE_TIP;
      //...
    
      private static final ResourceBundle resourceBundle =
          ResourceBundle.getBundle( "my.app.ui.texts.PersonView", Locale.getDefault(),
              new ResourceBundle.Control() {
                @Override
                public long getTimeToLive( final String baseName, final Locale locale ) {
                  return TTL_NO_EXPIRATION_CONTROL;
                }
              } );
    
      @Override
      public String toString() {
        try {
          return resourceBundle.getString( name() );
        }
        catch ( @SuppressWarnings( "unused" ) final MissingResourceException e ) {
          return String.format( "!%s!", name() );
        }
      }
    }
```
#### Class PersonView ####
```java
    ...
    private final TextField firstName = new TextField( PersonText.FIRST_NAME.toString() );
    private final TextField lastName = new TextField( PersonText.LAST_NAME.toString() );
    ...
```
All the `toString()`s don't make the code clearer, as it would be with:
```java
    ...
    private final TextField firstName = new TextField( PersonText.FIRST_NAME );
    private final TextField lastName = new TextField( PersonText.LAST_NAME );
    ...
```
#### General ####

* Type-safe strings. (This alone would be a good enough reason for me.)
* It conforms to [Jon Postel][2]'s (R.I.P., hero of the old days!) "Be liberal in what you accept, and conservative in what you send".
* Clearer, less cluttered code.
* Any object can be a source for captions.
* ... something I'm not thinking of atm ...

#### Specific for this use case ####

* Automatic caching as per [ResourceBundle Cache Management][1].
* Descriptive fallback values like !FIRST_NAME!. Very helpful while developing, if developers and translators are different persons with different schedules.
* ... something I'm not thinking of atm ...

### How? ###

The implementations of the constructors have just to be changed from:
```java
    public AnyComponent( String caption[, ...] ) {
        ...
        this.caption = caption;
        ...
```
to:
```java
    public AnyComponent( Object caption[, ...] ) {
        ...
        this.caption = caption.toString();
        ...
```
That means, existing code doesn't have to be adapted at all.

  [1]: http://docs.oracle.com/javase/8/docs/api/java/util/ResourceBundle.html
  [2]: https://en.wikipedia.org/wiki/Jon_Postel

**Comment by Knoobie** [comment]
```java
this caption = caption.toString();
```
That's going to throw a NullPointerException in a lot of applications. 

Why not create your own implementation for the components where you need that type of constructor? You can even create your own setCaption() method there to be typesafe.

```java
public I18nEnumTextField extends TextField {

    public I18nEnumTextField(PersonText caption){
          super(caption == null ? null : caption.toString());
    }

    public void setCaption(PersonText caption){
          super.setCaption(caption == null ? null : caption.toString());
    }
}
```

**Comment by gerib** [comment]
> That's going to throw a NullPointerException in a lot of applications.

Are you sure? And if it does, shouldn't it do so anyway? Because, what's the point of passing `null` for `caption` if the intention is most probably to display some meaningful, descriptive text? Such a NPE would gracefully signal that something apparently went wrong in your code.

However, since such a behaviour isn't described in the API we have take this No-NPE as granted.

But, this could be handled in the constructors in the same way you do it in your code samples:

    this.caption == null ? null : caption.toString()

whereby a Java 8-ish approach would be:

    private Optional<Object> caption;

    ...

    this.caption = Optional.of( caption );

However, thank you for the idea of extending the childs of `Component`. I'm going to do it this way since it's probably not foreseeable if this is going to be implemented and if it is, when.

**Comment by Knoobie** [comment]
Normaly ```object.toString() ``` throws a NPE if object is null and that's possible because null is a valid state as Caption. For Example you would remove a caption like this:

```java
   textfield.setCaption(null);
```
See [AbstractComponent.java#L301](https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/AbstractComponent.java#L301) what's going to happen with the given caption in the background. 

Optional could be way to implement that as well! Let's see what the framework team thinks about that when they read that. 

The coloring is done via Markdown Syntax - see [Github Markdown Support](https://guides.github.com/features/mastering-markdown/)

**Comment by gerib** [comment]
[v8.0.5 AbstractComponent#setCaption(String caption)'s API doc][1] doesn't say a single word about `null` behaviour. That means any behaviour is possible and valid. Under such circumstances I'd never pass `null` to a method, even if practice shows that it's OK (now). With this contract there's absolutely no guarantee that this behaviour is still the same the next time you use a higher version – and may it only be an incremental.

There happens not much at line 302: `getState().caption = caption;` is very unlikely to throw a NPE, indeed. ;)

Got the coloring, thanks. They all call it _Markdown_ but they're all different: https://xkcd.com/927/

  [1]: https://vaadin.com/api/8.0.5/com/vaadin/ui/AbstractComponent.html#setCaption-java.lang.String-

**Comment by Legioth** [comment]
Some drawbacks of the proposed change:
* Method overload resolution gets confusing with overly generic signatures. Will `new TextField(foo -> bar(foo))` use `TextField(Object caption)` or `TextField(ValueChangeListener<String> valueChangeListener)`?
* Method signatures wouldn't convey any information about what you're actually supposed to pass there. Once you know it, it might feel obvious that `Object caption` can be anything with a sensible `toString()` implementation, but that's not the case for users who are not familiar with the pattern.
* Why should this be restricted to only `String caption` in constructors? What about `setCaption(String)`? Should we then also change the return type of `getCaption()`? What about other string-typed properties, e.g. `setDescription(String)`.
* What if the `toString()` implementation of the passed `Object` returns different values at different times, e.g. based on `UI.getCurrent().getLocale()`. When should `toString()` be run? Should the framework ever re-run it?
* I'm not sure about the impact on code readability. `PersonText.LAST_NAME.toString()` does more explicitly define what's going on, even though it's slightly longer to type and read.

One intermediate approach that we have been considering from time to time is to use `CharSequence` instead of `String` in cases like this. The main reason for why this is problematic is still that `CharSequence` is a quite inconvenient return type from a getter, and having similarly named setters and getters with different types is problematic in some cases.

**Comment by Legioth** [comment]
> v8.0.5's `AbstractComponent#setCaption(String caption)`'s API doc doesn't say a single word about `null` behaviour.

[Component#setCaption(String caption)][1] has much more descriptive Javadocs that also make promises about `null` support. That description is unfortunately shadowed by Javadocs specific for `AbstractComponent`. I created https://github.com/vaadin/framework/pull/9066 for removing the useless `AbstractComponent` documentation so that the description from `Component` would be more obvious.

[1]: https://vaadin.com/api/8.0.5/com/vaadin/ui/Component.html#setCaption-java.lang.String-

**Comment by Legioth** [comment]
I'll close this issue since I cannot see how it could be implemented without causing lots of confusion with overloaded constructors.

I'll reopen if someone can come up with some idea on how to deal with that.
