### ISSUE TITLE
Converter on ComboBox should use equals() instead of itemCaption

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/framework#9051]
This affects Vaadin version 8.0.5

The convert on the binder for the combobox uses the itemCaption value for selecting the value rather than the isEquals method. This can result in some bad code.

For example I have

```
ComboBox<Vendor> comboBox = new ComboBox<Vendor>(Database.getListOfVendors());
comboBox.setItemCaptionGenerator(Vendor::getName);
```

where Vendor is:
```

public class Vendor
{
	private int id;
	private String name;

	// setters and getters
	
	@Override
	public boolean equals(Object obj)
	{
		// ignore null checks, etc.
		return (Vendor)obj.getId() == id;
	}
}
```

I then bind this with:

```
binder.forField(myForm.vendorComboBox)
	.withConverter(new VendorComboBoxConverter())
        .bind(MyPojo::getVendorID, MyPojo::setVendorID);
```

where VendorComboBoxConverter is:
```

@Override
public Vendor convertToPresentation(Integer id, ValueContext context)
{
	// ignore issues with empty selection for example
	return new Vendor(id);
}
```

Basically in the converter I just want the Binder to be able to select the correct item from the ComboBox by matching the ID. I would assume it would do a check on the equals() method but instead it does a check on the ItemCaption method, which in this case is Vendor.getName(). 

This is very bad for at least two reasons! 

First what happens if I have two vendors with the same itemCaption, in this case the same name? The names should be unique but it is possible that there are two items with the same name depending on how the ItemCaption is generated. I could be using the ItemIcon as a differentiator (for example if the combobox was categories such as utilities, it could be an expense in one case and a revenue in another). It should really be compared on the equals method and not the ItemCaption because if not the comboBox could select the wrong item and lead to further data issues. 

The other main reason is that I may not have the display information in the converter, maybe all I have is the ID number of the data item, which in this case is the Vendor ID. In the current version if I have just the ID I cannot match it with the ID, I have to call the database to get the display name so that I can then match it with the ItemCaption. Instead what should happen is that if the equals matches it will select that item and then just use the item as the display.

**Comment by FollowSteph** [comment]
It's also important to remember that the converter is there because you may not have direct access to the display value at binding time, you may only have access to the display when updating the combobox. In other words in the example above the MyForm class may be for an invoice and when I load the Invoice from the database I may only have the vendor's ID number and not their full information. In other words I have:

```
invoiceComboBox.setItems(Database.getListOfVendors());
Invoice invoice = Database.getInvoice(id);
```

where Invoice only contains the vendorID and not the Vendor's name. 

The only way this code could work is if I kept a reference of the list of vendors and passed that to the Converter, which is not a good idea. And again, what happens if I have two vendors with the same name? And again remember it could be kids in a classroom, etc. In this case if the system only used the vendor's name to match then it would fail.

**Comment by Legioth** [comment]
`ComboBox` in Vaadin Framework 8 doesn't in any case use the item caption for anything else than determining the visual representation (and together with some shorthands for in-memory filtering (`CaptionFilter`)).

When you set items to be used by `ComboBox`, the framework generates an internal identifier for each item, stores the items and identifiers in a `HashMap` and then uses those identifiers in all relevant communication between the client and the server. Values from the caption generator are not used for any part of that process.

You can verify that things work in that way using this code snippet:
```
ComboBox<Integer> comboBox = new ComboBox<>();
comboBox.setItems(1, 2, 3);
comboBox.setItemCaptionGenerator(item -> "Item");

comboBox.addValueChangeListener(event -> addComponent(new Label("Selected " + comboBox.getValue())));

addComponent(comboBox);
addComponent(new Button("Select two", event -> comboBox.setValue(2)));
```

The end result will be a `ComboBox` that displays three `Item` captions. Selecting any item through the browser will add a label with the corresponding number value (i.e. not just the caption). Clicking the button will cause the middle `Item` value to be displayed as selected in the dropdown.

Using `Binder ` with a converter will not change any of this. The result value of `convertToPresentation` will be passed to `ComboBox.setValue` in the same way as in my code example. Correspondingly, the return value of  `getValue` will be passed to `convertToModel`. The converter implementation doesn't even know that it's doing conversion specifically for a `ComboBox` instead of any generic field, so it cannot even know that the target field has an item caption generator.

**Comment by FollowSteph** [comment]
Thank you for the clarification. I did some further analysis and you're correct, it's actually using the hashcode rather than equals to compare items. I'm not sure why but I suspect it's because of how it's stored internally. I would of course recommend using the equals but I can appreciate that in some cases you may need hashcode. Either way I would recommend adding a comment about this in the documentation for anyone wanting to create their own converter because you may just have a stub/mock object and assume the system will use the equals to select the converted item. In other words you may not be working with the same instance or the full dataset.

Thank you for the clarification, this really helped. And I apologize for thinking it was a bug. Great product by the way!!

**Comment by Legioth** [comment]
The implementation is based on  `java.util.HashMap`, which primarily relies on `hashCode` for performance reasons, but falls back to `equals` when multiple items are hashed into the same bucket.

You should always override `hashCode` when overriding `equals` to ensure that objects that are `equals` also give the same `hashCode` value. This is mentioned in the Javadocs of `Object.equals` and `Object.hashCode`: https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#equals-java.lang.Object-. Static code analysis tools such as FindBugs or SonarQube also check for this.

I don't think there's any single location in the framework's documentation where this could be mentioned to cover all potential cases. It would instead have to be added to lots of different locations, which I don't think would be worthwhile since this is a general Java issue and not in any way specific to Vaadin Framework.

**Comment by FollowSteph** [comment]
That's a very good point, you are correct. My mistake and apologies.
