### ISSUE TITLE
Issue with Centering Grid Column Captions

### ISSUE THREAD

**Issue by szaluk** [vaadin/framework#9077]
I am not able to center the Grid column captions.  I have the following CSS:

`.text-align-center { text-align: center; }`

I am setting the style like so:

```
HeaderRow headerRow = countSummaryGrid.getDefaultHeaderRow();

HeaderCell testCycleHeaderCell = headerRow.getCell("Test Cycle");
testCycleHeaderCell.setStyleName("text-align-center");
testCycleHeaderCell.setHtml("<strong>Test Cycle</strong>");
```

The caption is not centering.  However, if I do the following in the footer, it does get centered:

```
FooterRow footerRow = countSummaryGrid.getFooterRow(0);

FooterCell totalsFooterCell = footerRow.getCell("Test Cycle");
totalsFooterCell.setStyleName("text-align-center");
totalsFooterCell.setHtml("<strong>Totals:</strong>");
```

Formatting text in a HeaderCell should work the same way as a FooterCell for consistency.  I can't seem to get the caption in the Header to center at all.

**Comment by Legioth** [comment]
Centering seems to work for me on http://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/features when using the browser inspector to add this CSS:
```
.v-grid-column-header-content {
    text-align: center;
}
```

Some things that you could check out for using the browser's DOM inspector:
* Is there enough room in the header cell for actually aligning the text? There's slightly less space available for the contents in header cells compared to footer cells since some pixels are reserved for the column resize handle and a potential sorting indicator.
* Does the `<th>` element actually get `text-align-center` as part of its `class` attribute value?
* Does your theme contain some other, more specific CSS rule, that overrides the text alignment for headers?

**Comment by szaluk** [comment]
Thanks for the info!

I update the code to the following:

```
        HeaderCell testCycleHeaderCell = headerRow.getCell("Test Cycle");
        testCycleHeaderCell.setStyleName("v-grid-column-header-content");
        testCycleHeaderCell.setHtml("<strong>Test Cycle</strong>");
```

That still is not working.  When I check the DOM, I am not seeing text-align-center added to the class for that element. 

<img width="762" alt="dom" src="https://cloud.githubusercontent.com/assets/2184567/25011017/e601436a-2039-11e7-93a7-82f72fab1936.png">

I am able to center the contents of the cells in the footer and the grid itself, just not the header.

Also, in that link you sent, the headers are showing up as left aligned.

**Comment by Legioth** [comment]
> Also, in that link you sent, the headers are showing up as left aligned.

I used the browser's inspector to add `text-align: center` for the column header. By doing that, I could verify that there doesn't seem to be anything in Grid itself that would prevent column headers from being centered.

Changing your code to set `v-grid-column-header-content` as the style name of the contents of a header may have some unintended side effects since the contents of the header might then get styling that is only intended for the actual header itself.

I'm suspecting that there's something in your application's theme that is interfering with the `.text-align-center` styling. To find out more about this, you can select the header contents in the DOM inspector and then look at what styles are applied for that element ("Styles" in the righthand panel in Chrome). There you can see all CSS selectors that apply for the selected element. If you find your `.text-align-center` stylename there, the `text-align` definition might be striked through, meaning that there is some other style definition that overrides your styles. The other option is that `.text-align-center` is not there at all, if you still see the stylename in the `class` attribute, then this would indicate that your stylesheet is not properly updated or loaded.

**Comment by szaluk** [comment]
@Legioth - When I look in the inspector I do see the style that I added with a strike though:

![style](https://cloud.githubusercontent.com/assets/2184567/25285458/5111c090-2688-11e7-9e0e-7dbd50bf4a49.png)

It seems like the styling in .v-grid-header is overriding what I am setting with text-align-center.  How I can set my styling as higher precedence?  I am calling setStyleName() on the header cell.

Thanks,
Steve

**Comment by Knoobie** [comment]
@szaluk Easiest way would be to add ``!important`` to your style. But you could also change your selector to something like ``.v-grid-header th.text-align-center`` if the style is added to the th, otherwise if it's added to the div below the th, change it to ``.v-grid-header th  div.text-align-center``.

**Comment by szaluk** [comment]
@Knoobie - Adding !important worked.  Thanks!

I do think this should be investigated a bit.  As a user I would expect that adding the same style to a HeaderCell as a FooterCell would result in the same behavior.
