### ISSUE TITLE
Inline icon not displayed in textfield in grid header

### ISSUE THREAD

**Issue by ianscriven** [vaadin/framework#9089]
Using Vaadin 8.0.5, inline icons are not shown in TextFields in Grid header cells.

In the attached project, there are two TextFields, configured the same way to have an inline icon. One is added to a Grid header cell, the other to the main layout. Only the TextField in the main layout shows the icon correctly. The TextField in the grid header cell is indented like an icon should be there, but there is no icon shown.
[gridicontest.zip](https://github.com/vaadin/framework/files/923249/gridicontest.zip)

**Comment by iXo** [comment]
I can confirm that this behaviour is still present in vaadin 8.1.5, surrouding the button with a layout makes it works as expected.

**Comment by TatuLund** [comment]
My earlier assumption that this is related to #10748 and #10752 is not correct. This behavior is independent of those.

Instead this is intentional behavior. When you add TextField to header cell, compact styles are applied (i.e. no caption, no icon inline or normal) The most typical use case of using TextField in header is a filter, and when this feature (possibility add component) was included in Grid, it was not possible to adjust Header height separately from the Body row height. Hence compact styling was needed. As mentioned above you need to wrap the TextField inside  e.g. HorizontalLayout to get normal styles applied. Nowadays it is also possible set header row height separately, which makes possible to have room for Caption if so needed.

The problem is that this behavior is not well documented, and that needs to be corrected.
