### ISSUE TITLE
Download using FileDownloader fails with Chrome / IE11, succeeds with Firefox

### ISSUE THREAD

**Issue by cyrilmhansen** [vaadin/framework#9100]
Using Vaadin 7.7.7, our application use a dynamically generated StreamSource.

Using Chrome, the brower seems to starts the download and immediately display a status 'Network error'.

In the dev console, the request appear in red, and the console contains these errors :+1: 

Refused to display 'http://127.0.0.1:8000/XXX/XXX/.xlsx' in a frame because it set 'X-Frame-Options' to 'deny'.
com.vaadin.DefaultWidgetSet-0.js:2161 GET http://127.0.0.1:8000/XXX/XXXX.xlsx net::ERR_BLOCKED_BY_RESPONSE

With IE 11, the download does not start, I haven't found any error message.

With Firefox the download proceed as expected.

Any clues ?

**Comment by Legioth** [comment]
Might be related to the `X-Frame-Options` error message. The framework isn't setting any such headers, so it might be something that is set as part of your application?

If that is the case, then it might be interesting to see what would happen if you would remove that header. I wouldn't suggest that you permanently remove it since there are good reasons for having it, but it would be good to determine whether it's actually related to this issue.

**Comment by cyrilmhansen** [comment]
Yes indeed, the header was added by default by spring security (I don't use spring-boot). If I add this xml configuration snippet the download is ok with chrome : 

<security:headers>
                       <security:frame-options disabled="true"></security:frame-options>
....
