### ISSUE TITLE
Migration to Vaadin 8 destroys descriptions and description styles

### ISSUE THREAD

**Issue by sebastianfilke** [vaadin/framework#9121]
Vaadin 8.0.5

I am migration to Vaadin 8 with my (not little) application. I have many descriptions which are sometimes html formatted. In Vaadin 7 if you set a description a description was default TEXT formatted. Now with vaadin 8 the default is ContentMode.PREFORMATTED. In this [commit](https://github.com/vaadin/framework/commit/1fb40df8742791803e0a08328028bbbd67deb78b#diff-91c97e48ba26c9da90bf8ebac1641c0f) the default behaviour was changed. But this change affects Vaadin 7 and 8. 

If i only have to change descriptions which should be HTML formatted this would not be a big deal. But now i have to go through all descriptions because the styles are different. PREFORMATTED should not look PREFORMATTED. Otherwise the application has a inconsistency in styling. Please update all description styles so they look all the same. The programmatic behaviour for security could be different.

**HTML:**
![image](https://cloud.githubusercontent.com/assets/10894484/25231780/6aed3a80-25d9-11e7-94f7-673175ff4e09.png)

**PREFORMATTED:**
![image](https://cloud.githubusercontent.com/assets/10894484/25231832/a0a47e86-25d9-11e7-8f23-5e9ec1303480.png)

**TEXT:**
![image](https://cloud.githubusercontent.com/assets/10894484/25231860/bb52b734-25d9-11e7-9459-69f3a1dc8490.png)

**Comment by Legioth** [comment]
The original intention of setting `PREFORMATTED` as the default was that it would then be possible to break the text up into separate paragraphs simply by adding `\n` to the text. Along the way, we did however fail to take into account that this would affect the used font and disable automatic line breaking.

I believe you can do a workaround for this in your own application by adding something like this to the theme:
```
.v-tooltip-text > pre {
    font: inherit;
    white-space: pre-wrap;
}
```

This will have the unfortunate side effect of also affecting any `<pre>` elements inside tooltips set with `ContentMode.HTML`.  If we choose to address this bug by keeping the same default value but adding this CSS to the default themes, we should also add a stylename to the `<pre>` tag that is added for `PREFORMATTED` so that styles can be applied only in that case without affecting `ContentMode.HTML`.

**Comment by sebastianfilke** [comment]
> I believe you can do a workaround for this in your own application by adding something like this to the theme:
> 
> .v-tooltip-text > pre {
>     font: inherit;
>     white-space: pre-wrap;
> }

This works for me as a good workaround. Thank you.

**Comment by sebastianfilke** [comment]
This issue references the following two:
#9120 -> maybe still needed. maybe adresses a designer for scss 
#9119 -> not that important anymore but still usefull
