### ISSUE TITLE
Directory listing possible for the /VAADIN-directory and its subdirectories

### ISSUE THREAD

**Issue by pontusbostrom** [vaadin/framework#9154]
It is possible to remotely list the content of directories in the /VAADIN-directory and its subdirectories. This can be a potential security issue depending on the content. Tested on Vaadin 8.1-SNAPSHOT and 8.0.0 and 7.6.8

**Comment by elmot** [comment]
Please specify your web container and web.xml used. Looks like that is more web container config issue rather than framework issue, and I can not reproduce that with official FW 8 demo.

**Comment by pontusbostrom** [comment]
It seems Vaadin uses a URLConnection to fetch static resources in /VAADIN/. Depending on where the resource is located it uses e.g. a JarURLConnection or a sun.net.www.protocol.file.FileURLConnection. At least sun.net.www.protocol.file.FileURLConnection does directory listings (used in at least on Jetty and it seems on Tomcat too). I have not been able to list directories served from jars.

However, since File#length() for directories is undefined (used in at least sun.net.www.protocol.file.FileURLConnection), this will often not work reliably. The contentLength will be too long and the browser will wait for content that never arrives. "curl" will display whatever it fetched so far, and can be used to show the issue.

**Comment by OlliTietavainenVaadin** [comment]
According to feedback, issue is reproducible on `WebSphere 8.5.5.11` with Vaadin 7.7.13. Web.xml looks as follows: 
![image](https://user-images.githubusercontent.com/15027701/41341909-95c806b2-6f03-11e8-942d-93a40d30a6fa.png)

**Comment by Saranraj-pranion** [comment]
The stated security issue is still prevalent. Is there any updates with regards to this ? My project uses Vaadin 8.0.5 deployed in Jboss EAP 7. Security testing team has found the directory listing of files within /VAADIN/ folder being listed when GET call made. E.g. folders. 

VAADIN\widgetsets
VAADIN\themes\intimationtheme
VAADIN\themes\mytheme
VAADIN\themes\intimationtheme\.sass-cache
VAADIN\themes\intimationtheme\images
VAADIN\themes\intimationtheme\.sass-cache\82edb1c7313ef609fc838939bf9767fa2af950c5
VAADIN\themes\mytheme\.sass-cache
VAADIN\themes\mytheme\images
VAADIN\themes\mytheme\.sass-cache\82edb1c7313ef609fc838939bf9767fa2af950c5
VAADIN\widgetsets\com.alert.util.WidgetSet

The issue occurs both with Chrome and Firefox except that Chrome puts a white page whereas the Firefox lists all. Following approach were taken to resolve and still unable to resolve the same 

1) Switching off directory listing explicitly
2) Removed duplicate servlet for /VAADIN URL  
3) Added login filter (but issue occurs post authentication)
4) Added welcome file list
5) Removed unwanted servlet container config in standalone.xml
6) Added underdow default servlet overide (https://stackoverflow.com/questions/67949082/getting-directory-listing-issue-with-url-vaadin-using-vaadin-8-jboss-eap-7-0)
7) Suspected exploded format deployment for the issue and tried to simulate the same for test project and yet with exploded or not , the issue is clearly unresolved

I see a clear gap in  Vaadin servlet code to understand that is clear gap in identifying if the URL to serve the static resources. Attached the stack trace for every GET request. The exception occurs post displaying the files in the directory . 
[vaadin_stack_trace.txt](https://github.com/vaadin/framework/files/6726210/vaadin_stack_trace.txt)

**Comment by TatuLund** [comment]
The issue is fixed by https://github.com/vaadin/framework/pull/12325

The fix will be included in the next maintenance release of Vaadin 8

**Comment by Ansku** [comment]
@Saranraj-pranion did you test the 8.14-SNAPSHOT that I mentioned in StackOverflow last week? It already contains that PR that Tatu linked.

**Comment by MioG777829** [comment]
@TatuLund @Ansku can you share plans to backport this to 7, as that version is still covered by Prime extended support?  If it was already backported, could you divulge which version contains this fix?  Directory listing on VAADIN/themes is still reproducible with 7.7.28.  Thank you

**Comment by TatuLund** [comment]
@MioG777829 This will be fixed in Vaadin 7 by in version 7.7.31 when it is released. https://github.com/vaadin/framework/pull/12514
