### ISSUE TITLE
Grid ComponentRenderer should have default width 100% and display the contents vertical align middle

### ISSUE THREAD

**Issue by sebastianfilke** [vaadin/framework#9170]
- Vaadin version: 8.1.0.alpha6

In the moment if you add for example a `ProgressBar` as a component in a grid cell you can't change the width of the element. This is that because the `ComponentRendererConnector` wraps the incoming widget (component) in a div element. But this div element has no styling nor the possibility to override the styling. 
Please change the default of a `ComponentRenderer` to

-  width: 100%;
-  vertcial-align: middle;
-  display: inline;
```
@Connect(ComponentRenderer.class)
public class ComponentRendererConnector
        extends AbstractRendererConnector<String> {

    @Override
    protected Renderer<String> createRenderer() {
        return new WidgetRenderer<String, SimplePanel>() {

            @Override
            public SimplePanel createWidget() {
                return GWT.create(SimplePanel.class);
            }

            @Override
            public void render(RendererCellReference cell, String connectorId,
                    SimplePanel widget) {
                ComponentConnector connector = (ComponentConnector) ConnectorMap
                        .get(getConnection()).getConnector(connectorId);
                widget.setWidget(connector.getWidget());
            }
        };
    }
```

![image](https://cloud.githubusercontent.com/assets/10894484/25477794/0a9687e8-2b3f-11e7-81e8-a42d1a4c47fc.png)

![image](https://cloud.githubusercontent.com/assets/10894484/25477815/192173ea-2b3f-11e7-9d3c-5e71e113edbd.png)

**Comment by sebastianfilke** [comment]
There is also another bug in styling for ComponentRenderer. The Grid Column has text-overflow ellipsis, which causes funny dots for a component if the column is to small.

![image](https://user-images.githubusercontent.com/10894484/28155610-bfd1ebfa-67af-11e7-88eb-b0eaf48cce9e.png)

**Comment by deformedpepper** [comment]
Either make it width 100% by default, put a classname on the div element or give us at least a way to fix it ourself.

The empty div is created in com.google.gwt.user.client.ui.SimplePanel which is used in the com.vaadin.client.connectors.ComponentRendererConnector.

We can't write our own ComponentRenderer (with our own ComponentRendererConnector and our own SimplePanel which at least puts a classname on the div) because the handling of the ComponentRenderer is hardcoded into the com.vaadin.ui.Grid in a private method generateRendererValue().

To me it looks like the Grid needs to keep track of components used by the ComponentRenderer. Therefore writing our own ComponentRenderer (and ...Connector/SimplePanel) to address the empty div problem gives us a "java.lang.RuntimeException: Component must be attached to a session when getConnectorId() is called for the first time".
