### ISSUE TITLE
@EnableRedisHttpSession fails with Communication problem

### ISSUE THREAD

**Issue by khauser** [vaadin/framework#9188]
Vaadin used together with _spring session redis_'s persistence does not work properly. Reason for that is in my opinion  a wrong line ordering within in the `VaadinService` class, where the session is stored without an assigned `LegacyCommunicationManager`. Apart from that other requests do not overwrite the initially stored `VaadinSession`. Using the `storeSession` function in the `UIInitHandler` had helped me on that. I will add a pull request as a solution proposal the next seconds.

Vaadin version: 8.0.5 but also 7.7.7 and earlier
Vaadin spring version: 2.0.1
Reproduce: https://github.com/khauser/vaadin-spring-session-push-showcase

Applying the changes of the pull request **vaadin** together with _spring session redis_ would work in normal mode. In **PUSH**-mode as already stated in https://github.com/vaadin/framework/issues/8443 it would not. The problem there is bound to a **transient** `AtmosphereResource`, which is away after deserializing the `VaadinSession`. I stuck here in making the `AtmosphereResource` serializable... Normally I would now say that the `sticky session` approach is the best workaround but the `VaadinSession` always get overwritten by the `getSession`-method from _spring session redis_ (see `RedisOperationsSessionRepository`). 
I don't know how to come over that. And I really would appreciate it if somebody from vaadin could dive deeper into this issue, it must be possible ;). Outcome could be a highly scalable vaadin service using shared session within a microservice achitecture.

**Comment by markathomas** [comment]
+1

**Comment by markathomas** [comment]
I am successfully reconnecting but have a problem showing the UI due to the following:
`
May 06, 2017 4:13:47 AM com.vaadin.server.communication.ServerRpcHandler parseServerRpcInvocation
WARNING: Ignoring RPC call to PositionReportingEmbeddedServerRpc.reportLocation in connector TelemetryTabSheetLayout(57) as no RPC implementation is registered
May 06, 2017 4:14:34 AM com.vaadin.server.communication.ServerRpcHandler parseServerRpcInvocation
WARNING: Ignoring RPC call to com.vaadin.shared.ui.button.ButtonServerRpc.click in connector com.webit360.boxview.ui.telemetry.TelemetryTabSheetLayout(57) as no RPC implementation is registered
`

**Comment by tony-pelton** [comment]
+1. just spent a few hours fiddling with this myself. trying to use the 'jdbc' implementation of spring session for a small (our first) vaadin application. ran into this issue. we use spring-session across our other spring stacks. really need vaadin to play nice with spring-session.

**Comment by mliesenberg** [comment]
+1 ran into the problem using the jdbc implementation.

**Comment by mwiesiolek** [comment]
Same issue here

**Comment by prismec** [comment]
Same issue here

**Comment by wesoos** [comment]
Same issue here with jdbc.  Are you guys actually looking into this?
