### ISSUE TITLE
Binder should automatically configure built in converters

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#9202]
Version: 8.0

Binder in V8 is not as handy as related tools in previous Vaadin versions, as developers will need to manually configure all converters, even for basic datatypes like numbers. It now forces developers to write boilerplate code for even simple cases.

Binder could do this automatically at least if name based binding is done using bindInstanceFields method (this is what I most often use).

**Comment by Legioth** [comment]
> `Binder` could do this automatically at least if name based binding is done using `bindInstanceFields``

Just filling in the blanks: To be able to find a converter, the framework needs to know the runtime type of the bean property and the value type of the field.
* The bean property type cannot be found based on a `ValueProvider` and `Setter` pair because of type erasure. The type can be known when using the reflection-based `bind(String propertyName)` method.  `bindInstanceFields` does also internally use this method.
* The value type of the field component is not necessarily known from a given instance of `HasValue<T>` since the instance might be defined as a raw type. In practice, the type is still always known since components such as `TextField` define a type that can be read using reflection (using `com.googlecode.gentyref.GenericTypeReflector`).

**Comment by mstahv** [comment]
Has anybody though of this further? This would be really nice feature, removing a lot of boilerplate code from simple apps.

**Comment by mstahv** [comment]
Ping! Please, this would really need some love and this is also very valid with V10 as well. Because of this and couple of other issues with the Binder (like the limited JSR 303 support) I still find V10 era binding (together with helpers from Viritin) more efficient in most use cases.

**Comment by TatuLund** [comment]
This has been implemented in Flow, to be included in Vaadin 23.1.

**Comment by TatuLund** [comment]
This feature is going to be included in Vaadin 8.16.0 (requires extended support subscription)
