### ISSUE TITLE
Embedded Vaadin iframe steals focus on page load on some browsers

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/framework#9232]
- Seems to occur regardless of Vaadin version
- When loading a web page with an embedded Vaadin application in an iframe, the focus of the page is shifted down from the top of the page. This occurs only on certain browsers, but at least on FireFox (tested with 53.0 on Windows 10) and possibly mobile Chrome.
- The issue can be replicated with Vaadin Sampler and the following html page:

```html
<html>
<body>
<div style="height:1000px;border:1px solid red"></div>
<div style="height:200px;border:1px solid blue"></div>
<iframe src="https://demo.vaadin.com/sampler/"
        frameborder="0" width="100%" height="100%" allowtransparency="true" name="159"></iframe>
</body>
</html>
```
Serve this HTML locally and open with FireFox to see how the page loads - it's scrolled down instead of starting from the top. In desktop Chrome, it works as expected. Replace the Sampler URL with e.g. `https://www.w3schools.com/` to see that the behavior only occurs with an embedded Vaadin application.

**Comment by Legioth** [comment]
This is most likely caused by https://github.com/vaadin/framework/blob/master/client/src/main/java/com/vaadin/client/ui/ui/UIConnector.java#L574 that makes a new UI try to focus itself when it's loaded if the application is in "standalone" mode, i.e. run from bootstrap HTML generated by the framework instead of being explicitly embedded into an HTML page or run in as a portlet. When running in an iframe, the generated bootstrap HTML is still used inside the iframe. It's then up to each browser whether they allow focus requests from inside the iframe to affect the outside.

You can probably work around this in your application with a custom bootstrap listener that rewrites initial configuration JSON to remove the `standalone` flag.

On the framework side, the client-side logic could probably check whether it's inside an iframe, and in that case avoid trying to focus itself. It could however also be argued that the current default should be preserved since focusing the contents is still desirable in cases when a UI is the only thing that is shown on a page, but it's still embedded through an iframe for cross-frame reasons.

**Comment by tsuoanttila** [comment]
https://vaadin.com/docs/v8/framework/advanced/advanced-embedding.html has instructions on embeddings the Vaadin application and there's an explicit note on the `standalone`that it should be set to `false` when it's not the only content.

Quote from the documentation:
##### standalone
This parameter should be false when embedding. The parameter defines whether the UI is rendered on its own in the browser window or in some context. A standalone UI may do things that might interfere with other parts of the page, such as change the page title and request focus when it is loaded. When embedding, the UI is not standalone.
