### ISSUE TITLE
Unable to create custom Renderer (as presented in Vaadin docs)

### ISSUE THREAD

**Issue by michallichvar** [vaadin/framework#9328]
I wanted to create custom ButtonRenderer, as I would like to display Button in Grid only in some rows, based on particular value from the row.

I found several examples, all with solution from official docs:
https://vaadin.com/docs/-/part/framework/clientsidewidgets/clientsidewidgets-grid.html#clientsidewidgets.grid.renderers

However, this docs are out of date, looks like this part comes from Vaadin 7, as in Vaadin 8 there is no method render() available to Override. Also RendererCellReference is unknown.

I tried both 8.0.0 and latest 8.0.6.

Any suggestions?

**Comment by tsuoanttila** [comment]
The page of documentation you linked is for the client-side of the renderers. There is a `Renderer` interface for both client and server. On the client-side full package name is `com.vaadin.client.renderers.Renderer` and the server-side is `com.vaadin.ui.renderers.Renderer`. These two interfaces have a different API and the client-side one is located in the `com.vaadin.vaadin-client` artefact. Make sure you have all necessary dependencies. 

The Grid renderer concept consists of three parts:
1. Server-side of the renderer which gets input of a certain type from the `Column` and makes a `JSON` representation. Existing `AbstractRenderer` on the server side will attempt to automatically encode most types, but for custom types you may need to override the `Renderer#encode` method.
2. Client-side of the renderer which get a cell and the `JSON` created by the server-side.
3. `Connector` which knows that your server-side of renderer maps to your client-side of renderer

Take a look at [server-side](https://github.com/tsuoanttila/custom-grid-demo/blob/master/src/main/java/org/vaadin/customgrid/CheckboxRenderer.java) and [connector & client-side](https://github.com/tsuoanttila/custom-grid-demo/blob/master/src/main/java/org/vaadin/customgrid/client/CheckboxRendererConnector.java) from a Vaadin 7 example. The APIs have not changed much between 7 and 8.

These instructions should help @michallichvar to get forward. For the actual fix for this ticket, the documentation on Grid renderers should be rewritten in a tutorial-like way, since only describing this in parts will do no good.

**Comment by michallichvar** [comment]
Hello, thank you for quick answer.

Looks like I haven't notinced client class Renderer, because
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-spring-boot-starter</artifactId>
		</dependency>

does not contain
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-client</artifactId>
			<version>${vaadin.version}</version>
		</dependency>

However, I still don't understand, how by overriding Renderer#encode(Object value) can I reach my goal: not to render a button. I'm trying to override ButtonRenderer. Desired logic: if (value != null) renderButton();

**Comment by michallichvar** [comment]
Is there any other solution than this hack?
https://stackoverflow.com/questions/42012282/how-to-hide-the-button-in-generated-column-in-grid

**Comment by michallichvar** [comment]
looks like feature addComponentColumn introduced in vaadin 8.1 is the solution

`grid.addComponentColumn(
    person -> new Button("Delete",
        e -> delete(person)
    )
);`

or

`public void addColumnWithDeleteButton(Consumer<UserDTO> c) {
		grid.addComponentColumn(dto-> {
			if (dto.canDelete()) {
				return null;
			} else {
				return new NativeButton("Delete", event -> c.accept(dto));
			}
		});
}`
