### ISSUE TITLE
VaadinSession missing serialVersionUID

### ISSUE THREAD

**Issue by markathomas** [vaadin/framework#9338]
Bumping Vaadin from 8.0.5 to 8.0.6 then attempting to deploy resulted in the following exception:
`
2017-05-16 20:33:37,405 com.webit360.boxview.web.UncaughtExceptionFilter ERROR [http-nio-8080-exec-7] Uncaught exception
org.springframework.data.redis.serializer.SerializationException: Cannot deserialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is java.io.InvalidClassException: com.vaadin.server.VaadinSession; local class incompatible: stream classdesc serialVersionUID = -232728198079740282, local class serialVersionUID = 5419537850195707397
`

Vaadin MUST include serialVersionUIDs on its serializable components in order for shared sessions to work for those of us that go through the pain of making it work.

**Comment by Legioth** [comment]
Adding `serialVersionUID` to all classes that might be serialized would mean that we'd also have to ensure that an object serialized with one version can be deserialized with some other version.

Only adding `serialVersionUID` without also ensuring compatibility would instead cause hard-to-debug issues e.g. when some newly introduced field wouldn't be properly initialized if it was serialized with a version where that field didn't exist.

We have chosen to not use `serialVersionUID` in Vaadin Framework since proper usage would slow us 
down. This means that any serialized sessions might be invalid after upgrading to a new version. The proper solution to that is usually to silently discard any such sessions, thus causing the same end result for a user as though their session would have expired.

**Comment by markathomas** [comment]
With this practice you cannot possibly state that Vaadin is properly Serializable.  You've taken the easy way out and pushed all the work onto your users.  This means there's no way to upgrade to a new Vaadin version without discarding all existing sessions thus breaking the ability for seamless upgrades.

**Comment by Legioth** [comment]
We have never aspired to that level of serializability. Perfect migration of the server-side state from one framework version to another would not even be enough for a seamless upgrade since any application that the user has open in a browser would still use client-side state and code from the previous version.

This means that the best possible upgrade experience would be to implement something similar to how e.g. Google Inbox works: any open session remains pinned to the old version of the backend, and then a notification is shown that encourages the user to refresh to get the new version. Upon refresh, the user is migrated to the new backend version and all relevant application state is restored based on the navigation status in the loaded URL.

This would require integration with the way the application is hosted, so it's not something that we could provide out of the box. Please open separate tickets if you try to implement this kind of scheme and discover something that would need to be improved on the framework side.

**Comment by Legioth** [comment]
I don't see how we could do anything about this unless someone comes up with an approach for how to also update code running in the browser at the same time as a session would be deserialized into an updated server-side version.
