### ISSUE TITLE
Variable row height in grid component for Vaadin 8

### ISSUE THREAD

**Issue by BrianSiimAndersenEG** [vaadin/framework#9355]
We need variable row height in the grid component. Are there any plans to support variable row height for grid? And if so - when can it be expected?

We're using Vaadin 8 and would love to use the grid, but we need variable heights for the grid rows, which are not supported. It's supported in table and that means that we're stuck with the table - unfortunately...

**Comment by Legioth** [comment]
There are no specific plans for making Grid support variable row heights.

It is actually not supported for Table either, but it happens to be possible to hack Table to work quite well in that way. There are still some cases where e.g. the scrollbar might behave in a quite strange way.

**Comment by BrianSiimAndersenEG** [comment]
We have done this using Table without any hacks whatsoever. We add a generated column, and the generateCell returns a VerticalLayout. The row is automatically fitted to the contents of the VerticalLayout. Grid does not adjust the height of the row when we use the ComponentRenderer in the same way as the generated columns in Table.

**Comment by neerup** [comment]
It seems there is no way to drop the compatibility packages (Table)  and move on the the clean Vaadin 8.x if there is no plans for grid to support row height. That is really sad :( Hopefully the (**Infinite scrolling generic component #8711**) will receive more love then...

**Comment by AdamBrowning** [comment]
We're running into the same issue as neerup. Fully upgraded to Vaadin 8 but can't drop compatibility until there's a solution for this. 

The blog post for elements showcases variable row height (https://vaadin.com/blog/-/blogs/-vaadin-grid-2-0-with-million-dollar-scrolling) and talks about Java APIs being available. Hopefully sooner than later!

**Comment by elexx** [comment]
Just want to leave another :+1: here. We are also blocked by not having dynamic row-height anymore.

**Comment by Artur-** [comment]
This will be implemented in Vaadin 10, through the usage of the `vaadin-grid` element which already today supports variable row height.

**Comment by gaugat** [comment]
Can the vaadin-grid element be use with Vaadin 8? And if so, is there an example on how to do this?

**Comment by Fitzchev** [comment]
+1 for having variable row height support for grid in Vaadin 8: it's currently blocking the design of one of our screen, and switch to Vaadin 10 is not yet an option.

**Comment by elmot** [comment]
@Fitzchev, unfortunately not in our plans. You can try to use https://vaadin.com/directory/component/elements-add-on/0.2.0 + vaadin-grid
Note, if you need lazy data loading, then it might be quite challenging.

**Comment by koen-serneels** [comment]
+1 We have a large application in Vaadin and migrated to Vaadin 8 some time ago. This was by far a painless experience and migration from Table to Grid was one of them, mainly because the Grid lacks  features compared to Table. Sure, we could continue using tables, but these have other issues and are afaik no longer the official way to go aka deprecated 

It's understandable that Grid is (relatively) new and that these things can take time. Indeed, some features were retrofitted to the Grid afterwards, but there are still many things left open likethis ticket. What concerns me is the type of replies from Vaadin on this matter: imho Vaadin is letting a large user base down by not properly supporting features on one of the more important components for building web-applications, and I find this very disturbing for future use of Vaadin.  Pointing to Vaadin10 or some add-ons (of which code quality, sorry to say this, is mostly questionable and where there is no kind of support) is not a solution, it's merely saying: we are no longer interested in properly maintaining our current production version. Also, Vaadin10 is by far not finished and seems a different beast all together. 

So, to conclude: please Vaadin, take some respo

**Comment by AdnanMujkic** [comment]
+1 Vaadin 11 now out, and this is still open... Spending far to much time on finding an elegent solution for this problem, which should have not be there in the first time...Allready regreted starting a project with Vaadin

**Comment by zaheer1389** [comment]
Vaadin 12 is also out and this issue still not resolved. Will vaadin going to resolved this issue or not?

**Comment by Legioth** [comment]
> +1 Vaadin 11 now out, and this is still open...

> Vaadin 12 is also out and this issue still not resolved. Will vaadin going to resolved this issue or not?

Grid in Vaadin 10 and newer supports variable row heights. This ticket is still open because this issue tracker is for Vaadin 8.

I'm wondering if we should close this issue as fixed, even though that would imply that it has been fixed in Vaadin 8 as well?

**Comment by elmot** [comment]
@Legioth, I think this may be closed with a resolution "Fixed in Vaadin 10+".
IIRC there is a number of Vaadin 7- issues closed this way when something was done in Vaadin 8.

**Comment by gaugat** [comment]
Unfortunately, not everyone can upgrade to Vaadin 10+. For example, we use Vaadin 8 to develop portlets for Liferay. Vaadin 10+ has no support for portlets.  I'm sure many people need to find add-on replacements as well.

**Comment by ohens** [comment]
Are there any plans on fixing this or will this be left open/not-fixed because of the new Vaadin Platform?

We are also in the situation that after quite complex migration from Vaadin 7 to 8, we still have to use deprecated table all over our projects because of this issue. Migration to Vaadin 10+ is also not option right now, as the effort would be huge (too soon after the last migration) and still other things missing (like non-modal sub-windows which can be dragged around etc.).

It would be nice to know if there will still be improvements like this be made for Vaadin 8 or if the development stopped altogether.

**Comment by Legioth** [comment]
I don't anticipate that anyone will find the time to make this kind of enhancement to the Grid implementation that is used in Vaadin 8. This is an architectural issue that cannot be resolved without  significant rework.

I am truly sorry that we weren't determined enough to come up with a good way of doing this at the time when we created the original Grid architecture. Luckily, the next generation that built the Grid web component for Vaadin 10 was able to learn from our mistakes.

I'm going to close this issue to signal the expected outcome. It may be opened again if our internal priorities change or if an external sponsor shows up.
