### ISSUE TITLE
TreeGrid IconGenerator Has No Effect

### ISSUE THREAD

**Issue by bdunn44** [vaadin/framework#9391]
Using Vaadin 8.1.0.alpha8. Setting an IconGenerator has no effect:
```java
TreeGrid<String> tree = new TreeGrid<>();
tree.addColumn(String::toString)
    .setCaption("");
tree.setItemIconGenerator((value) -> FontAwesome.THUMBS_UP);
```
Currently using an HtmlRenderer as a workaround:
```java
tree.addColumn((value) -> "<i class=\"fa fa-thumbs-up\"></i> " + value)
    .setCaption("")
    .setRenderer(new HtmlRenderer());
```

**Comment by hesara** [comment]
setItemIconGenerator() is protected in Grid and its subclasses as it is inherited from the common parent class AbstractListing, but is only really supported in specific subclasses (CheckBoxGroup, RadioButtonGroup and ComboBox). The example in the ticket only compiles if in a subclass of AbstractListing (at least with 8.1.0.beta1).

The javadoc of setItemIconGenerator() should be clarified, but otherwise I think the renderer approach is the correct one if you want an icon column (though I think it can be slightly simpler), and gives more freedom on the location and behavior of the column.

Clarifying the javadoc in #9442, closing this issue.
