### ISSUE TITLE
Binder.getBean() returns null in validator if Grid.Editor is in buffered mode

### ISSUE THREAD

**Issue by F43nd1r** [vaadin/framework#9392]
Sometimes, a property `Validator` needs to check the bean for context data. However, this is currently not possible when the `Grid.Editor` is in buffered mode, as in this case `Binder.getBean()` returns null inside the `Validator`.

Minimal example:
```java
    {
        Grid<Bean> grid = new Grid<>("ExampleGrid");
        Editor<Bean> editor = grid.getEditor().setEnabled(true);
        //editor.setBuffered(false); //this is a workaround, but not desired
        Binder<Bean> binder = editor.getBinder();
        grid.addColumn(bean->String.valueOf(bean.aBoolean)).setCaption("Value")
                .setEditorBinding(binder.forField(new CheckBox())
                        .withValidator(value->value && binder.getBean().context, "Failed Check") //binder.getBean is always null here
                        .bind(bean -> bean.aBoolean,(bean, value) -> bean.aBoolean = value));
        grid.setItems(new Bean());
    }
    
    private static class Bean {
        boolean aBoolean;
        boolean context;
    }
```

Vaadin version: 8.0.6

**Comment by jcgueriaud** [comment]
Hi,

binder.getBean returns the bean set by setBean. In buffered mode the binder values are set by readBean and no bean is set to the binder so getbean returns null (and the bean properties are not written because it's buffered).
You can't have the bean read by readBean.

You can add a bean validator
editor.getBinder().withValidator()
But this validator is not link to your field and the validation check is done during writeBean (in buffered mode).
if "context" is editable you can get the value from the field and use a field validator:
.withValidator(value->value && contextField.getValue(), "Failed Check")

**Comment by hesara** [comment]
The javadoc of readBean implies this by stating that "The bean is not otherwise associated with this binder." However, the implications of this on grid editors and buffered mode are not that clearly documented. The relevant documentation could be improved for this.

The easiest way around this is probably validating the field value as jcgueriaud suggested, which does not require a custom Binder - the Binder is normally created by the constructor of EditorImpl, and might require a bit more work to replace with all other bindings created automatically.

**Comment by NBau** [comment]
I am facing the same issue, but I cannot really use the workaround proposed by @jcgueriaud, since I need access to the bean's class to check for additional context information. Wouldn't it be possible to extend the editor interface to provide access to the currently edited bean, since EditorImpl already stores the bean internally.

**Comment by tsuoanttila** [comment]
The Editor API should be extended to contain `getBean()` for accessing the bean even in buffered mode. Discussion about if it's semantically correct to use some extra members of the bean in your validator is a completely different thing.
