### ISSUE TITLE
Atmosphere should not spam console when running Vaadin application

### ISSUE THREAD

**Issue by johannesh2** [vaadin/framework#9426]
Running a regular Vaadin application with mvn jetty:run produces a lot of INFO level output to console. It's annoying.

**Comment by jreznot** [comment]
It would be nice if they use SLF4J for these log statements, so will be able to control this log output using our loveable logging backend, for instance logback/

**Comment by jdahlstrom** [comment]
Atmosphere logging can be controlled with normal j.u.l configuration (maybe one should be provided by the archetype?) SLF4J is actually used by vanilla Atmosphere but alas, its use turned out to be infeasible because some app servers include (some arbitrary version of) it on the classpath and others don't. It would have necessitated providing compatibility modules for each supported app server.

**Comment by jreznot** [comment]
SLF4J is just API, so libraries can use it safely, app servers will not conflict with it. We really want to patch Vaadin atmosphere version to use slf4j, since it is much more convenient than j.u.l.

**Comment by Legioth** [comment]
> SLF4J is just API, so libraries can use it safely, app servers will not conflict with it

Back in the days, there were differing opinions from at least JBoss AS 5 and 6 (#3839) and TomEE 1.5 (#3885).

Could be that the servers we're currently supporting are more well-behaved.
