### ISSUE TITLE
TreeGrid Expand and Sort Produce Inconsistent State and Error

### ISSUE THREAD

**Issue by bdunn44** [vaadin/framework#9449]
8.1.0.beta1

When attempting to track expanded nodes and re-expand after sorting, the expand method appears to have no effect.

```java
class MyTreeGrid<T> extends TreeGrid<T> {
    private static final long serialVersionUID = 5137316344382298358L;
    private Set<T> expanded = new HashSet<>();
    MyTreeGrid() { 
        super();
        addExpandListener(e -> expanded.add(e.getExpandedItem()));
        addCollapseListener(e -> expanded.remove(e.getCollapsedItem()));
    }
    @Override
    public void sort(Column<T, ?> columns) {
        super.sort(columns);
        super.expand(expanded);
    }
}
HorizontalLayout buttons = new HorizontalLayout();
MyTreeGrid<String> tree = new MyTreeGrid<>();
TreeData<String> data = new TreeData<>();
tree.setDataProvider(new TreeDataProvider<>(data));
tree.addColumn(String::toString);
for (String root : new String[]{"First", "Second", "Third"}) {
    data.addItem(null, root);
    for (String child : new String[]{"1", "2", "3"}) {
        data.addItem(root, root + " - " + child);
    }
}
Button sort = new Button("Sort", e -> tree.sort(tree.getColumns().get(0)));
content.addComponent(tree);
content.addComponent(buttons);
buttons.addComponent(sort);
```

Additionally, using the example above, performing the following clicks produces incorrect data in the tree and the error below.

1. Expand "First", "Second" and "Third"
2. Click Sort button
3. Expand "Third"
4. Click Sort button
    a. Notice that the "Second" child items are displayed underneath the "First - 1" item
5. Click Sort button

```
...
Caused by: java.lang.IllegalArgumentException: Invalid row index 8 when tree grid size of 3
	at com.vaadin.data.provider.HierarchicalDataCommunicator.doExpand(HierarchicalDataCommunicator.java:421)
	at com.vaadin.ui.TreeGrid$1.setNodeCollapsed(TreeGrid.java:137)
	... 44 more
```

**Comment by hesara** [comment]
This seems to be a workaround for #9448, and the approach described here is less often needed once that issue is addressed.

In any case, I can confirm that there are problems with sorting hierarchical data (right now either HierarchyMapper internal indices don't get updated, or we just clear the whole HierarchyMapper).

Addressing this might require somewhat larger changes to HierarchyMapper and the behavior of HierarchicalDataCommunicator on various kinds of refresh/reset situations, but should be done before 8.1 final.
