### ISSUE TITLE
Grid Drag Scrolling Not Working

### ISSUE THREAD

**Issue by mikleing** [vaadin/framework#9477]
This issue may be related to https://github.com/vaadin/framework/issues/7085.

Vaadin Grid does not drag scroll the screen when the end of the list is reached.  To see an example of this issue visit https://demo.vaadin.com/dashboard/#!dashboard on a mobile device.  Scroll down to the "Top 10 Titles by Revenue" widget.  Drag scroll to the end of the list.  Once you reach the end of the list the rest of the page does not scroll down.  This is functional in this particular example because you can drag scroll on other parts of the UI.  But in my use case Grid can take up the entire screen.

It appears that Vaadin Elements Grid 2.0 scrolls correctly.  Here is an example: https://cdn.vaadin.com/vaadin-grid/2.0.0-alpha3/demo/data.html  Although, I sometimes had issues scrolling the actual grid list.  But the drag scrolling the page worked correctly.

I am using Vaadin Framework version 8.1.0.beta1.  How do I make drag scrolling actually scroll the entire page and not just the grid in Vaadin Framework?  Thanks!

**Comment by hesara** [comment]
The interaction of scrolling components on the page vs. the whole page is sometimes tricky on mobile devices, especially when coming to an end of the scroll range for the component.

Right now, I can't think of an easy way for the user to customise this (see the TODO at https://github.com/vaadin/framework/blob/master/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L630 ).

However, if there is a sliver of the page visible in some edge of the screen, that can be used to scroll the page rather than the Grid, which is probably the easiest application level workaround for this.

**Comment by mikleing** [comment]
Thanks for the response!  I was aware that a user could scroll by using a sliver of the page visible on the edge.  It just isn't a great user experience in my opinion.  Users think the page is unresponsive.  It's not obvious to most to drag along the sliver visible on the side.  Unless there is a good reason not to, it would be wonderful if this could be corrected at some point.  Thanks!
