### ISSUE TITLE
Vaadin 8 Tree gets horizontal scrollbar if there's a vertical scrollbar

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/framework#9503]
- Vaadin version 8.1beta1
- If a fixed dimensions Tree is vertically so short that all of the contents won't fit into it, it gets a vertical scrollbar. This is ok, but once the vertical scrollbar appears, a horizontal scrollbar 
- Minimal sample project:
[tree.zip](https://github.com/vaadin/framework/files/1060121/tree.zip)
![image](https://user-images.githubusercontent.com/15027701/26915389-85808c0a-4c2e-11e7-86f5-6491b369ce06.png)

```java
public class TreeUI extends UI {

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        layout.setHeight("300px");
        layout.setWidth("500px");
        
        Tree<String> tree = new Tree<>("Hardware Inventory");
        
        TreeData<String> data = new TreeData<>();
        data.addItems(null, "Desktops", "Laptops")
            .addItems("Desktops", "Dell GX240", "Dell GX260", "Dell GX280")
            .addItems("Laptops", "IBM T40", "IBM T43", "IBM T60");
 
        tree.setDataProvider(new TreeDataProvider<>(data));
        tree.expand("Desktops", "Laptops");
        tree.setItemIconGenerator(item -> {
            if (item.equals("Desktops")) {
                return VaadinIcons.DESKTOP;
            } else if (item.equals("Laptops")) {
                return VaadinIcons.LAPTOP;
            }
            return null;
        });
        tree.setSizeFull();
        
        layout.addComponent(tree);
        setContent(layout);
    }

    @WebServlet(urlPatterns = "/*", name = "TreeUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = TreeUI.class, productionMode = false)
    public static class TreeUIServlet extends VaadinServlet {
    }
}
```

**Comment by tsuoanttila** [comment]
If I remember correctly we have specifically disabled most size setting methods to make the Tree behave like it did back in the old Vaadin 7. Said old Tree does not support basically any other height mode than undefined (takes size based on content).

I'm not sure how good UX it is to allow a tree component have scrolling, but if it is something we should support, this issue is making it a bit difficult. Issue itself should be fixed in Escalator so that it would shrink the columns by the width of the scrollbar to prevent the horizontal scroll.

**Comment by OlliTietavainenVaadin** [comment]
Vertical scrolling should probably work, but I'm not sure if there's ever a need for the horizontal scrollbar.

**Comment by tsuoanttila** [comment]
Initially when escalator calculates the size of the columns, the vertical scrollbar is not there, and the column size is calculated without taking that into account. That's why the horizontal scrolling appears. usually if you have lots of data, you should use TreeGrid and not Tree, since the latter has some limitations in it's functionality.
