### ISSUE TITLE
getContainer().getItem(itemId)

### ISSUE THREAD

**Issue by ayutang** [vaadin/framework#9526]
Object[] itemIds = tabularForm.getContainer().getItemIds().toArray();
			for (Object itemId : itemIds) {
				Item item = tabularForm.getContainer().getItem(itemId);
			}
itemId is not null
why item is null?
thanks for your answer

**Comment by Artur-** [comment]
Hi,

This looks more than a request for help than a report about something which is broken in the product. The issue tracker is used only for reporting bugs in the product itself and for requesting new features to be incorporated in an upcoming version. For all other matters, please use the forum at https://vaadin.com/forum.

For bug reports you should include a way to reproduce the problem. The best way for this is to create a GitHub project where you demonstrate the issue and add a link to it in the issue. Another good way is attaching a UI class which demonstrates the problem. Do make sure though that the attached code actually compiles and is not dependent on some internals of your real application project.

For either approach, please also include a list of steps to perform to see the issue, and a description of what you would expect to happen and what actually happens.

For feature requests, please describe the use case where you want to use the feature rather than only how you feel it could be technically implemented. For most features, there are multiple use cases and a good design can only be made once several of these are known.
