### ISSUE TITLE
MenuBar Component not accepting Tabindex

### ISSUE THREAD

**Issue by xoulz** [vaadin/framework#9550]
Im using the MenuBar Component of Vaadin 7.7.6 (also tested with Vaadin 8.0.6) and its not accepting the Tabindex i want to set.
Heres my code:

`MenuBar barmenu = new MenuBar();`
`MenuBar.MenuItem servs = barmenu.addItem("Services", null, null);`
`servs.addItem("Car Service", null, null);`
`barmenu.setTabIndex(-1);`

No matter what Tabindex i set (tried -2, -1 and >= 1) the Index always stays at 0. Is this a bug thats fixed in another Vaadin Version or is this behaviour intended?

![tabindex](https://user-images.githubusercontent.com/3998703/27220666-43670688-5286-11e7-858d-62391b6340b4.png)

**Comment by OlliTietavainenVaadin** [comment]
`MenuBarConnector` extends `AbstractComponentConnector`
where in the `onStateChanged` method, the tab index should be set:

```java
     if (getState() instanceof TabIndexState) {
            if (getWidget() instanceof Focusable) {
                ((Focusable) getWidget())
                        .setTabIndex(((TabIndexState) getState()).tabIndex);
            } else {
                /*
                 * TODO Enable this error when all widgets have been fixed to
                 * properly support tabIndex, i.e. implement Focusable
                 */
                // VConsole.error("Tab index received for "
                // + Util.getSimpleName(getWidget())
                // + " which does not implement Focusable");
            }
        }
```

`MenuBarState` extends `TabIndexState` and `VMenuBar` implements `Focusable`, so the setting of TabIndex should happen properly. 

However, I believe `AbstractComponentConnector.onStateChanged` is never called from `MenuBarConnector` because `MenuBarConnector` uses  `updateFromUIDL` to pass values instead.

**Comment by Artur-** [comment]
@OlliTietavainenVaadin The problem is that `VMenuBar` implements `com.vaadin.client.Focusable` and not `com.google.gwt.user.client.ui.Focusable`
