### ISSUE TITLE
TreeTable - massive performance decrease caused by over 400.000.000 internal calls in TreeTable

### ISSUE THREAD

**Issue by simonesaenftl** [vaadin/framework#9662]
TreeTable with 15.000 entries.
Used Vaadin Version: 7.7.10
Screenshots of jVisualVM and Eclipse --> attached you´ll find it under "Bug 1" 

Current situation: TreeTable is used to display 15.000 entries. This leads to a massive performance decrease caused by over 400.000.000 internal calls in TreeTable (we stopped measuring after we reached this high number).
[Vaadin - Bugs.docx](https://github.com/vaadin/framework/files/1135260/Vaadin.-.Bugs.docx)

**Comment by ralfklemmer** [comment]
Do you have any new thoughts about this?

**Comment by hesara** [comment]
The issue stems from the modification (setParent() etc.) and expansion/collapsing (setCollapsed()) methods of TreeTable invalidating the preOrder cache.

I would recommend taking the following steps in the application to solve the issue:
* Pre-create a hierarchical container (including parent relationships) before setting it for the TreeTable.
* If you want to expand many nodes from the beginning, make the container class implement Collapsible, and set up collapsed/expanded nodes before setting the container for the component. You can even use a subclass of HierarchicalContainer with a trivial map/set based implementation of the two methods of Collapsible.
* If not implementing Collapsible, avoid automatically expanding too many nodes at once.

These should improve the performance of your TreeTable drastically.

Note that pre-constructing a container before setting it for a component is strongly recommended for any data component in Vaadin with a large number of items, not just for TreeTable. Furthermore, modifications of more than a few items are typically more efficient if detaching the container from the component, making the modifications and then re-attaching the container. This is because the component constantly listens for modification events from its container.

**Comment by tsuoanttila** [comment]
Documentation and JavaDocs fixed. Telling to use a `Container.Hierarchical` with a large data set as well as instruct to create the data before setting the container to `TreeTable`.
