### ISSUE TITLE
Heartbeats blocked during long run request

### ISSUE THREAD

**Issue by simonesaenftl** [vaadin/framework#9663]
Used Vaadin Version: 7.7.10

We had several bugs because Vaadin UI and Session have been removed, because of not received Heartbeats. In fact, the Heartbeats have been send, but during processing a long running request Hearbeats are not processed until the long running request has finished.

1.	Start long running request
2.	Hearbeats will be send, but not received/processed
3.	End of long running request
4.	Kill of UI by Vaadin
5.	Hearbeats are processed (but it’s to late, because UI and Session have been invalidated.

**Comment by Legioth** [comment]
The reason the heartbeat request is "ignored" is that the heartbeat request is waiting for the session lock that is currently being held by the thread that handles the long running request. The UI is killed by the cleanup code that the long running request triggers right before releasing the lock.

I can think of several ways how we could change the framework to better deal with this:
* Also update the timestamp for the current UI when the actual processing for the request has been done, but before checking for expired UIs that haven't received any heartbeat requests. The drawback of this simplistic approach is that it would still allow other UIs in the same session to be killed.
* Only kill UIs because of "missed" heartbeats in cases where there's no other thread waiting for the session lock, i.e. by checking `ReentrantLock.hasQueuedThreads`. In this way, UIs would only be killed after any pending heartbeat requests have had a chance to update the timestamp.
* Update the heartbeat handling logic to not depend on the lock. This could be achieved using e.g. a `ConcurrentHashMap` in `VaadinSession` that maps UI ids to hearbeat timestamps. After updating the timestamp, it would also try to lock the session to actually do any cleanup, but just fall back if the session cannot be locked. The additional benefit of this approach is that it would use less resources on the server when heartbeat requests wouldn't be left blocking.

There is still one even more fundamental issue that can only be resolved on the application level, namely that there are long running requests in the first place. The user experience could probably be better if the long processing would be done in a background thread so that the UI and session doesn't have to be locked the entire time. The UI can still show e.g. a modal dialog with a progress indicator or spinner, and maybe also a "Cancel" button. For this to work, the UI would also have to use push or polling so that it could be updated once the processing is completed.

**Comment by ralfklemmer** [comment]
Hi Legioth,
thank's for your fast feedback.
Your thoughts are totally correct. We just implemented a workaround that is based on your suggestions (+2). But much better would be suggestion no. 3. This is definitly what we would prefer.

In general your right, that such long running request should be done in background, but sometimes (and that's our case) we have to do it synchroniously.

Do you plan to implement suggestion no. 3? And until when can we expect a fixed Vaadin version?

**Comment by Legioth** [comment]
Alternative 2 (checking `ReentrantLock.hasQueuedThreads`) is the bugfix approach that I expect we will go with for resolving the [Warranty request](https://vaadin.com/support#section-warranty) that is open for this issue.

Alternative 3 (completely avoiding the lock) seems like a new feature that requires more thorough design and validation. We could consider introducing it (if it's actually feasible) in some upcoming minor or major version based on expected ROI compared to other potential new features (or if someone wants to sponsor the feature).

**Comment by mschmiedel** [comment]
Hi. Can you confirm on which Vaadin Versions the fix will be rolled out? We are interested in a 7.7.10+ Version (prior to 8)

**Comment by mschmiedel** [comment]
Hi. according to the latest activity, it would seem that it is only planned for a 8.2+ Version. Can you confirm if this is the case? Are there any chances for a 7.7.10+ Version?

**Comment by Legioth** [comment]
@mschmiedel Cherry pick to the 7.7 branch is done in https://github.com/vaadin/framework/pull/10450

**Comment by OlliTietavainenVaadin** [comment]
If everything goes well, it will be included in 7.7.13.
