### ISSUE TITLE
Tutorial need to be updated to make it work properly

### ISSUE THREAD

**Issue by lmmathurin** [vaadin/framework#9821]
In the tutorial:
https://vaadin.com/docs/-/part/framework/tutorial.html

At step 6.1.2 we have the following code:

private CustomerService service = CustomerService.getInstance();
private Customer customer;
private MyUI myUI;

public CustomerForm(MyUI myUI) {
    this.myUI = myUI;
}

We need to change the constructor to be:
public CustomerForm(MyUI myUI) {
    **super();**
    this.myUI = myUI;
}

Otherwise he layout will not be done by the super class !

**Comment by anasmi** [comment]
Hi,

actually, it's not necessary since  Java compiler automatically inserts a call to the no-argument constructor of the superclass.  And since CustomerForm class extend the FormLayout class, which has public no-argument constructor, this will work as it should out of the box.
[Using super keyword in Java](http://docs.oracle.com/javase/tutorial/java/IandI/super.html)

So there is no need to add this line explicitly and update tutorial. : )
Regards,
Anastasia
