### ISSUE TITLE
Paging Problem when add Checkbox Component Column.

### ISSUE THREAD

**Issue by RomeoAT** [vaadin/framework#9852]
I'm trying to add a checkbox as Component Column in grid. This column serves custom implementation for row selection dependent on defined logic . But i get a problem with paging. The checkbox is redrawn every time and getting initial value not (selected, or invisible) as defined in server side.
![1](https://user-images.githubusercontent.com/31248848/29572194-d877b51a-875b-11e7-869c-4b967f99e4f1.png)
![3](https://user-images.githubusercontent.com/31248848/29572205-e2a8595e-875b-11e7-8248-b3b377d8351a.png)
![2](https://user-images.githubusercontent.com/31248848/29572236-06767870-875c-11e7-94f1-3d96e3b4f031.png)

**Comment by ahie** [comment]
The `ComponentRenderer` javadocs have the following note:

"Components will occasionally be generated again during runtime e.g. when selection changes. If your component has internal state that is not stored into the object, you should reuse the same component instances."

This can possibly in your case be achieved for instance with a `Map` that stores `CheckBox`es with the key corresponding to the item in your `Grid` and instantiating a new `CheckBox` in the `ComponentRenderer` only if it is absent in the `Map`.

Another option for doing custom selection logic is to extend `Grid` itself so that a custom `GridSelectionModel` can be passed to the protected `setSelectionModel` method.

**Comment by RomeoAT** [comment]
thanks for replay. actually Mapping the checkbox is good idea. I've solved the problem with using an embedded component with path for selected, other for not selected and final path for not allowed to select. 
i've implemented already the mapping solution.
