### ISSUE TITLE
In special scenario AbstractField component don't trigger ValueChangeListener

### ISSUE THREAD

**Issue by doctorlux** [vaadin/framework#9900]
Vaadin version: 7.7.10.

There is a bug in AbstractField component for not triggering ValueChangeEvent in following scenario:
- binding must be used
- buffering should be false

If certain value is assigned to component by user (trough UI), then change the value of this field trough binding value (not setting the value directly on component), and then change to do old value again trough UI. In this case ValueChangeEvent should be triggered by changing the value from new one to old one, but it's not happening. In case that the changed value is from new to some other, ValueChangeEvent is triggered as expected.

In attachment is a reproducible example of this bug.
Simply unzip the project.
Reproducible scenario:
1. In ComboBox select value v1. Notification shows that ValueChangeEvent is triggered.
2. Click on the button. ComboBox value is changed to v2, but no VCE is triggered (no notification on the screen) because change is made trough backend. (works as expected)
3.1. (Unexpected behaviour) Select again v1 on ComboBox, and nothing happens (notification should appear).
3.2. (Expected behaviour) Select v3 on ComboBox and notification is shown.

[DemoValueChange.zip](https://github.com/vaadin/framework/files/1263352/DemoValueChange.zip)

**Comment by Ansku** [comment]
Took me a while to realize, but the problem here is that you are updating your DTO directly, not through the BeanItem as you should if you want the field to update its internal state properly. If you do that, you'll get a ValueChangeEvent from all updates, including the one that happens through the data source, and the field never has a chance to end up in an inconsistent state. Vaadin 7 ComboBox still uses Vaadin 6 -type legacy communication logic between server- and client-side, so the inconsistent state happens to be outwardly invisible and only reveals itself in the two missing events. In other words, an easy mistake to make and a difficult one to spot if it isn't fresh on your mind, but works as designed.

Try setting the value like this instead:
`comboBox.getPropertyDataSource().setValue("v2");`
or even:
`binder.getItemDataSource().getItemProperty("value").setValue("v2");`

**Comment by doctorlux** [comment]
I'm not sure if I can agree with you on that. Because, changing the data in DTO in any other values beside described scenario it forks as expected. I had a couple longer discussion with guys from Vaadin Expert chat and they agreed also that this is bug and not expected behaviour. Maybe I'm thinking in the wrong direction, but if buffering is not used, then there should be no internal state of BeanItem, and yes I don't want to trigger ValueChangeEvent when the data changes happens on DTO side.

**Comment by Ansku** [comment]
It's not the BeanItem's state that is inconsistent, it's the ComboBox internal state. When you update through BeanItem, the BeanItem takes care of keeping the DTO state and the component state in sync and triggering all the expected events. That's pretty much the whole purpose of the BeanItem. When you update the DTO directly you skip all that logic, and the ComboBox doesn't know it should update its internal state, because it doesn't get any events from it. You could of course add the listening logic yourself to get around that, but the end result would be the same -- ValueChangeEvent is triggered no matter where the value change comes from. Buffering doesn't mean that the component no longer has internal state, it means that when the component's internal state changes those changes are forwarded to the data source immediately instead of waiting for explicit command.

There is a discrepancy in how ComboBox handles the internal state versus data source, you are absolutely correct about that, but I'd be inclined to fix it to the direction where the ComboBox never updates at all when the internal state isn't updated, and that's pretty much opposite of what this issue asks for. Updating through the data source would still be supported, as it is now, but that data source is the BeanItem, not the DTO.

**Comment by doctorlux** [comment]
Ok, so there is different behaviour of ComboBox and TextField? TextField for example doesn't have this problem at all.

**Comment by Ansku** [comment]
I'm afraid I can't reproduce that, when I try to bind to a TextField it behaves exactly the same -- ValueChangeEvent when I set the initial value manually, no ValueChangeEvent from updating the DTO directly, no ValueChangeEvent when setting the initial value back manually, and ValueChangeEvent from all three if the middle step updates through Beanitem instead.
