### ISSUE TITLE
Vaadin 8: Null pointer exception when converting blank field

### ISSUE THREAD

**Issue by sergetania** [vaadin/framework#9916]
A null pointer exception is thrown when the user deletes all characters from the field (the field is blank). To see this in the attached project navigate to 
[http://localhost:8080/v8-nativeselect/#!Blank](url)
```
public class CalcFocusView extends VerticalLayout implements View {

  public class Data {
    private double amount;
    public double getAmount() {
      return amount;
    }
    public void setAmount(double amount) {
      this.amount = amount;
    }
  }

  private Data data;
 
  @Override
  public void enter(ViewChangeEvent event) {
    data = new Data();
    TextField field = new TextField("Enter amount");
    addComponent(field);
    Binder<Data> binder = new Binder<>(Data.class);
    binder.forField(field).withValidator(value->value != null, "Empty value").withConverter(new StringToDoubleConverter("Please enter an amount")).bind("amount");
    binder.setBean(data);
  }
}
```
[v8-errors.zip](https://github.com/vaadin/framework/files/1268321/v8-errors.zip)

Exception:

> null
sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.vaadin.data.BeanPropertySet.invokeWrapExceptions(BeanPropertySet.java:367) com.vaadin.data.BeanPropertySet.access$200(BeanPropertySet.java:48) com.vaadin.data.BeanPropertySet$BeanPropertyDefinition.lambda$getSetter$2658adf8$1(BeanPropertySet.java:187) com.vaadin.data.Binder$BindingImpl.lambda$writeFieldValue$22abd369$1(Binder.java:951) com.vaadin.data.SimpleResult.handle(SimpleResult.java:78) com.vaadin.data.Result.ifOk(Result.java:146) com.vaadin.data.Binder$BindingImpl.writeFieldValue(Binder.java:951) com.vaadin.data.Binder$BindingImpl.handleFieldValueChange(Binder.java:918) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510) com.vaadin.event.EventRouter.fireEvent(EventRouter.java:211) com.vaadin.event.EventRouter.fireEvent(EventRouter.java:174) com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1030) com.vaadin.ui.AbstractField.setValue(AbstractField.java:144) com.vaadin.ui.AbstractTextField$AbstractTextFieldServerRpcImpl.setText(AbstractTextField.java:58) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...

**Comment by tsuoanttila** [comment]
When defining Converters, you should handle `null` values. There's a `withNullRepresentation` method that does both ways conversion (`null -> representation -> null`) and should help with this functionality quite a lot.

**Comment by Legioth** [comment]
The main problem here is that the `Empty value` validator looks for `null` instead of `""`. The value of a `TextField` in Vaadin 8 will never be `null`, which means that the validator is never triggered.

It has been suggested that `StringToDoubleConverter` should produce some other `Double` value instead of `null` when the input is `""`, but it's not really clear what value that should be. That's why there's an alternative constructor of `StringToDoubleConverter` through which you can also chose the `Double` value to use instead of the default `null` value.

**Comment by Legioth** [comment]
To summarise:
* When binding to a primitive value in the bean (e.g. `double` in this case), you have to make an explicit choice between disallowing or changing empty input.
  * Disallow by using a validator that checks for `value -> !value.isEmpty()`
  * Convert by defining which `Double` value to use for converting `""` instead of the default `null` conversion: `new StringToDoubleConverter(0d, "Please enter an amount")`.
* When binding to a non-primitive value (e.g. `Double`), you instead have to protect the `TextField` against `null` values from the bean. This can be done with a custom converter or with the shorthand `withNullRepresentation` method, e.g. `withNullRepresentation("")`. The shorthand applies the same transformation in both direction, so you do typically need to do anything special about empty values from the field.
