### ISSUE TITLE
Navigator navigateTo inconsistent when navigating to the current view

### ISSUE THREAD

**Issue by pontusbostrom** [vaadin/framework#9940]
The navigator behaves differently when navigating (with navigateTo) to the current view, depending on how the view was added. If the view was added as an instance nothing happens, and enter is not called. If the view was added as a class, then the view is re-created and enter is called.  This is probably related to issue #7841

The problem occurs at least in Vaadin 8.1

Refreshing a view by navigating to it again can be a quite handy way of refreshing it.

**Comment by matheusjardimb** [comment]
Any progress in here?

**Comment by downdrown** [comment]
Guys ... this is a major Problem for many of us, it would be great if you wouldn't just ignore these issues and leave a comment like "yeah, we're having a look at it" or something similar ...

**Comment by tsuoanttila** [comment]
Original issue about not doing the `enter` twice #4112 was fixed back in the day, I made a fix to allow navigation again to the same UI with different parameters as it was even more broken. I'm not sure how we should fix it so that user who calls `navigateTo(someState)` twice in a row won't hit twice the same `enter` method but so that it would work in the case where you actually want to refresh the View. Any ideas?
