### ISSUE TITLE
BinderValidationStatusHandler does not behave correctly when using buffered mode with bean level validator

### ISSUE THREAD

**Issue by peterl1084** [vaadin/framework#9955]
If applying bean level validator to Binder by saying binder.withValidator and having a special BinderValidationStatusHandler assigned to Binder by saying binder.setValidationStatusHandler the validation status handler does not get triggered for bean level validation errors if the bean is bound with buffered writeBean mode.

Simply, having buffering enabled will fail to communicate the bean level validation results to BinderValidationStatusHandler as it only gets trigger on field value changes. As bean level validation requires that all the relevant properties are written into the bean prior running the validation the BinderValidationStatusHandler is invoked too early or only when bean properties change in non-buffered (setBean) mode. 

The problem is that if setBean is used, bean level validation failure will not cause reversal of the already set values, whereas if writeBean is used the BinderValidationStatusHandler will never see the bean in such state that would correctly trigger the custom logic that the handler is supposed to do.

Reverting works correctly if writeBean is used and BinderValidationStatusHandler works correctly if setBean is used but together they will not work.

How they should work is that if there is a bean level validator its validation results will also be communicated to BinderValidationStatusHandler upon invoking writeBean, currently this does not happen.

**Comment by nikkijuk** [comment]
It seems that in 8.2.0.rc1 buffered readBean/WriteBean pair works as exprected using bean level withValidator, but there's still problem in binder.validate() method. So; if one uses binder.validate() directly (like we: to see if save button can be enabled), has not set bean with set bean (unbuffered) but wants tu use unbuffered editing (readBean/WriteBean) and there's bean level validators exception is thrown in validate().

Important part of stack trace looks like this

Caused by: java.lang.IllegalStateException: Cannot validate binder: bean level validators have been configured but no bean is currently set
at com.vaadin.data.Binder.validate(Binder.java:1864) ~[vaadin-server-8.2.0.rc1.jar:8.2.0.rc1]

This same behavior is discussed at https://github.com/vaadin/framework/issues/10406

**Comment by nikkijuk** [comment]
Described my findings in separate issue https://github.com/vaadin/framework/issues/10486

**Comment by TatuLund** [comment]
To me it looks like this has been addressed already in Vaadin 8.2.0, but but closing was forgotten.
